/* End-to-end checks with independent authored response fixtures.
   PLAYWRIGHT_MODULE and CHROMIUM_PATH can point to a preinstalled runtime. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {answers,event,revision}=require('./core.test.cjs');
const root=path.resolve(__dirname,'..'),out=process.env.QA_OUTPUT||path.resolve(root,'../../qa');fs.mkdirSync(out,{recursive:true});
const url=process.env.TEST_URL||'file://'+root+'/index.html';
let checks=0;const ok=(v,label)=>{assert.ok(v,label);checks++};
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1365,height:1000},acceptDownloads:true});await context.setOffline(true);const p=await context.newPage(),pageErrors=[],requests=[];p.on('pageerror',e=>pageErrors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
 const click=async a=>{await p.locator('[data-action="'+a+'"]').first().click()};
 const fill=async vals=>{for(const [k,v]of Object.entries(vals)){const el=p.locator('[data-field="'+k+'"]');if(await el.count()===1&&await el.isVisible()){const tag=await el.evaluate(e=>e.tagName);if(tag==='SELECT')await el.selectOption(v);else await el.fill(v)}}};
 const stage=async n=>ok(await p.locator('.progress .active').getAttribute('data-stage')===String(n),'stage '+n+'; errors: '+await p.locator('#error-summary').allTextContents());
 const noErrors=async label=>ok(await p.locator('#error-summary').count()===0,label);
 await p.goto(url);await p.screenshot({path:path.join(out,'home.png'),fullPage:true});await click('new');await stage(1);await p.locator('#team-alias').fill('QA Cedar');await fill({briefPriority1:'lodging',briefPriority2:'activities'});await click('next');await stage(2);await click('next');await stage(3);
 await fill({...answers,liters:'70'});await p.locator('[data-check="C02"]').click();ok(await p.locator('#error-summary').count()===1,'useful wrong fuel error');ok(await p.locator('#status-fuelCost').textContent()==='Checked','correct sibling retained');await p.locator('[data-help="C02"]').click();ok(await p.locator('#modal').textContent().then(t=>t.includes('240 km')&&!t.includes('75 L')),'help uses different numbers');await p.keyboard.press('Escape');ok(await p.locator('[data-help="C02"]').evaluate(e=>e===document.activeElement),'help returns focus');await fill({liters:'75'});await click('next');await stage(4);await fill(answers);await click('next');await stage(5);await fill(answers);await click('next');await stage(6);await fill(answers);await click('next');await stage(7);await click('apply-event');ok(await p.locator('#status-liters').count()===0,'unchanged fuel does not need event screen');ok(await p.locator('#status-expression').textContent().then(t=>t.includes('Needs recheck')),'event stales model');await fill({...answers,...event});await click('record-event');await noErrors('event responses pass');await click('revise');await stage(3);await p.locator('input[data-field="food"][value="balanced"]').check();await fill(revision);await click('next');await stage(4);await fill(revision);await click('next');await stage(5);await fill(revision);await p.screenshot({path:path.join(out,'forecast.png'),fullPage:true});await click('next');await stage(6);await fill(revision);await click('next');await stage(7);await click('next');await stage(8);
 await fill(answers);await p.locator('[data-transfer="A"]').click();await p.locator('[data-learner="B"]').click();ok(await p.locator('#f-transferExpressionA').count()===0,'one transfer visible');await fill(answers);await p.locator('[data-transfer="B"]').click();await click('finish');await noErrors('transfer correct');ok(await p.locator('.ending h2').textContent()==='Client delighted','delighted outcome');await p.screenshot({path:path.join(out,'delighted.png'),fullPage:true});
 // Persisted evidence and event survive reload; no auto-resume of the wrong session.
 const saved=await p.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes(':session:')).map(k=>JSON.parse(localStorage.getItem(k))));ok(saved.length===1,'one session');let session=saved[0];ok(session.inputs.total==='1785'&&session.eventEvidence.scenario.total==='1890','final and event snapshots');ok(session.attempts.filter(a=>a.key==='liters').map(a=>a.passed).join(',')==='false,true','first incorrect and corrected responses retained');fs.writeFileSync(path.join(out,'completed-session.json'),JSON.stringify(session,null,2));
 await p.reload();await click('sessions');await p.locator('[data-resume]').click();await stage(8);ok(await p.locator('.ending h2').textContent()==='Client delighted','resume same outcome');ok(await p.locator('#save-label').textContent()==='Loaded saved work','truthful resume status');
 // Every help group and route help can open and close.
 await p.locator('[data-stage="7"]').click();for(const g of ['C03','C04','C05','C06','C07','C08']){const btn=p.locator('[data-help="'+g+'"]').first();await btn.evaluate(e=>{e.closest('details')?.setAttribute('open','')});await btn.click();ok(await p.locator('#modal h3').count()===4,'four-part help '+g);await p.keyboard.press('Escape')}
 await p.locator('[data-stage="3"]').click();await p.locator('[data-help="C01"]').click();await p.keyboard.press('Escape');await p.locator('[data-stage="2"]').click();await p.locator('[data-help="route"]').click();await p.keyboard.press('Escape');await p.locator('[data-stage="8"]').click();await p.locator('[data-help="C09"]').click();await p.keyboard.press('Escape');
 // Print the exact native views on A4 and Letter.
 await click('proposal');ok(await p.locator('#print-root .report-page').count()===4,'four report sections');ok(!(await p.locator('#print-root').textContent()).includes('Transfer keys'),'no teacher key in student report');for(const format of ['A4','Letter'])await p.pdf({path:path.join(out,'student-'+format+'.pdf'),format,printBackground:true});await click('close');
 await click('teacher');await click('toggle-teacher');await click('teacher-print');for(const format of ['A4','Letter'])await p.pdf({path:path.join(out,'teacher-'+format+'.pdf'),format,printBackground:true});await click('close');await click('slips');ok(!(await p.locator('#print-root').textContent()).includes('880'),'slips omit answers');await p.pdf({path:path.join(out,'transfer-slips.pdf'),format:'A4',printBackground:true});await click('close');
 // Responsive layouts and touch-equivalent viewport sizes.
 for(const [name,w,h]of [['portrait',768,1024],['landscape',1024,768],['phone',390,844]]){await p.setViewportSize({width:w,height:h});ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow '+name);await p.screenshot({path:path.join(out,name+'.png'),fullPage:true})}await p.setViewportSize({width:1365,height:1000});
 // Export, duplicate, delete cancellation and restored backup.
 const exportPromise=p.waitForEvent('download');await click('export');const exported=await exportPromise;await exported.saveAs(path.join(out,'exported.json'));const downloaded=JSON.parse(fs.readFileSync(path.join(out,'exported.json'),'utf8'));ok(downloaded.sessionId===session.sessionId,'export identity');await click('duplicate-active');await click('sessions');ok(await p.locator('[data-resume]').count()===2,'duplicate separate session');await click('delete-all');await click('close');await click('sessions');ok(await p.locator('[data-resume]').count()===2,'delete cancel preserves');await click('delete-all');const backupPromise=p.waitForEvent('download');await click('backup-selected');await (await backupPromise).saveAs(path.join(out,'backup.json'));await click('confirm-delete');ok(await p.locator('[data-resume]').count()===0,'clear all empty');await p.locator('#import-file').setInputFiles(path.join(out,'backup.json'));await p.waitForFunction(()=>['Review import','Import was not applied'].includes(document.querySelector('#modal-title')?.textContent));ok((await p.locator('#modal').textContent()).includes('2 session(s) validated'),'backup preview');await click('import-copy');await click('sessions');ok(await p.locator('[data-resume]').count()===2,'backup restored two');await click('close');
 // Wrong-project import is rejected without changing saved work.
 const bad={...downloaded,projectId:'other'};fs.writeFileSync(path.join(out,'wrong-project.json'),JSON.stringify(bad));await p.locator('#import-file').setInputFiles(path.join(out,'wrong-project.json'));await p.waitForFunction(()=>['Review import','Import was not applied'].includes(document.querySelector('#modal-title')?.textContent));ok((await p.locator('#modal').textContent()).includes('not applied'),'bad import rejected');await click('close');ok(await p.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes(':session:')).length)===2,'bad import preserves sessions');
 // Markup is inert text after import.
 const hostile={...downloaded,teamAlias:'<img src=x onerror=alert(1)>'};fs.writeFileSync(path.join(out,'markup.json'),JSON.stringify(hostile));await p.locator('#import-file').setInputFiles(path.join(out,'markup.json'));await p.waitForFunction(()=>['Review import','Import was not applied'].includes(document.querySelector('#modal-title')?.textContent));ok(await p.locator('#modal img').count()===0,'preview escapes markup');await click('import-copy');ok(await p.locator('#app img').count()===0,'app escapes markup');
 // Cross-tab conflict offers a copy, retaining both edits.
 await click('sessions');const activeId=await p.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes(':session:')).map(k=>JSON.parse(localStorage.getItem(k))).find(s=>s.teamAlias.startsWith('<img')).sessionId);await click('close');const p2=await context.newPage();await p2.goto(url);await p2.locator('[data-action="sessions"]').first().click();await p2.locator('[data-resume="'+activeId+'"]').click();await p2.locator('[data-action="save"]').click();ok(await p.locator('#storage-notice').textContent().then(t=>t.includes('newer copy')),'storage conflict banner');await click('copy-conflict');ok(await p.locator('#save-label').textContent()==='Loaded saved work','conflict copy saved');await p2.close();
 ok(pageErrors.length===0,'no page exceptions: '+pageErrors.join('; '));ok(requests.length===0,'no external asset requests');await browser.close();const result={suite:'Road Trip browser journey',browser:'Chromium',offline:true,checks,passed:checks,failed:0,pageErrors,externalRequests:requests.length};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));})().catch(e=>{console.error(e);process.exit(1)});
