/* Independent application checks. Run: node tests/core.test.cjs */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../src/core.js'),cases=require('./reference-cases-v0.1.0.json');let count=0;
const eq=(a,b,label)=>{assert.equal(a,b,label);count++},ok=(a,label)=>{assert.ok(a,label);count++},reject=(f,label)=>{assert.throws(f,undefined,label);count++};
const answers={classOne:'once',classFuel:'once',classVehicle:'day',classHotel:'night',classFood:'day',classActivities:'day',liters:'75',fuelCost:'120',partyFood:'60',nights:'6',hotelExpression:'90(d-1)',expression:'220d+230',slope:'220',constant:'230',slopeMeaning:'daily',constantMeaning:'adjusted',domain:'whole',table1:'450',table3:'890',table5:'1330',table7:'1770',xAxis:'days',yAxis:'cost',yStep:'200',x1:'1',y1:'450',x3:'3',y3:'890',x5:'5',y5:'1330',x7:'7',y7:'1770',budgetLine:'1800',budgetShape:'horizontal',rise:'220',inequality:'220d+230<=1800',bound:'157/22',maxDays:'7',costAtMax:'1770',nextDayCost:'1990',total:'1770',reserve:'30',percent:'98.33',lodgingPriority:'yes',activityPriority:'yes',recommendation:'recommend',evidenceType:'reserve',evidenceValue:'30',reason:'The plan keeps preferred lodging and activities with $30 left.',deltaSlope:'20',deltaConstant:'-20',deltaTotal:'120',deltaReason:'nights',transferExpressionA:'160d+240',transferTotalA:'880',transferExpressionB:'145d+310',transferTotalB:'1180'};
const event={hotelExpression:'110(d-1)',expression:'240d+210',slope:'240',constant:'210',table1:'450',table3:'930',table5:'1410',table7:'1890',y1:'450',y3:'930',y5:'1410',y7:'1890',rise:'240',inequality:'240d+210<=1800',bound:'53/8',maxDays:'6',costAtMax:'1650',nextDayCost:'1890',total:'1890',reserve:'-90',percent:'105',recommendation:'revise',evidenceValue:'-90',reason:'The hotel increase makes the plan exceed the budget by $90.',reserveStatement:'Reduce food spending while retaining the top priorities.'};
const revision={partyFood:'45',expression:'225d+210',slope:'225',constant:'210',table1:'435',table3:'885',table5:'1335',table7:'1785',y1:'435',y3:'885',y5:'1335',y7:'1785',rise:'225',inequality:'225d+210<=1800',bound:'106/15',maxDays:'7',costAtMax:'1785',nextDayCost:'2010',total:'1785',reserve:'15',percent:'99.17',recommendation:'recommend',evidenceValue:'15',reason:'The new food plan leaves $15 while keeping lodging and activities.'};
function put(s,vals){for(const [k,v]of Object.entries(vals))C.setInput(s,k,v)}
function base(){const s=C.newSession('QA Cedar');s.maxStage=8;s.currentStage=8;put(s,answers);eq(C.check(s,C.baseKeys).length,0,'base responses');return s}
function eventDone(){const s=base();C.applyEvent(s);put(s,event);eq(C.check(s,C.baseKeys.concat(C.groups.C08)).length,0,'event responses');C.recordEvent(s);return s}
for(const [name,input] of [['factored','200+120+40d+90(d-1)+3*20d+30d'],['expanded','220d+230'],['unicode','40d + 90(d−1) + 60d + 30d + 320'],['division','440d/2+460/2']])ok(C.equivalent(input,220,230),name);
ok(!C.equivalent('220d+200',220,230),'wrong intercept rejected');ok(!C.equivalent('200d+370',220,230),'one correct total is insufficient');
for(const v of ['d*d','d^2','1/0','Infinity','NaN','0x10','1,2','alert(1)','<img src=x>','d+','x+2','(d+2','1/(d+1)','9'.repeat(33),'('.repeat(17)+'1'+')'.repeat(17)])reject(()=>C.linear(v),'parser reject '+v);
for(const [v,unit,w]of [['$1,800','USD','1800'],['75 L','L','75'],['98.33%','%','9833/100'],['−3/4','','-3/4'],['(1800-230)/220','','157/22']])eq(C.numeric(v,unit).str(),w,'numeric '+v);
reject(()=>C.numeric('75 km','L'));reject(()=>C.numeric('120 USD/day','USD'));reject(()=>C.numeric('60 USD','USD/day'));eq(C.numeric('$60 USD/day','USD/day').str(),'60');eq(C.numeric('60 dollars / day','USD/day').str(),'60');eq(C.q('1.005').round(2).str(),'101/100');eq(C.q('-1.005').fixed(2),'-1.01');
for(const input of ['220d+230<=1800','1800>=220d+230','d<=157/22','440d+460<=3600'])ok(C.inequality(input,220,230,1800),input);
for(const input of ['220d+230>=1800','d<=7','220d<=1800'])ok(!C.inequality(input,220,230,1800),input);reject(()=>C.inequality('d=7',220,230,1800));
for(const test of cases.cases){const s=C.newSession();['vehicle','hotel','food','activities'].forEach((k,i)=>s.inputs[k]=test.selection[i]);s.eventApplied=test.event;if(test.distanceKm)s.inputs.routeDistance=test.distanceKm;const m=C.scenario(s),e=test.expected;const map={liters:'liters',fuelCost:'K',m:'m',b:'b',total:'total',reserve:'reserve',percentSpent:'percent',continuousBound:'bound'};for(const [k,target]of Object.entries(map))if(e[k]!==undefined)eq(m[target].str(),C.numeric(e[k]).str(),test.id+' '+k);if(e.maxDays!==undefined)eq(m.max,e.maxDays,test.id+' max');if(e.fit!==undefined)eq(m.U,e.fit,test.id+' fit');if(e.table)e.table.forEach((v,i)=>eq(m.cost([1,3,5,7][i]).str(),v,test.id+' table'));if(e.reserveStatementRequired!==undefined)eq(m.reserveQuestion,e.reserveStatementRequired,test.id+' reserve rule')}
let s=base();const first=s.attempts.length;eq(C.check(s,C.baseKeys).length,0);eq(s.attempts.length,first,'no duplicate checks');s.teamAlias='Changed';ok(C.baseKeys.every(k=>C.valid(s,k)),'alias preserves evidence');C.applyEvent(s);eq(C.state(s,'liters'),'verified');eq(C.state(s,'nights'),'verified');eq(C.state(s,'partyFood'),'verified');eq(C.state(s,'hotelExpression'),'needsRecheck');eq(C.state(s,'expression'),'needsRecheck');eq(C.state(s,'table1'),'needsRecheck','model dependency even equal first-day cost');reject(()=>C.setInput(s,'food','balanced'),'cannot bypass event');eq(C.applyEvent(s),false,'event once');eq(C.scenario(s).h.str(),'110');put(s,event);eq(C.check(s,C.baseKeys.concat(C.groups.C08)).length,0);C.recordEvent(s);C.check(s,C.groups.C09);eq(C.outcome(s).code,'revision');C.setInput(s,'food','balanced');eq(C.state(s,'hotelExpression'),'verified');eq(C.state(s,'liters'),'verified');eq(C.state(s,'partyFood'),'needsRecheck');eq(C.state(s,'transferExpressionA'),'verified');put(s,revision);eq(C.check(s,C.baseKeys).length,0);eq(C.outcome(s).code,'delighted');eq(s.eventBaseline.scenario.total,'1770');eq(s.eventEvidence.scenario.total,'1890');const imported=C.parseImport(JSON.stringify(s))[0];eq(C.outcome(imported).code,'delighted');ok(imported.imported);eq(imported.attempts.length,s.attempts.length);
const forged=C.clone(s);forged.inputs.total='1';eq(C.state(C.validateSession(forged),'total'),'needsRecheck');for(const mutate of [p=>p.projectId='other',p=>p.schemaVersion='2.0.0',p=>p.inputs.evil='x',p=>p.inputs.routeDistance='Infinity',p=>p.teamAlias='x'.repeat(65),p=>p.eventEvidence.scenario.total='100']){const p=C.clone(s);mutate(p);reject(()=>C.parseImport(JSON.stringify(p)))}reject(()=>C.parseImport('{bad'));reject(()=>C.parseImport(JSON.stringify({schema:'mcada-project-backup',schemaVersion:'1.0.0',projectId:'road-trip',sessions:[s,s]})));
s=eventDone();C.setInput(s,'transferModeA','paper');C.check(s,C.groups.C09);eq(C.outcome(s).code,'draft','paper needs submission');s.reviews.push({key:'transferModeA',response:'paper',reviewer:'T',status:'pending',fingerprint:C.fingerprint(s,'transferModeA')});eq(C.outcome(s).code,'revision');eq(C.reviewStatus(s,'transferModeA'),'pending');C.setInput(s,'total','123');eq(C.outcome(s).code,'draft');C.bypass(s,'C07','T','Discussion response accepted provisionally');eq(C.outcome(s).code,'provisional');C.setInput(s,'total','1890');C.check(s,C.groups.C07);eq(C.outcome(s).code,'revision');eq(s.teacherOverrides.length,1);
let wrong=base();C.setInput(wrong,'liters','70');C.check(wrong,['liters']);const attempts=wrong.attempts.filter(a=>a.key==='liters');eq(attempts.at(-1).passed,false);C.setInput(wrong,'liters','75');C.check(wrong,['liters']);eq(wrong.attempts.filter(a=>a.key==='liters').length,3);eq(C.rec(wrong,'liters').firstAttemptId,attempts[0].id);
class Mem{constructor(){this.map=new Map;this.fail=false;this.failOnce=null}get length(){return this.map.size}key(i){return [...this.map.keys()][i]}getItem(k){return this.map.get(k)??null}setItem(k,v){if(this.fail||k===this.failOnce){this.failOnce=null;throw Error('quota')}this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}}
const mem=new Mem,st=new C.Store(mem),one=eventDone();st.save(one);eq(st.list().length,1);eq(st.read(one.sessionId).imported,false,'local resume not imported');const stale=C.clone(one);st.save(one);reject(()=>st.save(stale),'conflict');const two=C.newSession('second');mem.failOnce=C.PREFIX+'index';reject(()=>st.saveMany([two]));eq(st.ids().length,1,'rollback removes partial import');mem.setItem('other-app','keep');st.remove([one.sessionId]);eq(st.ids().length,0);eq(mem.getItem('other-app'),'keep');const denied=new Mem;denied.fail=true;eq(new C.Store(denied).available,false);
const research=C.newSession();put(research,{routeMode:'researched',sourceTitle:'QA route',accessDate:'2026-09-30',routeType:'oneWay',originalDistance:'450000',originalUnit:'m',routeDistance:'900'});eq(C.routeErrors(research).length,0);research.inputs.routeDistance='450';ok(C.routeErrors(research).length>0);research.inputs.routeDistance='3000';research.inputs.originalDistance='1500000';ok(C.routeErrors(research).length>0);research.inputs.routeReviewed='verified';eq(C.routeErrors(research).length,0);
// Independently calculate all 81 catalogs before and after the event with integer cents.
for(const v of C.CAT.vehicle)for(const h of C.CAT.hotel)for(const f of C.CAT.food)for(const a of C.CAT.activities)for(const changed of [false,true]){const z=C.newSession();Object.assign(z.inputs,{vehicle:v[0],hotel:h[0],food:f[0],activities:a[0]});z.eventApplied=changed;const hotel=h[2]+(changed?20:0),m=v[2]+hotel+3*f[2]+a[2],b=320-hotel;eq(C.scenario(z).cost(7).str(),String(200+120+v[2]*7+hotel*6+3*f[2]*7+a[2]*7));eq(C.scenario(z).m.str(),String(m));eq(C.scenario(z).b.str(),String(b))}

// Boundary algebra and a partially typed route must remain recoverable.
eq(C.affordability(100,0,700).max,7);eq(C.affordability(100,0,700).bound.str(),'7');
eq(C.affordability(100,1900,1800).max,null);eq(C.affordability(50,100,1800).max,14);
const partial=C.newSession('Partial route');partial.currentStage=2;partial.maxStage=3;partial.inputs.routeDistance='900/';st.save(partial);eq(st.read(partial.sessionId).inputs.routeDistance,'900/');eq(C.canStage(partial,3),false);
const failDelete=new Mem,delStore=new C.Store(failDelete),delA=C.newSession('A'),delB=C.newSession('B');delStore.saveMany([delA,delB]);failDelete.removeItem=k=>{if(k.endsWith(delA.sessionId))throw Error('denied');failDelete.map.delete(k)};reject(()=>delStore.remove([delA.sessionId,delB.sessionId]));eq(delStore.ids().join(','),delA.sessionId);
if(require.main===module)console.log(JSON.stringify({suite:'Road Trip application core',checks:count,passed:count,failed:0},null,2));
module.exports={answers,event,revision,base,eventDone};
