/* Remaining product risks: denied/corrupt storage, teacher paths, weak endings, touch and guided input. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const C=require('../src/core.js');const {answers,event,revision,eventDone}=require('./core.test.cjs');
const root=path.resolve(__dirname,'..'),url='file://'+root+'/index.html',out=process.env.QA_OUTPUT||path.resolve(root,'../../qa');let checks=0;const ok=(v,label)=>{assert.ok(v,label);checks++};
function fixture(){const s=eventDone();C.setInput(s,'food','balanced');for(const[k,v]of Object.entries(revision))C.setInput(s,k,v);C.check(s,C.baseKeys.concat(C.groups.C09));return s}
function approved(){const s=eventDone();for(const[k,v]of Object.entries({vehicle:'basic',food:'balanced',activities:'light',partyFood:'45',expression:'195d+210',slope:'195',constant:'210',table1:'405',table3:'795',table5:'1185',table7:'1575',y1:'405',y3:'795',y5:'1185',y7:'1575',rise:'195',inequality:'195d+210<=1800',bound:'106/13',maxDays:'8',costAtMax:'1770',nextDayCost:'1965',total:'1575',reserve:'225',percent:'87.5',activityPriority:'no',recommendation:'recommend',evidenceValue:'225',reason:'Keep the lodging, with quieter activities and $225 for a reserve.',reserveStatement:'Hold $225 for unexpected costs.'}))C.setInput(s,k,v);assert.equal(C.check(s,C.baseKeys.concat(C.groups.C09)).length,0);return s}
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});
 async function context(session,init){const c=await b.newContext({viewport:{width:768,height:1024},hasTouch:true,isMobile:true});await c.setOffline(true);if(init)await c.addInitScript(init);const p=await c.newPage();await p.goto(url);if(session){await p.evaluate(s=>{localStorage.setItem('mcada:road-trip:session:'+s.sessionId,JSON.stringify(s))},session);await p.locator('[data-action=sessions]').first().tap();await p.locator('[data-resume]').tap()}return {c,p}}
 const {c,p}=await context(fixture());const click=async a=>p.locator('[data-action="'+a+'"]').first().tap();
 await click('teacher');await click('toggle-teacher');await click('close');await p.locator('#f-transferModeA').selectOption('paper');ok(await p.locator('.ending h2').textContent()==='Draft — finish checks','paper not automatically submitted');await p.locator('[data-record-transfer=A]').tap();await p.locator('#submission-reviewer').fill('Teacher QA');await p.locator('[data-submit-transfer=A]').tap();ok(await p.locator('.ending h2').textContent()==='Client delighted','recorded paper permits client outcome');ok((await p.locator('.ending .caption').textContent()).includes('pending'),'paper review stays pending');await click('teacher');await p.locator('#reviewer').fill('Teacher QA');await p.locator('#review-key').selectOption('transferModeA');await p.locator('#review-status').selectOption('verified');await click('record-review');ok((await p.locator('.ending .caption').textContent()).includes('verified'),'review saved separately');
 await p.locator('[data-stage="6"]').tap();await p.locator('#f-total').fill('999');await p.locator('[data-check=C07]').tap();await click('teacher');await p.locator('#reviewer').fill('Teacher QA');await p.locator('#bypass-group').selectOption('C07');await p.locator('#bypass-reason').fill('Follow up after an oral discussion.');await click('bypass');await p.locator('[data-stage="8"]').tap();ok(await p.locator('.ending h2').textContent()==='Provisional — teacher review','bypass cannot claim normal completion');await p.screenshot({path:path.join(out,'provisional-touch.png'),fullPage:true});
 await p.locator('[data-stage="4"]').tap();await p.locator('#f-guided').selectOption('yes');for(const [k,v]of Object.entries({termFixed:'200',termFuel:'120',termVehicle:'40d',termHotel:'110(d-1)',termFood:'45d',termActivities:'30d'}))await p.locator('#f-'+k).fill(v);await p.locator('[data-check=C04]').tap();ok(await p.locator('#status-expression').textContent()==='Checked','guided six-term expression checked');ok(await p.locator('#f-slope').inputValue()==='225','slope not overwritten');
 // A 44-pixel label makes radio cards usable, while primary controls have native minimum dimensions.
 const sizes=await p.locator('button,input:not([type=radio]),select,textarea').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));ok(sizes.every(z=>z.w>=44&&z.h>=44),'control target sizes');await p.evaluate(()=>document.documentElement.style.fontSize='32px');ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'200% text resize reflows');await c.close();
 for(const [name,session,title]of [['approved',approved(),'Trip approved'],['revision',(()=>{const s=eventDone();C.check(s,C.groups.C09);return s})(),'Revision requested']]){const {c,p}=await context(session);ok(await p.locator('.ending h2').textContent()===title,name+' real rendered ending');await p.screenshot({path:path.join(out,name+'-touch.png'),fullPage:true});await c.close()}
 const denied=await context(null,()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('denied','SecurityError')}})});await denied.p.locator('[data-action=new]').tap();await denied.p.locator('#team-alias').fill('Memory only');await denied.p.locator('[data-action=save]').tap();ok((await denied.p.locator('#storage-notice').textContent()).includes('unavailable'),'denial banner');ok((await denied.p.locator('#save-label').textContent()).includes('Not saved'),'no false saved claim');const dp=denied.p.waitForEvent('download');await denied.p.locator('[data-action=export]').first().tap();ok((await dp).suggestedFilename().endsWith('.json'),'denied storage still exports');await denied.c.close();
 const corrupt=await context();await corrupt.p.evaluate(()=>{localStorage.setItem('mcada:road-trip:session:broken','{no');localStorage.setItem('another-project','keep')});await corrupt.p.locator('[data-action=sessions]').first().tap();ok(await corrupt.p.locator('[data-recover=broken]').count()===1,'corrupt record offers recovery');await corrupt.p.locator('[data-delete=broken]').tap();await corrupt.p.locator('[data-action=confirm-delete]').tap();ok(await corrupt.p.evaluate(()=>localStorage.getItem('another-project'))==='keep','delete preserves other app');await corrupt.c.close();
 await b.close();const result={suite:'Road Trip edge browser risks',checks,passed:checks,failed:0,touchEmulated:true,physicalDeviceTested:false};fs.writeFileSync(path.join(out,'edge-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));})().catch(e=>{console.error(e);process.exit(1)});
