/* Explicitly verify the destructive import choice against a named existing session. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const C=require('../src/core.js');const {answers}=require('./core.test.cjs');let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++};
(async()=>{const out=process.env.QA_OUTPUT||path.resolve(__dirname,'../../../qa'),browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}),ctx=await browser.newContext({acceptDownloads:true});await ctx.setOffline(true);const p=await ctx.newPage();await p.goto('file://'+path.resolve(__dirname,'../index.html'));const s=C.newSession('Replace QA');s.currentStage=2;s.maxStage=2;await p.evaluate(s=>localStorage.setItem('mcada:road-trip:session:'+s.sessionId,JSON.stringify(s)),s);await p.locator('[data-action=sessions]').first().click();await p.locator('[data-resume]').click();const before=await p.evaluate(id=>localStorage.getItem('mcada:road-trip:session:'+id),s.sessionId);const imported=C.clone(s);imported.teamAlias='Replacement QA';const file={name:'replacement.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))};
const click=async a=>p.locator('[data-action="'+a+'"]').first().click();
async function preview(){await p.locator('#import-file').setInputFiles(file);await p.waitForFunction(()=>document.querySelector('#modal-title')?.textContent==='Review import');await click('replace-preview')}
await preview();ok((await p.locator('#modal').textContent()).includes('1 named session'),'names replacement count');await click('close');ok(await p.evaluate(id=>localStorage.getItem('mcada:road-trip:session:'+id),s.sessionId)===before,'replacement cancel leaves bytes');await preview();const dl=p.waitForEvent('download');await click('backup-replace');await(await dl).saveAs(path.join(out,'replacement-backup.json'));const backup=JSON.parse(fs.readFileSync(path.join(out,'replacement-backup.json'),'utf8'));ok(backup.sessions[0].teamAlias==='Replace QA','backup contains previous work');await click('confirm-replace');const after=await p.evaluate(id=>JSON.parse(localStorage.getItem('mcada:road-trip:session:'+id)),s.sessionId);ok(after.teamAlias==='Replacement QA'&&after.imported,'confirmed replacement changes named record');ok(await p.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes(':session:')).length)===1,'replacement keeps identity');
// Delete a single session, reload, and start afresh after the empty state.
await click('sessions');await p.locator('[data-delete]').click();await click('confirm-delete');await p.reload();await click('sessions');ok(await p.locator('[data-resume]').count()===0,'single delete persists through reload');await p.locator('#modal [data-action=new]').click();ok(await p.locator('#team-alias').inputValue()==='','new session after deletion');
// Research provenance stays pending; route conversion can be completed through controls.
await p.locator('#team-alias').fill('Research QA');await p.locator('#f-briefPriority1').selectOption('lodging');await p.locator('#f-briefPriority2').selectOption('activities');await click('next');await p.locator('#f-routeMode').selectOption('researched');await p.locator('#f-sourceTitle').fill('Teacher supplied distance');await p.locator('#f-accessDate').fill('2026-09-30');await p.locator('#f-routeType').selectOption('oneWay');await p.locator('#f-originalDistance').fill('450000');await p.locator('#f-originalUnit').selectOption('m');await p.locator('#f-routeDistance').fill('900');await click('next');ok(await p.locator('.progress .active').getAttribute('data-stage')==='3','research conversion accepted');await click('swap');ok((await p.locator('.role-pill').textContent()).includes('Planner B'),'swap role control');await click('ratings');ok((await p.locator('#modal').textContent()).includes('85–100'),'rating table dialog');await click('close');await click('teacher');await click('toggle-teacher');const diagnostic=p.waitForEvent('download');await click('diagnostics');await(await diagnostic).saveAs(path.join(out,'diagnostic.json'));const d=JSON.parse(fs.readFileSync(path.join(out,'diagnostic.json'),'utf8'));ok(d.appVersion==='0.1.0'&&d.checkpoints.C01&&!('teamAlias'in d),'nonidentifying diagnostics');await click('toggle-teacher');ok(!(await p.locator('#modal').textContent()).includes('Active scenario solution key'),'leaving teacher hides key controls');await browser.close();const result={suite:'Replacement, recovery and remaining controls',checks,passed:checks,failed:0};fs.writeFileSync(path.join(out,'replacement-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));})().catch(e=>{console.error(e);process.exit(1)});
