/* Food Truck — A WILLIAM MCADA PRODUCT. App 0.1.0, content/schema 1.0.0. */
(function(root){
'use strict';
const VERSION='0.1.0', CONTENT='1.0.0', PREFIX='mcada:food-truck:', clone=x=>JSON.parse(JSON.stringify(x));
const gcd=(a,b)=>{a=a<0n?-a:a;b=b<0n?-b:b;while(b){[a,b]=[b,a%b]}return a||1n};
class Q{
 constructor(n,d=1n){n=BigInt(n);d=BigInt(d);if(!d)throw Error('The denominator cannot be zero.');if(d<0n){n=-n;d=-d}let g=gcd(n,d);this.n=n/g;this.d=d/g}
 add(b){b=q(b);return new Q(this.n*b.d+b.n*this.d,this.d*b.d)} sub(b){return this.add(q(b).neg())} mul(b){b=q(b);return new Q(this.n*b.n,this.d*b.d)} div(b){b=q(b);return new Q(this.n*b.d,this.d*b.n)} neg(){return new Q(-this.n,this.d)} eq(b){b=q(b);return this.n===b.n&&this.d===b.d} cmp(b){b=this.sub(b);return b.n<0n?-1:b.n>0n?1:0} num(){return Number(this.n)/Number(this.d)} str(){return this.d===1n?String(this.n):this.n+'/'+this.d} toJSON(){return this.str()}
 round(places=2){const scale=10n**BigInt(places),n=(this.n<0n?-this.n:this.n)*scale,c=(2n*n+this.d)/(2n*this.d);return new Q(this.n<0n?-c:c,scale)}
 fixed(places=2){const v=this.round(places),scale=10n**BigInt(places),i=v.n*scale/v.d,a=i<0n?-i:i;return (i<0n?'-':'')+(a/scale)+(places?'.'+String(a%scale).padStart(places,'0'):'')}
}
function q(v){if(v instanceof Q)return v;if(typeof v==='number'&&!Number.isFinite(v))throw Error('Use a finite number.');let s=String(v).trim();if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)||s.replace(/\D/g,'').length>12)throw Error('Use a decimal or a fraction such as 3/4.');let neg=s[0]==='-';s=s.replace(/^[+-]/,'');let [a,b='']=s.split('.');return new Q(BigInt((a||'0')+b)*(neg?-1n:1n),10n**BigInt(b.length))}
function clean(s){if(typeof s!=='string'||s.length>256)throw Error('Use an expression with at most 256 characters.');s=s.trim().replace(/[−–]/g,'-').replace(/[×·]/g,'*').replace(/÷/g,'/');if(s.includes(',')){s=s.replace(/\b\d[\d,]*(?:\.\d+)?/g,t=>{if(!t.includes(','))return t;if(!/^\d{1,3}(,\d{3})+(\.\d+)?$/.test(t))throw Error('Use a decimal point; commas only separate thousands.');return t.replace(/,/g,'')});}return s}
function linear(raw){if(String(raw).length>200)throw Error('Use at most 200 characters.');let s=clean(raw).replace(/\s/g,'');if(!s)throw Error('Enter your answer.');let ts=s.match(/(?:\d+(?:\.\d*)?|\.\d+)|x|[()+*/-]/g)||[];if(ts.join('')!==s)throw Error('Use numbers, x, parentheses, +, −, × and ÷ only.');if(ts.length>100)throw Error('Use at most 100 tokens.');let i=0,depth=0;const pair=(a,b)=>({m:q(a),b:q(b)}),add=(a,b)=>({m:a.m.add(b.m),b:a.b.add(b.b)}),neg=a=>({m:a.m.neg(),b:a.b.neg()});
 function mul(a,b){if(a.m.n&&b.m.n)throw Error('Use a linear rule; x × x is not linear.');return {m:a.m.mul(b.b).add(b.m.mul(a.b)),b:a.b.mul(b.b)}}
 function atom(){let t=ts[i++];if(t==='+'||t==='-'){let a=atom();return t==='-'?neg(a):a}if(t==='('){if(++depth>12)throw Error('Use fewer nested parentheses.');let a=expr();if(ts[i++]!==')')throw Error('Close each parenthesis.');depth--;return a}if(t==='x')return pair(1,0);if(t&&/^[\d.]/.test(t))return pair(0,q(t));throw Error('Check the numbers and operators in your expression.')}
 function term(){let a=atom();while(i<ts.length){let t=ts[i];if(t==='*'||t==='/'){i++;let b=atom();if(t==='/'){if(b.m.n)throw Error('Divide only by a constant number.');if(!b.b.n)throw Error('The denominator cannot be zero.');a={m:a.m.div(b.b),b:a.b.div(b.b)}}else a=mul(a,b)}else if(t==='x'||t==='('){a=mul(a,atom())}else break}return a}
 function expr(){let a=term();while(ts[i]==='+'||ts[i]==='-'){let t=ts[i++],b=term();a=add(a,t==='-'?neg(b):b)}return a}let ans=expr();if(i!==ts.length)throw Error('Check your parentheses and operators.');return ans;
}
function numeric(raw,unit=''){
 if(String(raw).length>64)throw Error('Use at most 64 characters.');
 let s=clean(String(raw));
 const endings={USD:/\s*(?:USD|dollars?)$/i,'USD/portion':/\s*(?:USD|dollars?)\s*\/\s*(?:portion|meal)$/i,kg:/\s*kg$/i,L:/\s*(?:L|liters?)$/i,units:/\s*(?:units?|packages?)$/i,portions:/\s*(?:portions?|meals?)$/i,'%':/\s*%$/};
 if(unit.startsWith('USD'))s=s.replace(/^\$\s*/,'');if(endings[unit])s=s.replace(endings[unit],'');
 const a=linear(s);if(a.m.n)throw Error('Enter a number, not a rule containing x.');return a.b;
}
function equivalent(raw,m,b){const a=linear(raw);return a.m.eq(m)&&a.b.eq(b)}
function equation(raw,m,b){const sides=clean(raw).split('=');if(sides.length!==2)throw Error('Use one equals sign.');const l=linear(sides[0]),r=linear(sides[1]),a=l.m.sub(r.m),c=l.b.sub(r.b);return !!a.n&&c.div(a).eq(q(b).div(m))}
const now=()=>new Date().toISOString(),id=()=>typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():'s-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const stages=['Festival invitation','Recipe bench','Purchasing ledger','Pricing desk','Investor pitch','Stock and service','Launch weekend','Business review'];
const labels={C01:'Scale the recipe',C02:'Purchase and cost',C03:'Contribution and markup',C04:'Three business functions',C05:'Break-even and first profit',C06:'Table, graph and loss',C07:'Stock, demand and service',C08:'Realized profit and waste',C09:'Compare and recommend',C10:'Individual transfer'};
const ingredients=[['grain','Grain / base','2','kg','5'],['vegetables','Vegetables','3','kg','6'],['protein','Protein','2','kg','20'],['sauce','Sauce','0.5','L','20'],['packaging','Packaging','20','units','0.60']];
const cuisines={bowl:'Rice bowl',wrap:'Wrap',noodle:'Noodles'},demand={9:120,12:90,15:60};
const help={
 C01:['Batch factor','Scale every quantity by the same factor. Use kg, L and whole packages.','Divide prepared portions by 20, then multiply each recipe quantity.','A 10-portion recipe using 1.5 kg needs 4.5 kg for 30 portions.'],
 C02:['Cost per portion','Variable costs grow with prepared stock. Fixed fees happen once.','Multiply quantity by its unit price. Include packaging. Divide variable total by prepared portions.','A $72 batch of 24 portions costs $3 per portion.'],
 C03:['Contribution and markup','Contribution is the amount from each sale available for fixed costs, then profit.','Subtract cost from price. For markup, divide that difference by cost and multiply by 100. Round to 0.1%.','Cost $8 and price $10 give $2 contribution and 25% markup.'],
 C04:['Sold-all functions','Here x means portions both prepared and sold. R is revenue, C expense, P profit.','Use x for the number of portions. Fixed expense is paid once. Enter an equivalent linear rule.','Price 11, variable cost 3 and fee 160 give R=11x, C=160+3x and P=8x−160.'],
 C05:['Break-even','At equality profit is zero. Positive profit requires revenue to be greater.','Enter the exact crossing as a fraction when necessary, then the two whole-number thresholds.','Fee 150 and contribution 6 give break-even 25 and first profit 26.'],
 C06:['Business graph','Horizontal: portions. Vertical: USD. Lines illustrate a sold-all model, not the actual festival.','Complete both tables, then enter their ordered pairs. Use exact fractions for a crossing.','Revenue 200 and expense 250 at 20 sales mean profit −50.'],
 C07:['Three sales limits','Stock, forecast demand and service capacity each limit sales.','Multiply meals/hour by hours. Sales are the smallest limit; select all limits tied at that value.','Stock 50, demand 70 and capacity 60 permit 50 sales, limited by stock.'],
 C08:['Unsold stock','Ingredients and packages for all prepared meals have been purchased.','Revenue uses sold portions. Expense uses prepared portions. Waste is prepared minus sold.','Prepare 50 at cost 3, sell 40 at price 9, fee 100: revenue 360, expense 250, profit 110, waste 10.'],
 C09:['Compare two plans','A revision can trade some profit for less waste. Either plan may be recommended.','Calculate Plan B minus Plan A. Choose a metric, enter its value, and give one short reason.','Profits 120/140 and waste 8/2 mean changes +20 profit and −6 waste.'],
 C10:['Individual transfer','Each learner submits a separate response. Paper or oral work needs a teacher record.','Apply the model or prepared-stock rule to the new given numbers.','Fee 100 with contribution 5 breaks even at 20; the next sale first earns a profit.']
};
function plan(name='A'){return {id:name,p:12,q:100,revision:0,frozen:false,raw:{xStep:'20',yStep:'200'},evidence:{},history:[]}}
function newSession(alias=''){return {schema:'mcada-project-progress',schemaVersion:'1.0.0',projectId:'food-truck',appVersion:VERSION,contentVersion:CONTENT,sessionId:id(),scenarioId:'FT-BASE',teamAlias:alias,truckName:'',cuisineId:'bowl',planner:'A',brief:false,lessonSwaps:[],currentStage:'FT-S01',maxStage:1,activePlan:'A',plans:{A:plan(),B:null},raw:{chosenPlan:'B',transferModeA:'digital',transferModeB:'digital'},evidence:{},attempts:[],reviews:[],support:[],teacherOverrides:[],completedAt:null,localRevision:0,updatedAt:now(),imported:false,duplicateOf:null}}
const stageNumber=s=>Number(s.currentStage.slice(-2));
function model(p=12,stock=100,F=450,v='4.5',D=demand[p],K=96){const price=q(p),variable=q(v),fixed=q(F),c=price.sub(variable),s=Math.min(stock,D,K),waste=stock-s,revenue=price.mul(s),expense=fixed.add(variable.mul(stock)),profit=revenue.sub(expense),crossing=c.cmp(0)>0?fixed.div(c):null;return {p:price,q:stock,v:variable,F:fixed,D,K,s,waste,revenue,expense,profit,c,crossing,firstNonLoss:crossing?Number((crossing.n+crossing.d-1n)/crossing.d):null,firstProfit:crossing?Number(crossing.n/crossing.d)+1:null,markup:c.div(variable).mul(100).round(1),wastePercent:stock?q(waste).div(stock).mul(100).round(1):null,sellThrough:stock?q(s).div(stock).mul(100).round(1):null,overstatement:variable.mul(waste),limits:['stock','demand','capacity'].filter((_,i)=>[stock,D,K][i]===s),R:x=>price.mul(x),C:x=>fixed.add(variable.mul(x)),P:x=>c.mul(x).sub(fixed)}}
const scenario=(s,pid=s.activePlan)=>{const a=s.plans[pid];if(!a)throw Error('Create Plan B first.');return model(a.p,a.q)};
const definitionCache=new WeakMap();
function definitions(s,pid=s.activePlan){const signature=JSON.stringify([pid,s.plans.A.p,s.plans.A.q,s.plans.B?.p,s.plans.B?.q,s.raw.chosenPlan,s.raw.evidenceMetric,s.raw.transferModeA,s.raw.transferModeB]);let cached=definitionCache.get(s);if(cached?.signature===signature)return cached.value;const a=s.plans[pid]||s.plans.A,m=model(a.p,a.q),D={};
const num=(g,k,label,value,unit='',hint='Recheck the calculation using the given values.')=>D[k]={g,label,kind:'numeric',expected:q(value),unit,hint};
const select=(g,k,label,expected,options,hint='Choose the statement that matches this quantity.')=>D[k]={g,label,kind:'select',expected,options,hint};
const expr=(g,k,label,slope,b,prefix)=>D[k]={g,label,kind:'expression',m:q(slope),b:q(b),prefix,hint:'Check both the coefficient of x and the constant.'};
num('C01','factor','Batch factor',a.q/20);for(const [k,n,v,u]of ingredients)num('C01','qty_'+k,n,q(v).mul(a.q/20),u,'Multiply the base recipe quantity by your batch factor.');
for(const [k,n,v,u,p]of ingredients){num('C02','base_'+k,n+' — one batch',q(v).mul(p),'USD');num('C02','prepared_'+k,n+' — prepared stock',q(v).mul(p).mul(a.q/20),'USD');select('C02','class_'+k,n+' cost type','variable',[['variable','Variable: per prepared portion'],['fixed','Fixed: once per launch']]);}
num('C02','baseTotal','One-batch variable cost',90,'USD');num('C02','preparedTotal','Prepared-stock variable cost',q('4.5').mul(a.q),'USD');num('C02','unitCost','Cost per prepared portion','4.5','USD/portion');num('C02','fixedTotal','Fixed launch expense',450,'USD');for(const k of ['stall','hire','setup'])select('C02','class_'+k,({stall:'Stall fee',hire:'Truck hire',setup:'Signs/setup'})[k]+' cost type','fixed',[['variable','Variable: per prepared portion'],['fixed','Fixed: once per launch']]);
num('C03','contribution','Contribution per sale',m.c,'USD/portion');num('C03','markup','Markup — nearest 0.1%',m.markup,'%','Divide the increase by cost, not by selling price.');select('C03','markupBase','Markup denominator','cost',[['cost','Cost per portion'],['price','Selling price']]);select('C03','contributionMeaning','Contribution means…','cover',[['cover','Available per sale for fixed costs, then profit'],['profit','Final profit for the entire event']]);
expr('C04','revenueRule','Revenue R(x)',m.p,0,'R');expr('C04','expenseRule','Expense C(x)',m.v,m.F,'C');expr('C04','profitRule','Profit P(x)',m.c,m.F.neg(),'P');num('C04','profitSlope','Profit coefficient',m.c,'USD/portion');num('C04','profitConstant','Profit constant',m.F.neg(),'USD');select('C04','domain','Available counts','whole',[['whole','Whole portions, 0–120'],['any','Any real number is a possible sale']]);select('C04','assumption','This model assumes…','all',[['all','x portions prepared and all x sold'],['free','Unsold portions have no cost']]);
D.breakEquation={g:'C05',label:'Break-even equality',kind:'equation',m:m.c,b:m.F.neg(),hint:'Set revenue equal to expense, or profit equal to zero.'};num('C05','crossing','Exact continuous crossing',m.crossing,'portions','Use an exact fraction if the crossing is not a whole number.');num('C05','firstNonLoss','First whole count with no loss',m.firstNonLoss,'portions');num('C05','firstProfit','First whole count with positive profit',m.firstProfit,'portions');num('C05','profitBefore','Profit at '+(m.firstProfit-1)+' portions',m.P(m.firstProfit-1),'USD');num('C05','profitAt','Profit at '+m.firstProfit+' portions',m.P(m.firstProfit),'USD');select('C05','breakMeaning','Break-even versus profit','strict',[['strict','Zero at equality; positive profit requires more revenue than expense'],['same','Break-even is always the first profitable sale']]);
for(const x of [0,60,100])for(const kind of ['R','C']){num('C06','table'+kind+x,kind+'('+x+')',m[kind](x),'USD');num('C06','point'+kind+x+'X',kind+' point at '+x+': horizontal',x,'portions');num('C06','point'+kind+x+'Y',kind+' point at '+x+': vertical',m[kind](x),'USD');}
select('C06','xAxis','Horizontal axis','portions',[['portions','Portions'],['USD','USD']]);select('C06','yAxis','Vertical axis','USD',[['portions','Portions'],['USD','USD']]);D.xStep={g:'C06',label:'Horizontal tick interval',kind:'choice',options:['10','20','30'].map(x=>[x,x]),hint:'Choose a uniform interval.'};D.yStep={g:'C06',label:'Vertical tick interval',kind:'choice',options:['100','200','300'].map(x=>[x,x]),hint:'Choose a uniform interval.'};num('C06','crossX','Crossing: horizontal',m.crossing,'portions');num('C06','crossY','Crossing: vertical',m.R(m.crossing),'USD');num('C06','lossAt30','Profit at 30 portions',m.P(30),'USD');select('C06','lossMeaning','A loss means…','expense',[['expense','Expense exceeds revenue'],['revenue','Revenue exceeds expense']]);
num('C07','capacity','Service capacity',96,'portions');num('C07','forecastDemand','Demand at your price',m.D,'portions');num('C07','sales','Predicted sales',m.s,'portions');D.limits={g:'C07',label:'All limits tied at predicted sales',kind:'set',expected:m.limits,options:[['stock','Prepared stock'],['demand','Forecast demand'],['capacity','Service capacity']],hint:'Choose every quantity equal to the smallest limit.'};
num('C08','actualRevenue','Revenue from sales',m.revenue,'USD');num('C08','actualExpense','Expense for all prepared stock',m.expense,'USD','Expense includes all prepared portions, not only sold portions.');num('C08','actualProfit','Realized profit',m.profit,'USD');num('C08','waste','Unsold portions',m.waste,'portions');num('C08','wastePercent','Waste — nearest 0.1%',m.wastePercent,'%');num('C08','sellThrough','Sell-through — nearest 0.1%',m.sellThrough,'%');select('C08','costBasis','Variable expense uses…','prepared',[['prepared','All prepared portions'],['sold','Only sold portions']]);num('C08','overstatement','Sold-all P(s) overstates profit by…',m.overstatement,'USD');
const A=scenario(s,'A'),B=s.plans.B?scenario(s,'B'):A,chosen=s.raw.chosenPlan==='A'?A:B;num('C09','deltaProfit','Profit change: B − A',B.profit.sub(A.profit),'USD');num('C09','deltaWaste','Waste change: B − A',B.waste-A.waste,'portions');D.chosenPlan={g:'C09',label:'Recommend this plan',kind:'choice',options:[['A','Plan A'],['B','Plan B']]};D.evidenceMetric={g:'C09',label:'Quantity supporting your choice',kind:'choice',options:[['profit','Chosen plan profit'],['waste','Chosen plan waste'],['wastePercent','Chosen plan waste %'],['sales','Chosen plan sales'],['deltaProfit','B − A profit'],['deltaWaste','B − A waste']]};const metrics={profit:[chosen.profit,'USD'],waste:[chosen.waste,'portions'],wastePercent:[chosen.wastePercent,'%'],sales:[chosen.s,'portions'],deltaProfit:[B.profit.sub(A.profit),'USD'],deltaWaste:[B.waste-A.waste,'portions']},metric=metrics[s.raw.evidenceMetric]||metrics.profit;num('C09','evidenceValue','Your numerical evidence',metric[0],metric[1]);D.reason={g:'C09',label:'One sentence supporting your recommendation',kind:'text',hint:'Give one short reason, or ask the teacher to record your oral response.'};
for(const who of ['A','B'])D['transferMode'+who]={g:'C10',label:'Learner '+who+' response mode',kind:'choice',options:[['digital','Digital'],['paper','Paper — teacher records submission'],['oral','Oral — teacher records submission']]};
expr('C10','transferARule','Learner A: profit rule',9,-360,'P');num('C10','transferACross','Learner A: break-even',40,'portions');num('C10','transferAFirst','Learner A: first positive profit',41,'portions');for(const [key,label,value,unit]of [['Revenue','revenue',560,'USD'],['Expense','expense',480,'USD'],['Profit','profit',80,'USD'],['Waste','waste',14,'portions'],['Sell','sell-through',80,'%']])num('C10','transferB'+key,'Learner B: '+label,value,unit);select('C10','transferBBasis','Learner B: expense basis','prepared',[['prepared','All prepared portions'],['sold','Only sold portions']]);
for(const [key,d]of Object.entries(D)){d.key=key;d.id='FT-F'+d.g.slice(1)+'.'+key;d.objectiveId='FT-'+d.g.slice(1);d.global=['C09','C10'].includes(d.g);d.reviewPolicy=d.kind==='text'?'submitted — teacher review':'exact mathematical/structural check';d.help=help[d.g];if(d.g==='C10'&&!key.startsWith('transferMode')){const who=key.startsWith('transferA')?'A':'B';if(s.raw['transferMode'+who]!=='digital')d.kind='notRequired';}}
definitionCache.set(s,{signature,value:D});return D;
}
function target(s,key,pid=s.activePlan){return definitions(s,pid)[key]?.global?s:s.plans[pid]}
function fingerprint(s,key,pid=s.activePlan){const d=definitions(s,pid)[key],val=d.kind==='numeric'?d.expected.str():['expression','equation'].includes(d.kind)?[d.m.str(),d.b.str()]:d.expected||d.options||d.kind;return JSON.stringify([CONTENT,key,d.kind,val,d.g==='C09'?[s.plans.A.p,s.plans.A.q,s.plans.B?.p,s.plans.B?.q,s.raw.chosenPlan,s.raw.evidenceMetric]:null])}
function evaluate(s,key,raw,pid=s.activePlan){const d=definitions(s,pid)[key];if(!d)return 'Unknown field.';try{if(d.kind==='notRequired')return null;if(!String(raw??'').trim())return 'Enter '+d.label.toLowerCase()+'.';if(d.kind==='numeric')return numeric(raw,d.unit).eq(d.expected)?null:d.hint;if(d.kind==='expression'){let text=String(raw).replace(new RegExp('^\\s*'+d.prefix+'\\s*\\(\\s*x\\s*\\)\\s*=','i'),'');return equivalent(text,d.m,d.b)?null:d.hint;}if(d.kind==='equation')return equation(raw,d.m,d.b)?null:d.hint;if(d.kind==='select')return raw===d.expected?null:d.hint;if(d.kind==='choice')return d.options.some(x=>x[0]===raw)?null:'Choose an option.';if(d.kind==='set')return JSON.stringify(String(raw).split(',').filter(Boolean).sort())===JSON.stringify([...d.expected].sort())?null:d.hint;if(d.kind==='text')return raw.trim().length<=600?null:'Use at most 600 characters.';}catch(e){return e.message}return null}
function fieldState(s,key,pid=s.activePlan){const d=definitions(s,pid)[key];if(d.kind==='notRequired')return 'notRequired';const t=target(s,key,pid),r=t.evidence[key];if(!r)return 'unstarted';if(r.fingerprint!==fingerprint(s,key,pid)||r.response!==(t.raw[key]||''))return 'needsRecheck';return r.status}
const valid=(s,key,pid=s.activePlan)=>['verified','overridden','notRequired'].includes(fieldState(s,key,pid));
const keys=(s,g,pid=s.activePlan)=>{const d=definitions(s,pid);return Object.keys(d).filter(k=>d[k].g===g)};
const groupOK=(s,g,pid=s.activePlan)=>keys(s,g,pid).every(k=>valid(s,k,pid));
function check(s,g,pid=s.activePlan){if(s.attempts.length+keys(s,g,pid).length>10000)throw Error('History limit reached. Export this session and begin a new one.');const errors=[];for(const k of keys(s,g,pid)){if(fieldState(s,k,pid)==='verified'||fieldState(s,k,pid)==='notRequired')continue;const t=target(s,k,pid),raw=t.raw[k]||'',error=evaluate(s,k,raw,pid),fp=fingerprint(s,k,pid),old=t.evidence[k],attempt={id:id(),key:k,checkpoint:g,plan:definitions(s,pid)[k].global?'session':pid,revision:s.plans[pid].revision,response:raw,passed:!error,timestamp:now(),fingerprint:fp,context:{p:s.plans[pid].p,q:s.plans[pid].q}};s.attempts.push(attempt);t.evidence[k]={status:error?'inProgress':'verified',response:raw,fingerprint:fp,firstAttemptId:old?.fingerprint===fp?old.firstAttemptId:attempt.id,lastAttemptId:attempt.id};if(error)errors.push({key:k,message:error});}return errors}
function setRaw(s,key,value){const d=definitions(s)[key];if(!d)throw Error('Unknown field.');if(!d.global&&s.plans[s.activePlan].frozen)throw Error('Plan A is preserved. Create Plan B or duplicate this session.');if(String(value).length>(d.kind==='text'?600:200))throw Error('This answer is too long.');target(s,key).raw[key]=String(value)}
function changePlan(s,key,value){const a=s.plans[s.activePlan];if(a.frozen)throw Error('Plan A is preserved. Change Plan B instead.');value=Number(value);if(key==='p'?![9,12,15].includes(value):key==='q'?![60,80,100,120].includes(value):true)throw Error('Choose a supported price or stock.');if(a[key]===value)return;if(a.history.length>=100)throw Error('Revision limit reached. Export and start a new comparison.');a.history.push({p:a.p,q:a.q,revision:a.revision,at:now()});a[key]=value;a.revision++;}
function allPlanOK(s,pid){return !!s.plans[pid]&&['C01','C02','C03','C04','C05','C06','C07','C08'].every(g=>groupOK(s,g,pid))}
function freeze(s){if(s.plans.A.frozen)return false;if(!allPlanOK(s,'A'))throw Error('Finish the Plan A checks first.');s.plans.A.frozen=true;return true}
function createB(s){if(!s.plans.A.frozen)throw Error('Finish the first launch first.');if(!s.plans.B){s.plans.B=clone(s.plans.A);s.plans.B.id='B';s.plans.B.frozen=false;s.plans.B.history=[];for(const r of Object.values(s.plans.B.evidence))r.carriedFrom='A';}s.activePlan='B';s.currentStage='FT-S06';return s.plans.B}
function different(s){return s.plans.B&&(s.plans.A.p!==s.plans.B.p||s.plans.A.q!==s.plans.B.q)}
function transferSubmitted(s,who){return s.raw['transferMode'+who]==='digital'||s.reviews.some(r=>r.key==='transferMode'+who&&r.response===s.raw['transferMode'+who]&&r.reviewer.trim()&&r.note.trim())}
function business(m){if(m.profit.cmp(0)<0)return {code:'rethink',title:'Business rethink'};if(m.profit.cmp(150)>=0&&10*m.waste<=m.q)return {code:'success',title:'Festival success'};return {code:'viable',title:'Viable first launch'}}
function outcome(s){if(!s.plans.A.frozen||!different(s)||!allPlanOK(s,'A')||!allPlanOK(s,'B')||!groupOK(s,'C09')||!groupOK(s,'C10')||!['A','B'].every(a=>transferSubmitted(s,a)))return {code:'draft',title:'Draft — finish checks'};const overridden=['A','B'].some(pid=>Object.keys(definitions(s,pid)).some(k=>!definitions(s,pid)[k].global&&fieldState(s,k,pid)==='overridden'))||Object.keys(s.evidence).some(k=>fieldState(s,k)==='overridden');if(overridden)return {code:'provisional',title:'Provisional — teacher review'};return business(scenario(s,s.raw.chosenPlan))}
function bypass(s,g,reviewer,reason){if(!reviewer.trim()||reviewer.length>64||!reason.trim()||reason.length>400)throw Error('Enter reviewer alias and a reason (up to 400 characters).');if(!labels[g])throw Error('Unknown checkpoint.');for(const key of keys(s,g)){const t=target(s,key);if(t.frozen)throw Error('Plan A is preserved; duplicate for a new comparison.');if(!valid(s,key))t.evidence[key]={status:'overridden',response:t.raw[key]||'',fingerprint:fingerprint(s,key),firstAttemptId:null,lastAttemptId:null};}s.teacherOverrides.push({checkpoint:g,plan:s.activePlan,reviewer,reason,at:now()})}
function review(s,key,reviewer,note,status='pending'){if(!['reason','transferModeA','transferModeB'].includes(key)||!reviewer.trim()||reviewer.length>64||!note.trim()||note.length>400||!['pending','verified','revise'].includes(status))throw Error('Enter reviewer alias, note and review status.');if(key==='reason'&&!s.raw.reason){s.raw.reason='Oral response recorded: '+note;check(s,'C09');}s.reviews.push({key,response:s.raw[key]||'',fingerprint:fingerprint(s,key),reviewer,note,status,at:now()})}
function reviewStatus(s,key){return [...s.reviews].reverse().find(r=>r.key===key&&r.response===(s.raw[key]||'')&&r.fingerprint===fingerprint(s,key))?.status||'pending'}
function stageGroups(n){return ({2:['C01'],3:['C02'],4:['C03'],5:['C04','C05','C06'],6:['C07'],7:['C08'],8:['C09','C10']})[n]||[]}
function missing(s,n){let gs=[];for(let i=2;i<n;i++)gs.push(...stageGroups(i));return gs.filter(g=>!groupOK(s,g))}
function duplicate(s,fresh=false){const c=clone(s);c.sessionId=id();c.localRevision=0;c.duplicateOf=s.sessionId;c.teamAlias=(s.teamAlias+' — copy').slice(0,64);if(fresh){const a=clone(s.plans[s.raw.chosenPlan]||s.plans.A);a.id='A';a.frozen=false;a.history=[];c.plans={A:a,B:null};c.activePlan='A';c.currentStage='FT-S02';c.raw={chosenPlan:'B',transferModeA:'digital',transferModeB:'digital'};c.evidence={};c.completedAt=null;}return c}
function validateSession(raw,imported=true){
const fail=msg=>{throw Error(msg)},obj=x=>x&&typeof x==='object'&&!Array.isArray(x),allowed=(o,ks)=>obj(o)&&Object.keys(o).every(k=>ks.includes(k)),str=(x,n)=>typeof x==='string'&&x.length<=n;
if(!obj(raw)||!allowed(raw,Object.keys(newSession())))fail('Unsupported session fields.');if(raw.schema!=='mcada-project-progress'||raw.projectId!=='food-truck')fail('This is not Food Truck progress.');if(raw.schemaVersion!=='1.0.0'||raw.contentVersion!==CONTENT||raw.appVersion!==VERSION)fail('Unsupported or future application/content/schema version.');
if(!str(raw.sessionId,100)||!/^[-\w]+$/.test(raw.sessionId)||!str(raw.teamAlias,64)||!str(raw.truckName,64)||!cuisines[raw.cuisineId]||!['A','B'].includes(raw.planner)||typeof raw.brief!=='boolean'||!/^FT-S0[1-8]$/.test(raw.currentStage)||!Number.isInteger(raw.maxStage)||raw.maxStage<stageNumber(raw)||raw.maxStage>8||!['A','B'].includes(raw.activePlan)||raw.scenarioId!=='FT-BASE')fail('Invalid session identity, choices or stage.');
if(!Array.isArray(raw.lessonSwaps)||raw.lessonSwaps.some(n=>![1,2].includes(n))||new Set(raw.lessonSwaps).size!==raw.lessonSwaps.length)fail('Invalid lesson boundary record.');
if(!allowed(raw.plans,['A','B'])||!raw.plans.A||!raw.plans[raw.activePlan])fail('Missing plan.');if(!Number.isSafeInteger(raw.localRevision)||raw.localRevision<0)fail('Invalid stored revision.');
for(const name of ['attempts','reviews','support','teacherOverrides'])if(!Array.isArray(raw[name])||raw[name].length>10000)fail('Invalid or oversized '+name+' history.');
function walk(v,d=0){if(d>15)fail('Save nesting is too deep.');if(typeof v==='number'&&!Number.isFinite(v))fail('Nonfinite saved value.');if(typeof v==='string'&&v.length>2000)fail('Oversized saved string.');if(v&&typeof v==='object')for(const k of Object.keys(v)){if(['__proto__','constructor','prototype'].includes(k))fail('Unsafe saved key.');walk(v[k],d+1)}}walk(raw);
const s=clone(raw),defs=definitions(s,'A');
function validateEvidence(t,isGlobal,pid){if(!obj(t.raw)||!obj(t.evidence))fail('Missing inputs or evidence.');for(const [key,value]of Object.entries(t.raw)){const d=defs[key];if(!d||d.global!==isGlobal||!str(value,d.kind==='text'?600:200))fail('Invalid saved answer: '+key)}for(const [key,r]of Object.entries(t.evidence)){if(!defs[key]||defs[key].global!==isGlobal||!allowed(r,['status','response','fingerprint','firstAttemptId','lastAttemptId','carriedFrom'])||!['verified','inProgress','overridden','needsRecheck'].includes(r.status)||!str(r.response,600)||!str(r.fingerprint,2000))fail('Invalid evidence record.');if(r.status==='overridden'&&!s.teacherOverrides.some(o=>o.checkpoint===defs[key].g&&(isGlobal||o.plan===pid||(pid==='B'&&r.carriedFrom==='A'&&o.plan==='A'&&s.plans.A.evidence[key]?.status==='overridden'))))fail('Bypass record is missing.');}}
for(const pid of ['A','B']){const p=s.plans[pid];if(!p){if(pid==='A')fail('Missing Plan A');continue}if(!allowed(p,['id','p','q','revision','frozen','raw','evidence','history'])||p.id!==pid||![9,12,15].includes(p.p)||![60,80,100,120].includes(p.q)||!Number.isSafeInteger(p.revision)||p.revision<0||typeof p.frozen!=='boolean'||!Array.isArray(p.history)||p.history.length>100)fail('Invalid plan or production choices.');if(pid==='B'&&(p.frozen||!s.plans.A.frozen))fail('Inconsistent comparison history.');for(const h of p.history)if(!allowed(h,['p','q','revision','at'])||![9,12,15].includes(h.p)||![60,80,100,120].includes(h.q)||!Number.isSafeInteger(h.revision)||h.revision<0||!str(h.at,64))fail('Invalid plan history.');validateEvidence(p,false,pid)}
validateEvidence(s,true,'A');
for(const r of s.attempts)if(!allowed(r,['id','key','checkpoint','plan','revision','response','passed','timestamp','fingerprint','context'])||!defs[r.key]||r.checkpoint!==defs[r.key].g||!['A','B','session'].includes(r.plan)||!str(r.id,100)||!str(r.response,600)||typeof r.passed!=='boolean'||!Number.isSafeInteger(r.revision)||r.revision<0||!allowed(r.context,['p','q'])||![9,12,15].includes(r.context.p)||![60,80,100,120].includes(r.context.q))fail('Invalid attempt history.');
for(const r of s.teacherOverrides)if(!allowed(r,['checkpoint','plan','reviewer','reason','at'])||!labels[r.checkpoint]||!['A','B'].includes(r.plan)||!str(r.reviewer,64)||!r.reviewer.trim()||!str(r.reason,400)||!r.reason.trim())fail('Invalid teacher bypass.');
for(const r of s.reviews)if(!allowed(r,['key','response','fingerprint','reviewer','note','status','at'])||!['reason','transferModeA','transferModeB'].includes(r.key)||!str(r.reviewer,64)||!r.reviewer.trim()||!str(r.note,400)||!r.note.trim()||!['pending','verified','revise'].includes(r.status)||!str(r.response,600)||!str(r.fingerprint,2000))fail('Invalid review.');
for(const r of s.support)if(!allowed(r,['group','plan','at'])||!labels[r.group]||!['A','B'].includes(r.plan)||!str(r.at,64))fail('Invalid support history.');
for(const pid of ['A','B'])if(s.plans[pid])for(const key of Object.keys(s.plans[pid].evidence)){const r=s.plans[pid].evidence[key];if(r.status==='verified'&&(r.fingerprint!==fingerprint(s,key,pid)||r.response!==(s.plans[pid].raw[key]||'')||evaluate(s,key,r.response,pid)))r.status='needsRecheck';}
for(const key of Object.keys(s.evidence)){const r=s.evidence[key];if(r.status==='verified'&&(r.fingerprint!==fingerprint(s,key)||r.response!==(s.raw[key]||'')||evaluate(s,key,r.response)))r.status='needsRecheck';}
s.imported=imported||raw.imported===true;return s;
}
function parseImport(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>5*1024*1024)throw Error('Import files must be at most 5 MiB.');let p;try{p=JSON.parse(text)}catch{throw Error('The file is not valid JSON.');}if(p?.schema==='mcada-project-progress-bundle'){if(p.projectId!=='food-truck'||p.schemaVersion!=='1.0.0'||Object.keys(p).some(k=>!['schema','schemaVersion','projectId','exportedAt','sessions'].includes(k))||!Array.isArray(p.sessions)||!p.sessions.length||p.sessions.length>25)throw Error('Invalid Food Truck backup bundle.');if(new Set(p.sessions.map(s=>s.sessionId)).size!==p.sessions.length)throw Error('Duplicate session identities in backup.');return p.sessions.map(s=>validateSession(s));}return [validateSession(p)]}
function bundle(sessions){if(!sessions.length||sessions.length>25)throw Error('Choose between 1 and 25 sessions for a backup.');return {schema:'mcada-project-progress-bundle',schemaVersion:'1.0.0',projectId:'food-truck',exportedAt:now(),sessions}}
class Store{
 constructor(storage){this.storage=storage;this.available=false;try{storage.setItem(PREFIX+'probe','1');if(storage.getItem(PREFIX+'probe')!=='1')throw Error('Storage check failed');storage.removeItem(PREFIX+'probe');this.available=true}catch{}}
 ids(){const a=[];if(!this.available)return a;for(let i=0;i<this.storage.length;i++){let k=this.storage.key(i);if(k?.startsWith(PREFIX+'session:'))a.push(k.slice((PREFIX+'session:').length))}return a}
 read(id){const t=this.storage.getItem(PREFIX+'session:'+id);if(t===null)return null;return validateSession(JSON.parse(t),false)}
 list(){return this.ids().map(id=>{try{return {id,session:this.read(id)}}catch(e){return {id,error:e.message}}})}
 saveMany(sessions){if(!this.available)throw Error('Device storage is unavailable. Export progress before leaving.');const keys=sessions.map(s=>PREFIX+'session:'+s.sessionId),indexKey=PREFIX+'index',all=[...keys,indexKey],old=new Map(all.map(k=>[k,this.storage.getItem(k)]));try{for(let i=0;i<sessions.length;i++)this.storage.setItem(keys[i],JSON.stringify(sessions[i]));this.storage.setItem(indexKey,JSON.stringify(this.ids()));}catch(e){let rollback=true;for(const [k,v]of old){try{if(v===null)this.storage.removeItem(k);else this.storage.setItem(k,v)}catch{rollback=false}}throw Error(rollback?'Could not save. Existing saved work was retained. Export your current work.':'Storage failed during rollback. Keep this page open and export; inspect saved sessions before continuing.')}return true}
 save(s){let prev;try{prev=this.read(s.sessionId)}catch{}if(prev&&prev.localRevision>s.localRevision)throw Error('CONFLICT');const old=s.localRevision,oldTime=s.updatedAt;s.localRevision++;s.updatedAt=now();try{this.saveMany([s])}catch(e){s.localRevision=old;s.updatedAt=oldTime;throw e}return true}
 remove(ids){let failed=[];for(const id of ids){try{this.storage.removeItem(PREFIX+'session:'+id);if(this.storage.getItem(PREFIX+'session:'+id)!==null)failed.push(id)}catch{failed.push(id)}}try{const remain=this.ids();if(remain.length)this.storage.setItem(PREFIX+'index',JSON.stringify(remain));else this.storage.removeItem(PREFIX+'index')}catch{failed.push('session index')}if(failed.length)throw Error('Deletion was incomplete. Records remaining: '+failed.join(', '));return true}
}
function diagnostics(){const checks=[['Recipe cost',ingredients.reduce((a,r)=>a.add(q(r[2]).mul(r[4])),q(0)).eq(90)],['Baseline profit',model().profit.eq(180)],['First positive profit',model().firstProfit===61],['Fractional crossing',model(15,60).crossing.eq(q(300).div(7))],['Unsold expense',model(9,120).profit.eq(-126)],['Equivalent model',equivalent('12x-(450+4.5x)',7.5,-450)]];return checks.map(([name,passed])=>({name,passed}))}
root.FTCore={VERSION,CONTENT,PREFIX,Q,q,linear,numeric,equivalent,equation,now,id,clone,stages,labels,ingredients,cuisines,demand,help,newSession,stageNumber,model,scenario,definitions,target,fingerprint,evaluate,fieldState,valid,keys,groupOK,check,setRaw,changePlan,allPlanOK,freeze,createB,different,transferSubmitted,business,outcome,bypass,review,reviewStatus,stageGroups,missing,duplicate,validateSession,parseImport,bundle,Store,diagnostics};
if(typeof module!=='undefined')module.exports=root.FTCore;
})(typeof globalThis!=='undefined'?globalThis:this);
