/* Road Trip Planner — A WILLIAM MCADA PRODUCT. App 0.1.0, content/schema 1.0.0. */
(function(root){
'use strict';
const VERSION='0.1.0', CONTENT='1.0.0', PREFIX='mcada:road-trip:', clone=x=>JSON.parse(JSON.stringify(x));
const gcd=(a,b)=>{a=a<0n?-a:a;b=b<0n?-b:b;while(b){[a,b]=[b,a%b]}return a||1n};
class Q{
 constructor(n,d=1n){n=BigInt(n);d=BigInt(d);if(!d)throw Error('The denominator cannot be zero.');if(d<0n){n=-n;d=-d}let g=gcd(n,d);this.n=n/g;this.d=d/g}
 add(b){b=q(b);return new Q(this.n*b.d+b.n*this.d,this.d*b.d)} sub(b){return this.add(q(b).neg())} mul(b){b=q(b);return new Q(this.n*b.n,this.d*b.d)} div(b){b=q(b);return new Q(this.n*b.d,this.d*b.n)} neg(){return new Q(-this.n,this.d)} eq(b){b=q(b);return this.n===b.n&&this.d===b.d} cmp(b){b=this.sub(b);return b.n<0n?-1:b.n>0n?1:0} num(){return Number(this.n)/Number(this.d)} str(){return this.d===1n?String(this.n):this.n+'/'+this.d} toJSON(){return this.str()}
 round(places=2){const scale=10n**BigInt(places),n=(this.n<0n?-this.n:this.n)*scale,c=(2n*n+this.d)/(2n*this.d);return new Q(this.n<0n?-c:c,scale)}
 fixed(places=2){const v=this.round(places),scale=10n**BigInt(places),i=v.n*scale/v.d,a=i<0n?-i:i;return (i<0n?'-':'')+(a/scale)+(places?'.'+String(a%scale).padStart(places,'0'):'')}
}
function q(v){if(v instanceof Q)return v;if(typeof v==='number'&&!Number.isFinite(v))throw Error('Use a finite number.');let s=String(v).trim();if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)||s.replace(/\D/g,'').length>32)throw Error('Use a decimal or a fraction such as 3/4.');let neg=s[0]==='-';s=s.replace(/^[+-]/,'');let [a,b='']=s.split('.');return new Q(BigInt((a||'0')+b)*(neg?-1n:1n),10n**BigInt(b.length))}
function clean(s){if(typeof s!=='string'||s.length>256)throw Error('Use an expression with at most 256 characters.');s=s.trim().replace(/[−–]/g,'-').replace(/[×·]/g,'*').replace(/÷/g,'/');if(s.includes(',')){s=s.replace(/\b\d[\d,]*(?:\.\d+)?/g,t=>{if(!t.includes(','))return t;if(!/^\d{1,3}(,\d{3})+(\.\d+)?$/.test(t))throw Error('Use a decimal point; commas only separate thousands.');return t.replace(/,/g,'')});}return s}
function linear(raw){let s=clean(raw).replace(/\s/g,'');if(!s)throw Error('Enter your answer.');let ts=s.match(/(?:\d+(?:\.\d*)?|\.\d+)|d|[()+*/-]/g)||[];if(ts.join('')!==s)throw Error('Use numbers, d, parentheses, +, −, × and ÷ only.');let i=0,depth=0;const pair=(a,b)=>({m:q(a),b:q(b)}),add=(a,b)=>({m:a.m.add(b.m),b:a.b.add(b.b)}),neg=a=>({m:a.m.neg(),b:a.b.neg()});
 function mul(a,b){if(a.m.n&&b.m.n)throw Error('Use a linear rule; d × d is not linear.');return {m:a.m.mul(b.b).add(b.m.mul(a.b)),b:a.b.mul(b.b)}}
 function atom(){let t=ts[i++];if(t==='+'||t==='-'){let a=atom();return t==='-'?neg(a):a}if(t==='('){if(++depth>16)throw Error('Use fewer nested parentheses.');let a=expr();if(ts[i++]!==')')throw Error('Close each parenthesis.');depth--;return a}if(t==='d')return pair(1,0);if(t&&/^[\d.]/.test(t))return pair(0,q(t));throw Error('Check the numbers and operators in your expression.')}
 function term(){let a=atom();while(i<ts.length){let t=ts[i];if(t==='*'||t==='/'){i++;let b=atom();if(t==='/'){if(b.m.n)throw Error('Divide only by a constant number.');if(!b.b.n)throw Error('The denominator cannot be zero.');a={m:a.m.div(b.b),b:a.b.div(b.b)}}else a=mul(a,b)}else if(t==='d'||t==='('){a=mul(a,atom())}else break}return a}
 function expr(){let a=term();while(ts[i]==='+'||ts[i]==='-'){let t=ts[i++],b=term();a=add(a,t==='-'?neg(b):b)}return a}let ans=expr();if(i!==ts.length)throw Error('Check your parentheses and operators.');return ans;
}
function numeric(raw,unit=''){let s=clean(raw);if(unit==='USD'||unit==='USD/day')s=s.replace(/^\$\s*/,'').replace(/\s*(?:USD|dollars?)(?:\/day)?$/i,'');else if(unit==='L')s=s.replace(/\s*(?:L|liters?)$/i,'');else if(unit==='%')s=s.replace(/\s*%$/,'');let a=linear(s);if(a.m.n)throw Error('Enter a number, not a rule containing d.');return a.b}
function equivalent(raw,m,b){const a=linear(raw);return a.m.eq(m)&&a.b.eq(b)}
function inequality(raw,m,b,B){let s=clean(raw).replace(/≤/g,'<=').replace(/≥/g,'>='),parts=s.split(/(<=|>=)/);if(parts.length!==3)throw Error('Use ≤ or ≥ to show the budget limit.');let l=linear(parts[0]),r=linear(parts[2]),a=l.m.sub(r.m),c=l.b.sub(r.b);if(parts[1]==='>='){a=a.neg();c=c.neg()}if(a.cmp(0)<=0)return false;return c.neg().div(a).eq(q(B).sub(b).div(m))}
const CAT={vehicle:[['basic','City compact',30,15],['standard','Coastal wagon',40,15],['touring','Touring van',60,15]],hotel:[['basic','Trail cabin',60,15],['standard','Lakeview lodge',90,30],['premium','Grand hotel',130,30]],food:[['simple','Picnic plan',10,10],['balanced','Local cafés',15,20],['full','Food explorer',20,25]],activities:[['light','Quiet days',10,10],['varied','A little of both',20,20],['full','Adventure pass',30,30]]};
const stages=['Commission','Route desk','Build the itinerary','Modeling studio','Forecast wall','Budget review','Hotel alert','Client presentation'];
const CLASS={classOne:'once',classFuel:'once',classVehicle:'day',classHotel:'night',classFood:'day',classActivities:'day'};
const labels={C01:'Classify costs',C02:'Fuel calculation',C03:'People and nights',C04:'Cost model',C05:'Table and graph',C06:'Affordability',C07:'Recommendation',C08:'Price-change revision',C09:'Individual transfer'};
const groups={C01:Object.keys(CLASS),C02:['liters','fuelCost'],C03:['partyFood','nights','hotelExpression'],C04:['expression','slope','constant','slopeMeaning','constantMeaning','domain'],C05:['table1','table3','table5','table7','xAxis','yAxis','yStep','x1','y1','x3','y3','x5','y5','x7','y7','budgetLine','budgetShape','rise'],C06:['inequality','bound','maxDays','costAtMax','nextDayCost'],C07:['total','reserve','percent','lodgingPriority','activityPriority','recommendation','evidenceType','evidenceValue','reason','reserveStatement'],C08:['deltaSlope','deltaConstant','deltaTotal','deltaReason'],C09:['transferModeA','transferExpressionA','transferTotalA','transferModeB','transferExpressionB','transferTotalB']};
const FIELD_GROUP=Object.fromEntries(Object.entries(groups).flatMap(([g,ks])=>ks.map(k=>[k,g])));
const setupKeys=['briefPriority1','briefPriority2','planner','routeMode','sourceTitle','sourceLink','accessDate','routeType','originalDistance','originalUnit','routeDistance','segments','routeReviewed','vehicle','hotel','food','activities','guided','termFixed','termFuel','termVehicle','termHotel','termFood','termActivities'];
const ALLOWED=new Set([...setupKeys,...Object.keys(FIELD_GROUP)]),now=()=>new Date().toISOString(),id=()=>typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():'s-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
function newSession(alias=''){return {schema:'mcada-project-progress',schemaVersion:'1.0.0',projectId:'road-trip',appVersion:VERSION,contentVersion:CONTENT,sessionId:id(),scenarioId:'RT-BASE',teamAlias:alias,currentStage:1,maxStage:1,inputs:{vehicle:'standard',hotel:'standard',food:'full',activities:'full',planner:'A',routeMode:'provided',sourceTitle:'Harbor City–Lakeview classroom route',sourceLink:'',accessDate:'',routeType:'roundTrip',originalDistance:'900',originalUnit:'km',routeDistance:'900',segments:'',routeReviewed:'provided',yStep:'200',transferModeA:'digital',transferModeB:'digital',guided:'no'},attempts:[],checkpoints:{},teacherOverrides:[],completedAt:null,scenarioRevision:0,localRevision:0,updatedAt:now(),eventApplied:false,eventBaseline:null,eventEvidence:null,scenarioSnapshots:[],choiceHistory:[],reviews:[],support:[],imported:false,duplicateOf:null}}
function scenario(s){const x=s.inputs,selected={};for(const k of Object.keys(CAT)){selected[k]=CAT[k].find(a=>a[0]===x[k]);if(!selected[k])throw Error('Choose each itinerary option.')}const D=numeric(x.routeDistance||'900'),e=q(12),g=q('1.60'),F=q(200),p=3,d=7,B=q(1800);if(D.cmp(0)<=0)throw Error('Distance must be greater than zero.');const r=q(selected.vehicle[2]),h=q(selected.hotel[2]+(s.eventApplied?20:0)),f=q(selected.food[2]),a=q(selected.activities[2]);const liters=D.div(e),K=liters.mul(g).round(2),m=r.add(h).add(f.mul(p)).add(a),b=F.add(K).sub(h),cost=n=>m.mul(n).add(b),total=cost(d),reserve=B.sub(total),bound=B.sub(b).div(m);let max=null;for(let n=1;n<=14;n++)if(cost(n).cmp(B)<=0)max=n;return {D,e,g,F,p,d,B,r,h,f,a,liters,K,m,b,cost,total,reserve,bound,max,percent:total.div(B).mul(100).round(2),U:Object.values(selected).reduce((sum,row)=>sum+row[3],0),selected,reserveQuestion:reserve.cmp(0)<0||reserve.div(B).cmp(q('0.05'))>0}}
function context(s){const m=scenario(s);return {distance:m.D.str(),hotel:s.inputs.hotel,vehicle:s.inputs.vehicle,food:s.inputs.food,activities:s.inputs.activities,eventApplied:s.eventApplied,m:m.m.str(),b:m.b.str(),total:m.total.str(),budget:m.B.str(),U:m.U}}
function groupFor(key){return FIELD_GROUP[key]}
function definitions(s){const m=scenario(s),D={},num=(key,label,value,unit='',hint='Recheck the calculation using the given values.')=>D[key]={label,unit,kind:'numeric',expected:q(value),hint},sel=(key,label,value,hint='Choose the statement that matches the mathematics.')=>D[key]={label,unit:'',kind:'select',expected:value,hint},expr=(key,label,a,b)=>D[key]={label,kind:'expression',m:q(a),b:q(b),hint:'Check both the daily coefficient and the constant.'};
 for(const [k,v] of Object.entries(CLASS))sel(k,({classOne:'One-off expenses',classFuel:'Fuel for the fixed route',classVehicle:'Vehicle rental',classHotel:'Hotel',classFood:'Food per person',classActivities:'Group activities'})[k],v,k==='classFuel'?'The route stays fixed when the number of days changes. Fuel is once per route.':'Ask whether this happens once, every day, or every night.');
 num('liters','Fuel needed',m.liters,'L','Divide the total kilometers by kilometers per liter.');num('fuelCost','Fuel cost',m.K,'USD','Multiply the correct liters by $1.60/L; round only the fuel subtotal to cents.');num('partyFood','Food for the whole group each day',m.f.mul(3),'USD/day','Multiply the per-person price by three travelers.');num('nights','Nights in seven days',6,'','Seven days includes six overnight stays.');expr('hotelExpression','Hotel cost for d days',m.h,m.h.neg());expr('expression','Total cost C(d)',m.m,m.b);num('slope','Daily coefficient m',m.m,'USD/day');num('constant','Constant b',m.b,'USD','The hotel term h(d−1) subtracts h from the constant.');sel('slopeMeaning','Meaning of m','daily');sel('constantMeaning','Meaning of b','adjusted');sel('domain','Available travel days','whole');
 for(const d of [1,3,5,7]){num('table'+d,'Table: '+d+' days',m.cost(d),'USD');num('x'+d,'Point '+d+': days',d);num('y'+d,'Point '+d+': cost',m.cost(d),'USD')}sel('xAxis','Horizontal axis','days');sel('yAxis','Vertical axis','cost');D.yStep={label:'Cost-axis tick interval',kind:'oneOf',expected:['50','100','200','500','1000'],hint:'Choose a consistent cost-axis interval.'};num('budgetLine','Budget line height',m.B,'USD');sel('budgetShape','Budget line shape','horizontal');num('rise','Cost increase for one more day',m.m,'USD/day');
 D.inequality={label:'Budget inequality',kind:'inequality',hint:'The modeled cost must be less than or equal to the budget.'};num('bound','Exact continuous upper bound',m.bound,'','Use an exact fraction, or (budget − constant) ÷ daily coefficient.');sel('maxDays','Longest affordable whole-day trip',m.max===null?'none':String(m.max),'Use a whole number of days within 1–14.');num('costAtMax',m.max===null?'Cost of one day':m.max===14?'Cost of day 14':'Cost at your maximum whole days',m.cost(m.max||1),'USD');if(m.max!==null&&m.max<14)num('nextDayCost','Cost of the next whole day',m.cost(m.max+1),'USD');else D.nextDayCost={label:'Next-day check',kind:'notRequired'};
 num('total','Seven-day total',m.total,'USD');num('reserve','Budget left after seven days',m.reserve,'USD','Subtract trip cost from budget; an overspend gives a negative reserve.');num('percent','Budget spent, nearest 0.01%',m.percent,'%');sel('lodgingPriority','Preferred lodging included',s.inputs.hotel==='basic'?'no':'yes');sel('activityPriority','Full activity preference included',s.inputs.activities==='full'?'yes':'no');D.recommendation={label:'Your recommendation',kind:'oneOf',expected:['recommend','revise'],hint:'Choose a recommendation.'};D.evidenceType={label:'Number used as evidence',kind:'oneOf',expected:['total','reserve','percent'],hint:'Choose a verified quantity.'};num('evidenceValue','Your numerical evidence',({total:m.total,reserve:m.reserve,percent:m.percent})[s.inputs.evidenceType]||m.total,s.inputs.evidenceType==='percent'?'%':'USD');D.reason={label:'One sentence supporting your recommendation',kind:'text'};D.reserveStatement=m.reserveQuestion?{label:'Explain your reserve allocation or overspend revision',kind:'text'}:{label:'Reserve statement',kind:'notRequired'};
 num('deltaSlope','Change in m',20,'USD/day');num('deltaConstant','Change in b',-20,'USD');num('deltaTotal','Increase for the seven-day trip',120,'USD','Six nights × the $20 increase gives the trip increase.');sel('deltaReason','Why both coefficients change','nights');
 for(const a of ['A','B']){D['transferMode'+a]={label:'Learner '+a+' response mode',kind:'oneOf',expected:['digital','paper','oral'],hint:'Choose a response mode.'};expr('transferExpression'+a,'Learner '+a+' rule T(d)',a==='A'?160:145,a==='A'?240:310);num('transferTotal'+a,'Learner '+a+' trip total',a==='A'?880:1180,'USD');if(s.inputs['transferMode'+a]!=='digital'){D['transferExpression'+a].kind='notRequired';D['transferTotal'+a].kind='notRequired'}}return D;
}
function fingerprint(s,key){const m=scenario(s),x=s.inputs,g=groupFor(key);let v=[];if(g==='C01')v=[];else if(key==='liters')v=[m.D.str()];else if(key==='fuelCost')v=[m.D.str(),m.g.str()];else if(key==='partyFood')v=[m.f.str(),3];else if(key==='nights')v=[7];else if(key==='hotelExpression')v=[m.h.str()];else if(g==='C09')v=[key,x['transferMode'+key.slice(-1)]];else if(g==='C08')v=[s.eventBaseline?.revision??-1];else if(['xAxis','yAxis','yStep','budgetShape'].includes(key)||/^x[1357]$/.test(key))v=[];else if(key==='budgetLine')v=[m.B.str()];else if(['expression','slope','constant','slopeMeaning','constantMeaning','domain'].includes(key)||/^table|^y[1357]$|^rise$/.test(key))v=[m.m.str(),m.b.str()];else v=[m.m.str(),m.b.str(),m.B.str(),x.hotel,x.activities,key==='evidenceValue'?x.evidenceType:''];return JSON.stringify([CONTENT,key,...v])}
function evaluate(s,key,raw=s.inputs[key]||''){const d=definitions(s)[key];if(!d)return 'Unknown field.';try{if(d.kind==='notRequired')return null;if(!String(raw).trim())return 'Enter '+d.label.toLowerCase()+'.';if(d.kind==='text')return String(raw).trim().length<=280?null:'Use at most 280 characters.';if(d.kind==='select')return raw===d.expected?null:d.hint;if(d.kind==='oneOf')return d.expected.includes(raw)?null:d.hint;if(d.kind==='numeric')return numeric(raw,d.unit).eq(d.expected)?null:d.hint;if(d.kind==='expression')return equivalent(raw,d.m,d.b)?null:d.hint;if(d.kind==='inequality'){const m=scenario(s);return inequality(raw,m.m,m.b,m.B)?null:d.hint}}catch(e){return e.message}return 'Check this answer.'}
function rec(s,key){return s.checkpoints[groupFor(key)]?.fields?.[key]}
function state(s,key){const d=definitions(s)[key];if(d?.kind==='notRequired')return 'notRequired';const r=rec(s,key);if(!r)return 'unstarted';if(r.fingerprint!==fingerprint(s,key)||r.response!==(s.inputs[key]||''))return 'needsRecheck';return r.status}
function valid(s,key){return ['verified','overridden','notRequired'].includes(state(s,key))}
function groupOK(s,g){return groups[g].every(k=>valid(s,k))}
function check(s,keys){const errors=[];for(const key of keys){const def=definitions(s)[key];if(def.kind==='notRequired')continue;if(valid(s,key)&&state(s,key)==='verified')continue;const response=s.inputs[key]||'',error=evaluate(s,key,response),g=groupFor(key),fp=fingerprint(s,key);s.checkpoints[g]??={fields:{}};const old=rec(s,key),attempt={id:id(),key,checkpointId:'RT-'+g,scenarioRevision:s.scenarioRevision,response,passed:!error,timestamp:now(),fingerprint:fp};s.attempts.push(attempt);s.checkpoints[g].fields[key]={status:error?'inProgress':'verified',fingerprint:fp,response,firstAttemptId:old?.fingerprint===fp?old.firstAttemptId:attempt.id,finalAttemptId:attempt.id};if(error)errors.push({key,message:error})}return errors}
function setInput(s,key,value){if(!ALLOWED.has(key))throw Error('Unsupported field.');value=String(value);const old=s.inputs[key];if(old===value)return;if(s.eventApplied&&!s.eventEvidence&&['vehicle','hotel','food','activities','routeDistance','routeMode'].includes(key))throw Error('Record the hotel comparison before changing the route or choices.');let before;try{before=context(s)}catch{}s.inputs[key]=value;let after;try{after=context(s)}catch{}if(before&&after&&JSON.stringify(before)!==JSON.stringify(after)){s.scenarioRevision++;s.choiceHistory.push({key,from:old||'',to:value,at:now(),revision:s.scenarioRevision});s.scenarioSnapshots.push({revision:s.scenarioRevision,scenario:after,at:now()})}}
const baseKeys=[...groups.C01,...groups.C02,...groups.C03,...groups.C04,...groups.C05,...groups.C06,...groups.C07];
function applyEvent(s){if(s.eventApplied)return false;if(!baseKeys.every(k=>valid(s,k)))throw Error('Finish the original plan checks before opening the new quote.');s.eventBaseline={revision:s.scenarioRevision,scenario:context(s),inputs:clone(s.inputs),at:now()};s.eventApplied=true;s.scenarioId='RT-HOTEL';s.scenarioRevision++;s.scenarioSnapshots.push({revision:s.scenarioRevision,scenario:context(s),at:now()});return true}
function recordEvent(s){if(!s.eventApplied)throw Error('Open the new hotel quote first.');if(!baseKeys.concat(groups.C08).every(k=>valid(s,k)))throw Error('Recheck the changed mathematics before revising another choice.');s.eventEvidence={revision:s.scenarioRevision,scenario:context(s),inputs:clone(s.inputs),at:now()};return true}
function reviewStatus(s,key){const fp=fingerprint(s,key),r=[...s.reviews].reverse().find(r=>r.key===key&&r.fingerprint===fp&&r.response===(s.inputs[key]||''));return r?.status||'pending'}
function outcome(s){let keys=baseKeys.concat(groups.C08,groups.C09);if(!s.eventEvidence||!keys.every(k=>valid(s,k))||['A','B'].some(a=>s.inputs['transferMode'+a]!=='digital'&&!s.reviews.some(r=>r.key==='transferMode'+a&&r.response===s.inputs['transferMode'+a]&&r.reviewer?.trim())))return {code:'draft',title:'Draft — finish checks'};if(keys.some(k=>state(s,k)==='overridden'))return {code:'provisional',title:'Provisional — teacher review'};let m=scenario(s);if(m.total.cmp(m.B)>0||m.U<65)return {code:'revision',title:'Revision requested'};if(m.U<85)return {code:'approved',title:'Trip approved'};return {code:'delighted',title:'Client delighted'}}
function bypass(s,g,reviewer,reason){if(!groups[g]||!reviewer.trim()||!reason.trim())throw Error('Supply a reviewer alias and reason.');let keys=groups[g];s.checkpoints[g]??={fields:{}};for(const key of keys){if(valid(s,key))continue;s.checkpoints[g].fields[key]={status:'overridden',fingerprint:fingerprint(s,key),response:s.inputs[key]||'',firstAttemptId:rec(s,key)?.firstAttemptId||null,finalAttemptId:null}}s.teacherOverrides.push({checkpointId:'RT-'+g,reviewer,reason,at:now()})}
function routeErrors(s){const x=s.inputs,errs=[];try{let d=numeric(x.routeDistance);if(d.cmp(0)<=0)throw Error('Enter a distance greater than zero.');if(x.routeMode==='provided'){if(!d.eq(900))throw Error('The provided route is 900 km in total.')}else{for(const k of ['sourceTitle','accessDate','originalDistance'])if(!x[k]?.trim())errs.push({key:k,message:'Complete this source field.'});if(!/^\d{4}-\d{2}-\d{2}$/.test(x.accessDate||''))errs.push({key:'accessDate',message:'Record the access date.'});let source=numeric(x.originalDistance||'0');if(x.originalUnit==='m')source=source.div(1000);if(x.routeType==='oneWay')source=source.mul(2);if(x.routeType==='segmentTotal'){let parts=(x.segments||'').split('+').map(a=>numeric(a));source=parts.reduce((a,b)=>a.add(b),q(0));if(x.originalUnit==='m')source=source.div(1000)}if(!d.eq(source))errs.push({key:'routeDistance',message:'Convert the recorded source distance into the total return-trip kilometers.'});if((d.cmp(100)<0||d.cmp(2400)>0)&&x.routeReviewed!=='verified')errs.push({key:'routeDistance',message:'Ask the teacher to review this distance outside the classroom range.'})}}catch(e){errs.push({key:'routeDistance',message:e.message})}return errs}
function stageKeys(stage,s){if(stage===3)return [...groups.C01,...groups.C02,...groups.C03];if(stage===4)return groups.C04;if(stage===5)return groups.C05;if(stage===6)return [...groups.C06,...groups.C07];if(stage===7)return [...baseKeys,...groups.C08];if(stage===8)return groups.C09;return []}
function canStage(s,n){if(n<=3)return n<=s.maxStage;if(n===7&&s.eventApplied&&n<=s.maxStage)return true;const prereq=n===4?stageKeys(3,s):n===5?[...stageKeys(3,s),...groups.C04]:n===6?[...stageKeys(3,s),...groups.C04,...groups.C05]:baseKeys;return n<=s.maxStage&&prereq.every(k=>valid(s,k))&&(n<8||!!s.eventEvidence)}
const topKeys=Object.keys(newSession());
function validateSession(raw,imported=true){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('This is not a saved session.');if(Object.keys(raw).some(k=>!topKeys.includes(k)))throw Error('The save contains an unsupported field.');if(raw.schema!=='mcada-project-progress'||raw.projectId!=='road-trip')throw Error('This file belongs to a different project.');if(raw.appVersion!==VERSION||raw.schemaVersion!=='1.0.0'||raw.contentVersion!==CONTENT)throw Error('This save uses an unsupported or newer schema/content version.');if(typeof raw.sessionId!=='string'||!/^[\w-]{1,100}$/.test(raw.sessionId))throw Error('The saved session ID is invalid.');if(typeof raw.teamAlias!=='string'||raw.teamAlias.length>64)throw Error('Use an alias of at most 64 characters.');if(!Number.isInteger(raw.currentStage)||raw.currentStage<1||raw.currentStage>8||!Number.isInteger(raw.maxStage)||raw.maxStage<raw.currentStage||raw.maxStage>8)throw Error('The saved stage is invalid.');if(!raw.inputs||typeof raw.inputs!=='object'||Array.isArray(raw.inputs))throw Error('Missing input records.');for(const [k,v] of Object.entries(raw.inputs)){if(!ALLOWED.has(k)||typeof v!=='string'||v.length>(k==='sourceLink'?512:k==='reason'||k==='reserveStatement'?280:256))throw Error('Unsupported or oversized saved input: '+k)}for(const kind of Object.keys(CAT))if(!CAT[kind].some(x=>x[0]===raw.inputs[kind]))throw Error('Invalid saved itinerary choice.');if(!['provided','researched'].includes(raw.inputs.routeMode)||!['km','m'].includes(raw.inputs.originalUnit)||!['roundTrip','oneWay','segmentTotal'].includes(raw.inputs.routeType))throw Error('Invalid route/source format.');for(const k of ['scenarioRevision','localRevision'])if(!Number.isSafeInteger(raw[k])||raw[k]<0)throw Error('Invalid saved revision.');if(typeof raw.eventApplied!=='boolean')throw Error('Invalid event status.');
 for(const k of ['attempts','teacherOverrides','scenarioSnapshots','choiceHistory','reviews','support'])if(!Array.isArray(raw[k]))throw Error('Invalid saved history: '+k);
 if(!raw.checkpoints||typeof raw.checkpoints!=='object'||Array.isArray(raw.checkpoints))throw Error('Invalid checkpoint records.');for(const [g,c] of Object.entries(raw.checkpoints)){if(!groups[g]||!c.fields||Object.keys(c).some(k=>k!=='fields'))throw Error('Unknown checkpoint.');for(const [k,r] of Object.entries(c.fields)){if(!groups[g].includes(k)||!r||!['verified','inProgress','overridden','needsRecheck'].includes(r.status)||typeof r.fingerprint!=='string'||typeof r.response!=='string'||Object.keys(r).some(x=>!['status','fingerprint','response','firstAttemptId','finalAttemptId'].includes(x)))throw Error('Invalid field evidence.')}}
 function safeWalk(v,depth=0){if(depth>12)throw Error('The save is too deeply nested.');if(typeof v==='number'&&!Number.isFinite(v))throw Error('Nonfinite saved value.');if(typeof v==='string'&&v.length>2000)throw Error('Oversized saved text.');if(v&&typeof v==='object'){for(const k of Object.keys(v)){if(['__proto__','prototype','constructor'].includes(k))throw Error('Unsafe saved key.');safeWalk(v[k],depth+1)}}}safeWalk(raw);
 for(const a of raw.attempts)if(!ALLOWED.has(a.key)||typeof a.response!=='string'||typeof a.passed!=='boolean'||a.checkpointId!=='RT-'+groupFor(a.key))throw Error('Invalid attempt history.');for(const a of raw.reviews)if(!ALLOWED.has(a.key)||!['verified','pending','revise'].includes(a.status)||typeof a.reviewer!=='string')throw Error('Invalid review record.');for(const a of raw.teacherOverrides)if(!Object.keys(groups).some(g=>'RT-'+g===a.checkpointId)||typeof a.reason!=='string'||typeof a.reviewer!=='string')throw Error('Invalid teacher override.');
 if(raw.eventApplied!==!!raw.eventBaseline||raw.eventEvidence&&!raw.eventApplied)throw Error('Inconsistent event history.');for(const snap of [raw.eventBaseline,raw.eventEvidence].filter(Boolean)){if(!snap.inputs||!snap.scenario||!Number.isSafeInteger(snap.revision))throw Error('Invalid event snapshot.');const probe=clone(raw);probe.inputs=snap.inputs;probe.eventApplied=snap===raw.eventEvidence;if(JSON.stringify(context(probe))!==JSON.stringify(snap.scenario))throw Error('The event snapshot does not match its source values.');}if(raw.eventEvidence&&raw.eventBaseline){const b=raw.eventBaseline.scenario,e=raw.eventEvidence.scenario;if(['vehicle','hotel','food','activities','distance'].some(k=>b[k]!==e[k])||!numeric(e.total).sub(numeric(b.total)).eq(120))throw Error('The mandatory hotel comparison was altered.');}
 let s=clone(raw);scenario(s);for(const key of Object.keys(FIELD_GROUP)){const r=rec(s,key);if(r?.status==='verified'&&(r.fingerprint!==fingerprint(s,key)||r.response!==(s.inputs[key]||'')||evaluate(s,key)))r.status='needsRecheck'}s.imported=imported||raw.imported===true;return s;
}
function parseImport(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>20*1024*1024)throw Error('Import files must be at most 20 MiB.');let p;try{p=JSON.parse(text)}catch{throw Error('This file is not valid JSON.')}if(p.schema==='mcada-project-backup'){if(p.schemaVersion!=='1.0.0'||p.projectId!=='road-trip'||!Array.isArray(p.sessions)||p.sessions.length>100||!p.sessions.length||Object.keys(p).some(k=>!['schema','schemaVersion','projectId','exportedAt','sessions'].includes(k)))throw Error('Invalid Road Trip backup bundle.');if(new Set(p.sessions.map(s=>s.sessionId)).size!==p.sessions.length)throw Error('A bundle cannot repeat a session identity.');return p.sessions.map(s=>{if(new TextEncoder().encode(JSON.stringify(s)).length>2*1024*1024)throw Error('A session exceeds 2 MiB.');return validateSession(s)})}if(new TextEncoder().encode(text).length>2*1024*1024)throw Error('A single session must be at most 2 MiB.');return [validateSession(p)]}
class Store{
 constructor(storage){this.storage=storage;this.available=false;try{storage.setItem(PREFIX+'probe','1');if(storage.getItem(PREFIX+'probe')!=='1')throw Error('Storage check failed');storage.removeItem(PREFIX+'probe');this.available=true}catch{}}
 ids(){const a=[];if(!this.available)return a;for(let i=0;i<this.storage.length;i++){let k=this.storage.key(i);if(k?.startsWith(PREFIX+'session:'))a.push(k.slice((PREFIX+'session:').length))}return a}
 read(id){const t=this.storage.getItem(PREFIX+'session:'+id);if(t===null)return null;return validateSession(JSON.parse(t),false)}
 list(){return this.ids().map(id=>{try{return {id,session:this.read(id)}}catch(e){return {id,error:e.message}}})}
 saveMany(sessions){if(!this.available)throw Error('Device storage is unavailable. Export progress before leaving.');const keys=sessions.map(s=>PREFIX+'session:'+s.sessionId),indexKey=PREFIX+'index',all=[...keys,indexKey],old=new Map(all.map(k=>[k,this.storage.getItem(k)]));try{for(let i=0;i<sessions.length;i++)this.storage.setItem(keys[i],JSON.stringify(sessions[i]));this.storage.setItem(indexKey,JSON.stringify(this.ids()));}catch(e){let rollback=true;for(const [k,v]of old){try{if(v===null)this.storage.removeItem(k);else this.storage.setItem(k,v)}catch{rollback=false}}throw Error(rollback?'Could not save. Existing saved work was retained. Export your current work.':'Storage failed during rollback. Keep this page open and export; inspect saved sessions before continuing.')}return true}
 save(s){let prev;try{prev=this.read(s.sessionId)}catch{}if(prev&&prev.localRevision>s.localRevision)throw Error('CONFLICT');const old=s.localRevision,oldTime=s.updatedAt;s.localRevision++;s.updatedAt=now();try{this.saveMany([s])}catch(e){s.localRevision=old;s.updatedAt=oldTime;throw e}return true}
 remove(ids){let failed=[];for(const id of ids){try{this.storage.removeItem(PREFIX+'session:'+id);if(this.storage.getItem(PREFIX+'session:'+id)!==null)failed.push(id)}catch{failed.push(id)}}try{const remain=this.ids();if(remain.length)this.storage.setItem(PREFIX+'index',JSON.stringify(remain));else this.storage.removeItem(PREFIX+'index')}catch{failed.push('session index')}if(failed.length)throw Error('Deletion was incomplete. Records remaining: '+failed.join(', '));return true}
}
root.RTCore={VERSION,CONTENT,PREFIX,Q,q,linear,numeric,equivalent,inequality,CAT,stages,CLASS,groups,labels,ALLOWED,clone,now,id,newSession,scenario,context,definitions,fingerprint,evaluate,rec,state,valid,groupOK,check,setInput,baseKeys,applyEvent,recordEvent,reviewStatus,outcome,bypass,routeErrors,stageKeys,canStage,validateSession,parseImport,Store};
if(typeof module!=='undefined')module.exports=root.RTCore;
})(typeof globalThis!=='undefined'?globalThis:this);
