'use strict';
const projects={road:['Road Trip Planner','road-trip-planner/'],food:['Food Truck / Business Launch','food-truck-business-launch/'],park:['Theme Park Designer','theme-park-designer/'],scale:['Powers of Ten','powers-of-ten/']};
const dialog=document.querySelector('#share'),qr=document.querySelector('#qr'),status=document.querySelector('#status');
let opener=null;
function projectURL(path){const base=location.protocol==='file:'?'https://mcada-applied-math.netlify.app/':new URL('./',location.href);return new URL(path,base).href;}
for(const button of document.querySelectorAll('[data-project]'))button.addEventListener('click',()=>{opener=button;const [name,path]=projects[button.dataset.project],url=projectURL(path);document.querySelector('#share-title').textContent=name;const link=document.querySelector('#project-url');link.textContent=url;link.href=url;document.querySelector('#launch').href=url;status.textContent='';qr.replaceChildren();try{const code=qrcode(0,'M');code.addData(url);code.make();qr.innerHTML=code.createSvgTag({cellSize:8,margin:32,scalable:true});qr.setAttribute('aria-label','QR code opening '+name);}catch{status.textContent='The QR code could not load. Use the project link below.';}dialog.showModal();});
document.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('close',()=>{dialog.classList.remove('projecting');document.querySelector('#fullscreen').textContent='Full-screen QR';if(document.fullscreenElement===dialog)document.exitFullscreen().catch(()=>{});opener?.focus();});
document.querySelector('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.querySelector('#project-url').href);status.textContent='Link copied. Ready to share.';}catch{const selection=window.getSelection(),range=document.createRange();range.selectNodeContents(document.querySelector('#project-url'));selection.removeAllRanges();selection.addRange(range);status.textContent='Link selected. Press Ctrl+C / Command+C, or touch and hold the link to copy.';}});
document.querySelector('#fullscreen').addEventListener('click',async()=>{if(dialog.classList.contains('projecting')){dialog.classList.remove('projecting');if(document.fullscreenElement===dialog)await document.exitFullscreen().catch(()=>{});document.querySelector('#fullscreen').textContent='Full-screen QR';return;}dialog.classList.add('projecting');document.querySelector('#fullscreen').textContent='Exit full-screen';try{await dialog.requestFullscreen();}catch{status.textContent='Projection view is ready. Close the panel to return to projects.';}});
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement){dialog.classList.remove('projecting');document.querySelector('#fullscreen').textContent='Full-screen QR';}});
