/* Mars Colony — A WILLIAM MCADA PRODUCT. Exact parser adapted from the approved Food Truck source. */
(function(root){
'use strict';
const VERSION='0.1.0',CONTENT='1.0.0',PREFIX='mcada:mars-colony:',clone=x=>JSON.parse(JSON.stringify(x));
const gcd=(a,b)=>{a=a<0n?-a:a;b=b<0n?-b:b;while(b){[a,b]=[b,a%b]}return a||1n};
class Q{
 constructor(n,d=1n){n=BigInt(n);d=BigInt(d);if(!d)throw Error('The denominator cannot be zero.');if(d<0n){n=-n;d=-d}let g=gcd(n,d);this.n=n/g;this.d=d/g}
 add(b){b=q(b);return new Q(this.n*b.d+b.n*this.d,this.d*b.d)} sub(b){return this.add(q(b).neg())} mul(b){b=q(b);return new Q(this.n*b.n,this.d*b.d)} div(b){b=q(b);return new Q(this.n*b.d,this.d*b.n)} neg(){return new Q(-this.n,this.d)} eq(b){b=q(b);return this.n===b.n&&this.d===b.d} cmp(b){b=this.sub(b);return b.n<0n?-1:b.n>0n?1:0} num(){return Number(this.n)/Number(this.d)} str(){return this.d===1n?String(this.n):this.n+'/'+this.d} toJSON(){return this.str()}
 round(places=2){const scale=10n**BigInt(places),n=(this.n<0n?-this.n:this.n)*scale,c=(2n*n+this.d)/(2n*this.d);return new Q(this.n<0n?-c:c,scale)}
 fixed(places=2){const v=this.round(places),scale=10n**BigInt(places),i=v.n*scale/v.d,a=i<0n?-i:i;return (i<0n?'-':'')+(a/scale)+(places?'.'+String(a%scale).padStart(places,'0'):'')}
}
function q(v){if(v instanceof Q)return v;if(typeof v==='number'&&!Number.isFinite(v))throw Error('Use a finite number.');let s=String(v).trim();if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)||s.replace(/\D/g,'').length>12)throw Error('Use a decimal or a fraction such as 3/4.');let neg=s[0]==='-';s=s.replace(/^[+-]/,'');let [a,b='']=s.split('.');return new Q(BigInt((a||'0')+b)*(neg?-1n:1n),10n**BigInt(b.length))}
function clean(s){if(typeof s!=='string'||s.length>256)throw Error('Use an expression with at most 256 characters.');s=s.trim().replace(/[−–]/g,'-').replace(/[×·]/g,'*').replace(/÷/g,'/');if(s.includes(',')){s=s.replace(/\b\d[\d,]*(?:\.\d+)?/g,t=>{if(!t.includes(','))return t;if(!/^\d{1,3}(,\d{3})+(\.\d+)?$/.test(t))throw Error('Use a decimal point; commas only separate thousands.');return t.replace(/,/g,'')});}return s}
function linear(raw){if(String(raw).length>200)throw Error('Use at most 200 characters.');let s=clean(raw).replace(/\s/g,'');if(!s)throw Error('Enter your answer.');let ts=s.match(/(?:\d+(?:\.\d*)?|\.\d+)|t|[()+*/-]/g)||[];if(ts.join('')!==s)throw Error('Use numbers, t, parentheses, +, −, × and ÷ only.');if(ts.length>100)throw Error('Use at most 100 tokens.');let i=0,depth=0;const pair=(a,b)=>({m:q(a),b:q(b)}),add=(a,b)=>({m:a.m.add(b.m),b:a.b.add(b.b)}),neg=a=>({m:a.m.neg(),b:a.b.neg()});
 function mul(a,b){if(a.m.n&&b.m.n)throw Error('Use a linear rule; t × t is not linear.');return {m:a.m.mul(b.b).add(b.m.mul(a.b)),b:a.b.mul(b.b)}}
 function atom(){let t=ts[i++];if(t==='+'||t==='-'){let a=atom();return t==='-'?neg(a):a}if(t==='('){if(++depth>12)throw Error('Use fewer nested parentheses.');let a=expr();if(ts[i++]!==')')throw Error('Close each parenthesis.');depth--;return a}if(t==='t')return pair(1,0);if(t&&/^[\d.]/.test(t))return pair(0,q(t));throw Error('Check the numbers and operators in your expression.')}
 function term(){let a=atom();while(i<ts.length){let t=ts[i];if(t==='*'||t==='/'){i++;let b=atom();if(t==='/'){if(b.m.n)throw Error('Divide only by a constant number.');if(!b.b.n)throw Error('The denominator cannot be zero.');a={m:a.m.div(b.b),b:a.b.div(b.b)}}else a=mul(a,b)}else if(t==='t'||t==='('){a=mul(a,atom())}else break}return a}
 function expr(){let a=term();while(ts[i]==='+'||ts[i]==='-'){let t=ts[i++],b=term();a=add(a,t==='-'?neg(b):b)}return a}let ans=expr();if(i!==ts.length)throw Error('Check your parentheses and operators.');return ans;
}
function numeric(raw,unit=''){
 if(typeof raw!=='string'||raw.length>200)throw Error('Use at most 200 characters.');let s=clean(raw);
 if(unit){const suffix=unit.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');s=s.replace(new RegExp('\\s*'+suffix+'$','i'),'').trim();}
 const v=linear(s);if(v.m.n)throw Error('Enter a number, not a rule in t.');return v.b;
}
const now=()=>new Date().toISOString(),id=()=>typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():'s-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const names={water:'Water',oxygen:'Oxygen',food:'Food'},units={water:'L',oxygen:'kg',food:'kg'},caps={water:400,oxygen:100,food:200};
const catalog=[['o','Oxygen module','8 kg/day','12 kWh/day',200,2000,6],['w','Water module','30 L/day','8 kWh/day',150,1500,6],['h','Habitat','8 settlers · 24 m²','10 kWh/day',400,3000,6],['a','Solar array','36 kWh/day normally','27 kWh/day in storm',100,1000,8],['b','Battery','36 kWh usable storage','Starts full',80,800,4]];
const stages=['Arrival request','Demand console','Module bay','Supply manifest','Resource forecast','Storm briefing','Resilience test','Mission control'];
const labels={C01:'Demand over time',C02:'Stocks, rates and units',C03:'Whole modules',C04:'Habitat capacity',C05:'A resource model',C06:'Storm energy',C07:'Battery balance',C08:'Cargo and credits',C09:'Compare and recommend',C10:'Individual transfer'};
const help={
 C01:['Demand over time','A rate tells you how much is used per person each day.','Multiply by people, then by the number of days. Use L or kg for a total; add /day for daily demand.','Five people using 2 L each need 10 L/day and 40 L over four days.'],
 C02:['Stock or rate?','A stock is an amount now. A rate describes change per unit time.','Use the supplied 1 kg = 1,000 g and 1 L = 1,000 mL relationships.','2.5 kg is 2,500 g. A 50 L tank is stock; 6 L/day is a rate.'],
 C03:['Whole modules','Modules come in whole units. The demand/capacity ratio can be a decimal.','Divide demand by one module’s capacity. Round up for the minimum whole count, then check one fewer.','50 L/day ÷ 20 L/day = 2.5. Three modules supply 60; two supply only 40.'],
 C04:['Habitat capacity','Floor area is measured in square meters, not cubic meters.','Multiply each habitat’s area and occupancy by the number selected; divide total area by the people.','Two habitats of 30 m² provide 60 m². For 15 people that is 4 m²/person.'],
 C05:['Stock rule and graph','Initial stock is the intercept. Production minus use is the daily change.','Write initial + change × t. Apply the storage cap and show shortages separately. t counts completed Earth days.','A store starts at 40 L, receives 12 and uses 7 daily: R(t)=40+5t. At a 50 L cap it stops increasing after day 2.'],
 C06:['Reduced solar output','The storm removes part of the normal energy, not all of it.','Subtract the reduction from 100%, multiply normal output by the remaining fraction, then subtract the load.','A 20% loss from 50 kWh/day leaves 40. A load of 45 creates a −5 kWh/day balance.'],
 C07:['A finite battery','A battery stores kWh. It never creates a daily production rate.','Add one day’s signed balance to the previous stored energy. Cap it; record any unserved or curtailed energy.','A 20 kWh battery with 8 stored and a −10 daily balance ends at 0 with 2 kWh unserved.'],
 C08:['Two different limits','Cargo is mass in kg. The budget is money in credits.','Multiply each count by its cost and mass; add the pack once. Subtract totals from the two limits separately.','A 2,000 cr limit and 1,700 cr cost leave 300 cr. A 500 kg limit and 450 kg mass leave 50 kg.'],
 C09:['Compare strategies','Hold the resource modules and supply pack constant for a fair comparison.','Compute both strategies, choose a recommendation and cite a quantity. Your final plan can differ.','A design costing 200 more but weighing 20 less trades credits for cargo capacity. A daily model still omits hourly operation.'],
 C10:['Your own transfer','Each learner works on a new rate/capacity problem.','Find daily and ten-day demand, then divide by capacity and round upward when needed. Paper answers remain pending teacher review.','18 people using 2 L/day need 36 L/day. At 15 L/day per module, 2.4 means three whole modules.']
};
function model(cfg={o:3,w:3,h:3,a:4,b:1,pack:'standard'}){
 const {o,w,h,a,b}=cfg,lean=cfg.pack==='lean',food10=lean?1584:1728,packMass10=1440+384+food10+1000,packCost=lean?800:1000;
 const load=24+12*o+8*w+10*h,cost=2000*o+1500*w+3000*h+1000*a+800*b+packCost,mass10=2000*o+1500*w+4000*h+1000*a+800*b+packMass10;
 const resources={water:{initial:144,production:30*w,demand:72,cap:400},oxygen:{initial:38.4,production:8*o,demand:19.2,cap:100},food:{initial:food10/10,production:0,demand:14.4,cap:200}};
 const st={water:1440,oxygen:384,food:food10},prod={water:300*w,oxygen:80*o,food:0},dem={water:720,oxygen:192,food:144};let B=36*b;
 const days=[{day:0,battery:B,stocks:{water:144,oxygen:38.4,food:food10/10}}];
 for(let t=1;t<=10;t++){let r={day:t,storm:t>=4&&t<=6,resources:{},stocks:{}};for(const k of Object.keys(st)){let raw=st[k]+prod[k]-dem[k],unmet=Math.max(0,-raw),discarded=Math.max(0,raw-10*caps[k]);st[k]=Math.max(0,Math.min(10*caps[k],raw));r.resources[k]={raw:raw/10,unmet:unmet/10,discarded:discarded/10,stock:st[k]/10};r.stocks[k]=st[k]/10;}r.generation=(r.storm?27:36)*a;r.load=load;r.balance=r.generation-load;r.start=B;let raw=B+r.balance;r.unserved=Math.max(0,-raw);r.curtailed=Math.max(0,raw-36*b);B=Math.max(0,Math.min(36*b,raw));r.battery=B;days.push(r);}
 for(const [k,r]of Object.entries(resources)){r.net=(prod[k]-dem[k])/10;r.final=st[k]/10;r.reserve=q(st[k]).div(dem[k]);r.boundary=days.slice(1).find(d=>d.resources[k].raw<0||d.resources[k].raw>caps[k]||d.resources[k].stock===caps[k])?.day??null;}
 const criteria=[['Housing',8*h>=24&&24*h>=72,`${8*h} places; ${24*h} m²; ${h} m²/person`],['Water production',30*w>=72,`${30*w} of 72 L/day`],['Oxygen production',8*o>=19.2,`${8*o} of 19.2 kg/day`],['Food',food10>=1440,`${food10/10} kg loaded; 144 kg needed`],['Material stores',!days.slice(1).some(d=>Object.values(d.resources).some(x=>x.unmet>0)),'No unmet material demand; retained stores within caps'],['Daily energy',!days.slice(1).some(d=>d.unserved>0),days.slice(1).filter(d=>d.unserved>0).map(d=>`day ${d.day}: ${d.unserved} kWh unserved`).join('; ')||'Every modeled day covered'],['Budget',cost<=26000,`${cost.toLocaleString('en-US')} of 26,000 cr`],['Cargo',mass10<=34000,`${mass10/10} of 3,400 kg`]];
 const ready=criteria.every(x=>x[1]),resilient=ready&&Object.values(resources).every(r=>r.reserve.cmp(2)>=0),ending=ready?(resilient?'Resilient outpost':'Mission ready'):'Deployment delayed';
 return {cfg:clone(cfg),resources,days,load,cost,mass:mass10/10,packCost,packMass:packMass10/10,budgetReserve:26000-cost,cargoReserve:(34000-mass10)/10,normal:36*a,storm:27*a,batteryCap:36*b,criteria,ready,resilient,ending};
}
function newSession(){return {schema:'mcada-project-progress',schemaVersion:'1.0.0',projectId:'mars-colony',appVersion:VERSION,contentVersion:CONTENT,sessionId:id(),scenarioId:'MC-BASE',teamAlias:'',learnerA:'',learnerB:'',planner:'A',brief:false,currentStage:1,maxStage:1,cfg:{o:0,w:0,h:0,a:0,b:0,pack:'standard'},resource:'water',inputs:{transferModeA:'digital',transferModeB:'digital'},checkpoints:{},attempts:[],support:[],teacherOverrides:[],reviews:[],revisions:[],initialPlan:null,lessonSwaps:[],revision:0,localRevision:0,updatedAt:now(),completedAt:null,duplicateOf:null};}
const cache=new WeakMap();
function definitions(s){const signature=JSON.stringify([s.cfg,s.resource,s.inputs.transferModeA,s.inputs.transferModeB,s.inputs.metric]);const saved=cache.get(s);if(saved?.signature===signature)return saved.defs;const D={},m=model(s.cfg),r=m.resources[s.resource],u=units[s.resource];
 const num=(g,k,label,v,unit='',dep=null)=>D[k]={g,label,kind:'number',expected:q(v),unit,dep};
 const sel=(g,k,label,v,options,dep=null)=>D[k]={g,label,kind:'select',expected:v,options,dep};
 const choice=(g,k,label,options,dep=null)=>D[k]={g,label,kind:'choice',options,dep};
 const txt=(g,k,label,dep=null)=>D[k]={g,label,kind:'text',dep};
 const yn=[['yes','Meets the requirement'],['no','Does not meet the requirement']];
 for(const [k,v]of Object.entries({water:72,oxygen:19.2,food:14.4})){num('C01','daily_'+k,names[k]+' per day',v,units[k]+'/day');num('C01','total_'+k,names[k]+' over 10 days',q(v).mul(10),units[k]);}
 for(const [k,v]of [['L','stock'],['L/day','rate'],['kg','stock'],['kg/day','rate'],['kWh','stock'],['kWh/day','rate']])sel('C02','unit_'+k.replace('/','_'),k,v,[['stock','Stock — amount'],['rate','Rate — amount per day']]);
 num('C02','convert_oxygen','0.8 kg in grams',800,'g');num('C02','convert_water','3 L in milliliters',3000,'mL');num('C02','convert_group','19,200 g in kilograms',19.2,'kg');
 for(const [k,d,c,unit]of [['water',72,30,'L/day'],['oxygen',19.2,8,'kg/day']]){num('C03','ratio_'+k,names[k]+': demand ÷ capacity',q(d).div(c));num('C03','min_'+k,names[k]+': minimum whole modules',3,'modules');num('C03','enough_'+k,names[k]+': capacity of 3 modules',3*c,unit);num('C03','fewer_'+k,names[k]+': capacity of 2 modules',2*c,unit);sel('C03','why_'+k,'Why round upward for '+k+'?','capacity',[['capacity','Two do not meet demand; three do'],['nearest','Always round to the nearest whole number']]);}
 num('C04','min_h','Minimum habitats',3,'habitats');for(const [k,label,v,unit]of [['places','Selected occupancy capacity',8*s.cfg.h,'settlers'],['area','Selected floor area',24*s.cfg.h,'m²'],['perPerson','Floor area per settler',s.cfg.h,'m²/person']])num('C04',k,label,v,unit,{h:s.cfg.h});sel('C04','occupancyMet','Occupancy',s.cfg.h>=3?'yes':'no',yn,{h:s.cfg.h});sel('C04','areaMet','Floor area',s.cfg.h>=3?'yes':'no',yn,{h:s.cfg.h});
 const rd={resource:s.resource,initial:r.initial,production:r.production,demand:r.demand,cap:r.cap};
 for(const [k,label,v,unit]of [['initial','Initial stock',r.initial,u],['production','Daily production',r.production,u+'/day'],['consumption','Daily consumption',r.demand,u+'/day'],['net','Net daily change',r.net,u+'/day']])num('C05','stock_'+k,label,v,unit,rd);
 D.stock_rule={g:'C05',label:'Unrestricted stock rule R(t)',kind:'expression',m:q(r.net),b:q(r.initial),unit:u,dep:rd};
 sel('C05','stock_meaning','The rule describes actual stock…','until',[['until','Until a storage boundary is reached'],['always','At all times, even beyond a capacity']],rd);
 sel('C05','boundary','First boundary or shortage day',String(r.boundary??'none'),[['none','None during this mission'],...Array.from({length:10},(_,i)=>[String(i+1),'Day '+(i+1)])],rd);
 for(let t=0;t<=10;t++){num('C05','stock_day'+t,'Day '+t+' retained stock',m.days[t].stocks[s.resource],u,rd);if(t){num('C05','unmet_day'+t,'Day '+t+' unmet demand',m.days[t].resources[s.resource].unmet,u,rd);num('C05','discarded_day'+t,'Day '+t+' discarded surplus',m.days[t].resources[s.resource].discarded,u,rd);}}
 sel('C05','axisX','Horizontal axis','days',[['days','Completed Earth days'],['rate','Production per day']],rd);sel('C05','axisY','Vertical axis',s.resource,[...Object.keys(names).map(k=>[k,names[k]+' stock ('+units[k]+')']),['rate','Daily production (amount/day)']],rd);
 for(const t of [0,1,3,6,10]){num('C05','pointX'+t,'Day '+t+': horizontal',t,'days',rd);num('C05','pointY'+t,'Day '+t+': vertical',m.days[t].stocks[s.resource],u,rd);}
 num('C05','boundaryX','Boundary: horizontal',r.boundary??0,'days',rd);num('C05','boundaryY','Boundary: vertical',m.days[r.boundary??0].stocks[s.resource],u,rd);if(r.boundary===null||[0,1,3,6,10].includes(r.boundary)){D.boundaryX.active=false;D.boundaryY.active=false;}
 const energy={o:s.cfg.o,w:s.cfg.w,h:s.cfg.h,a:s.cfg.a};
 for(const [k,label,v,dep]of [['fixed','Other fixed load',24,{}],['oxygen','Oxygen module load',12*s.cfg.o,{o:s.cfg.o}],['water','Water module load',8*s.cfg.w,{w:s.cfg.w}],['habitat','Habitat load',10*s.cfg.h,{h:s.cfg.h}],['total','Total load',m.load,{o:s.cfg.o,w:s.cfg.w,h:s.cfg.h}],['normal','Normal total generation',m.normal,{a:s.cfg.a}],['storm','Storm total generation',m.storm,{a:s.cfg.a}],['normalBalance','Normal signed balance',m.normal-m.load,energy],['stormBalance','Storm signed balance',m.storm-m.load,energy]])num('C06','energy_'+k,label,v,'kWh/day',dep);
 num('C06','remaining','Percentage remaining',75,'%');num('C06','perArray','Storm yield per array',27,'kWh/day');
 const ed={...energy,b:s.cfg.b};num('C07','batteryCap','Total battery capacity',m.batteryCap,'kWh',{b:s.cfg.b});num('C07','batteryInitial','Initial stored energy',m.batteryCap,'kWh',{b:s.cfg.b});num('C07','stormDeficit','Three-day storm deficit before battery use',3*Math.max(0,m.load-m.storm),'kWh',energy);
 for(let t=1;t<=10;t++)for(const [k,label,unit]of [['start','Starting energy','kWh'],['battery','Ending energy','kWh'],['unserved','Unserved energy','kWh'],['curtailed','Curtailed energy','kWh']])num('C07',k+'_day'+t,'Day '+t+': '+label,m.days[t][k],unit,ed);
 sel('C07','allCovered','Every modeled day covered?',m.criteria[5][1]?'yes':'no',yn,ed);
 for(const [k,label,cap,usage,mass,cost]of catalog){num('C08','mass_'+k,label+' cargo',mass*s.cfg[k],'kg',{[k]:s.cfg[k]});num('C08','cost_'+k,label+' cost',cost*s.cfg[k],'cr',{[k]:s.cfg[k]});}
 num('C08','packMass','Supply pack cargo',m.packMass,'kg',{pack:s.cfg.pack});num('C08','packCost','Supply pack cost',m.packCost,'cr',{pack:s.cfg.pack});
 for(const [k,label,v,unit]of [['totalMass','Total cargo',m.mass,'kg'],['totalCost','Total cost',m.cost,'cr'],['cargoReserve','Cargo reserve',m.cargoReserve,'kg'],['budgetReserve','Budget reserve',m.budgetReserve,'cr']])num('C08',k,label,v,unit,s.cfg);
 sel('C08','cargoMet','Cargo cap',m.mass<=3400?'yes':'no',yn,s.cfg);sel('C08','budgetMet','Budget cap',m.cost<=26000?'yes':'no',yn,s.cfg);
 const A=model({o:3,w:3,h:3,a:4,b:1,pack:s.cfg.pack}),B=model({o:3,w:3,h:3,a:5,b:0,pack:s.cfg.pack});
 for(const [name,p]of [['A',A],['B',B]])for(const [k,label,v,unit]of [['normal','Normal output',p.normal,'kWh/day'],['storm','Storm output',p.storm,'kWh/day'],['load','Daily load',p.load,'kWh/day'],['battery','Battery at end of day 6',p.days[6].battery,'kWh'],['cost','Cost',p.cost,'cr'],['mass','Cargo',p.mass,'kg'],['food','Final food reserve',p.resources.food.reserve,'days']])num('C09','compare'+name+'_'+k,'Strategy '+name+': '+label,v,unit,{pack:s.cfg.pack});
 num('C09','compareCost','B − A cost',200,'cr');num('C09','compareMass','B − A cargo',20,'kg');
 choice('C09','recommend','Recommended strategy',[['A','A · four arrays + one battery'],['B','B · five arrays + no battery'],['own','My own configuration']],s.cfg);
 choice('C09','metric','Numerical evidence to cite',[['cost','Extra cost of B over A'],['mass','Extra cargo of B over A'],['energy','Battery energy left in A after storm'],['food','Food days in either strategy']],{pack:s.cfg.pack});
 const metric={cost:[200,'cr'],mass:[20,'kg'],energy:[18,'kWh'],food:[A.resources.food.reserve,'days']}[s.inputs.metric]||[200,'cr'];num('C09','evidenceValue','Value supporting comparison',metric[0],metric[1],{metric:s.inputs.metric,pack:s.cfg.pack});
 txt('C09','reason','One benefit or tradeoff behind your recommendation',s.cfg);txt('C09','limitation','One limitation of this daily classroom model');txt('C09','revisionReason','Why did you retain or revise your own plan?',s.cfg);
 for(const who of ['A','B']){choice('C10','transferMode'+who,'Learner '+who+' response mode',[['digital','On this device'],['paper','Paper — teacher review']]);const vals=who==='A'?[90,900,3,3]:[22.4,224,2.8,3],unit=who==='A'?'L':'kg';for(const [i,k]of ['daily','total','ratio','count'].entries()){num('C10','transfer'+who+'_'+k,'Learner '+who+': '+['daily demand','ten-day demand','demand/capacity ratio','minimum whole modules'][i],vals[i],[unit+'/day',unit,'','modules'][i]);if(s.inputs['transferMode'+who]==='paper')D['transfer'+who+'_'+k].active=false;}txt('C10','transfer'+who+'_reason','Learner '+who+': explain why this count is enough');if(s.inputs['transferMode'+who]==='paper')D['transfer'+who+'_reason'].active=false;}
 for(const [key,d]of Object.entries(D)){d.key=key;d.id=d.g+'.'+key;d.objective='MC-'+d.g.slice(1);d.help=help[d.g];d.active=d.active!==false;d.dep=clone(d.dep||{});d.prompt=d.label;d.sourceIds=({C01:['MC-D01','MC-D02'],C02:['MC-D02','MC-D07'],C03:['MC-D02','MC-EQ-O','MC-EQ-W'],C04:['MC-D01','MC-D03','MC-EQ-H'],C05:['MC-D02','MC-D06','MC-PACK','MC-EQ'],C06:['MC-D04','MC-D05','MC-EQ'],C07:['MC-D05','MC-EQ-B'],C08:['MC-D01','MC-EQ','MC-PACK'],C09:['MC-D01','MC-EQ','MC-PACK'],C10:['MC-TRANSFER']})[d.g];d.representation=d.kind==='expression'?'linear rule':key.startsWith('point')?'ordered pair':key.includes('_day')?'daily ledger':d.kind;d.precisionPolicy='exact; no hidden rounding';d.acceptedForms=d.kind==='number'?'equivalent exact decimal/fraction':d.kind==='expression'?'equivalent linear expression in t':'declared response';d.evaluatorId=d.kind;d.prerequisiteFieldIds=Object.keys(d.dep).map(k=>'context.'+k);d.teacherReviewPolicy=d.kind==='text'?'required semantic review':'automatic mathematical check';}
 cache.set(s,{signature,defs:D});return D;
}
function fingerprint(s,k){const d=definitions(s)[k];return JSON.stringify({content:CONTENT,kind:d.kind,expected:d.expected,m:d.m,b:d.b,unit:d.unit,dep:d.dep,active:d.active});}
function evaluate(s,key,value){const d=definitions(s)[key];try{if(!d)throw Error('Unknown answer field.');if(!d.active)return null;if(typeof value!=='string'||!value.trim())throw Error('Enter or select a response.');if(d.kind==='number'){if(!numeric(value,d.unit).eq(d.expected))throw Error('Recheck '+d.label.toLowerCase()+'. Use the supplied values and units.');}else if(d.kind==='expression'){let a=linear(value.replace(/^\s*[WOF R]\(t\)\s*=\s*/i,''));if(!a.m.eq(d.m)||!a.b.eq(d.b))throw Error('Check both the initial stock and net daily change.');}else if(d.kind==='select'){if(value!==d.expected)throw Error('Choose the statement that agrees with the quantity or calculation.');}else if(d.kind==='choice'){if(!d.options.some(o=>o[0]===value))throw Error('Select one available option.');}else if(d.kind==='text'){if(value.trim().length<3||value.length>1000)throw Error('Give a brief response, or ask the teacher to record it.');}return null;}catch(e){return e.message;}}
const keys=(s,g)=>Object.keys(definitions(s)).filter(k=>definitions(s)[k].g===g&&definitions(s)[k].active);
function fieldState(s,k){const d=definitions(s)[k];if(!d?.active)return 'notRequired';const r=s.checkpoints[k];if(!r)return 'unstarted';if(r.fingerprint!==fingerprint(s,k)||r.response!==(s.inputs[k]||''))return 'needsRecheck';return r.status;}
const valid=(s,k)=>['verified','overridden','notRequired'].includes(fieldState(s,k)),groupOK=(s,g)=>keys(s,g).every(k=>valid(s,k));
function check(s,g){const errs=[],D=definitions(s),todo=keys(s,g).filter(k=>!['verified','overridden'].includes(fieldState(s,k)));if(s.attempts.length+todo.length>10000)throw Error('Attempt limit reached. Export this session, then duplicate for revision with a fresh attempt log.');for(const k of todo){const raw=s.inputs[k]||'',error=evaluate(s,k,raw),fp=fingerprint(s,k),a={id:id(),key:k,checkpoint:g,response:raw,passed:!error,timestamp:now(),fingerprint:fp,context:{cfg:clone(s.cfg),resource:s.resource,revision:s.revision}};s.attempts.push(a);const old=s.checkpoints[k];s.checkpoints[k]={status:error?'inProgress':'verified',response:raw,fingerprint:fp,firstAttemptId:old?.fingerprint===fp?old.firstAttemptId:a.id,lastAttemptId:a.id};if(error)errs.push({key:k,message:error});}return errs;}
function setRaw(s,k,value){const d=definitions(s)[k];if(!d||typeof value!=='string'||value.length>(d.kind==='text'?1000:200))throw Error('Unknown field or answer too long.');s.inputs[k]=value;s.completedAt=null;}
function setConfig(s,k,v){const limits={o:6,w:6,h:6,a:8,b:4};if(k==='pack'){if(!['standard','lean'].includes(v))throw Error('Choose one supply pack.');}else if(!(k in limits)||!Number.isInteger(Number(v))||Number(v)<0||Number(v)>limits[k])throw Error('Choose a supported whole equipment count.');else v=Number(v);if(s.cfg[k]===v)return;s.revisions.push({at:now(),before:clone(s.cfg),key:k,value:v});s.cfg[k]=v;s.revision++;s.completedAt=null;}
const stageGroups=n=>({2:['C01','C02'],3:['C03','C04'],4:['C08'],5:['C05'],6:['C06'],7:['C07','C09'],8:['C10']})[n]||[];
const pairGroups=['C01','C02','C03','C04','C05','C06','C07','C08','C09'];
function outcome(s){const m=model(s.cfg),missing=pairGroups.filter(g=>!groupOK(s,g));if(missing.length)return {title:'Draft — finish checks',code:'draft',missing,model:m};if(Object.keys(definitions(s)).some(k=>fieldState(s,k)==='overridden'))return {title:'Provisional — teacher review',code:'provisional',missing:[],model:m};return {title:m.ending,code:m.ready?(m.resilient?'resilient':'ready'):'delayed',missing:[],model:m};}
function duplicate(s,fresh=false){const c=clone(s);c.sessionId=id();c.localRevision=0;c.duplicateOf=s.sessionId;c.teamAlias=(s.teamAlias+' copy').slice(0,40);c.updatedAt=now();if(fresh){c.attempts=[];c.checkpoints={};c.teacherOverrides=[];c.reviews=[];c.support=[];c.currentStage=2;c.completedAt=null;}return c;}
function bypass(s,g,reviewer,reason){if(!labels[g]||!reviewer.trim()||!reason.trim()||reviewer.length>40||reason.length>1000)throw Error('Enter teacher alias and a reason.');const oid=id();s.teacherOverrides.push({id:oid,group:g,reviewer,reason,at:now()});for(const k of keys(s,g))if(!valid(s,k))s.checkpoints[k]={status:'overridden',response:s.inputs[k]||'',fingerprint:fingerprint(s,k),firstAttemptId:null,lastAttemptId:null,overrideId:oid};}
function review(s,key,reviewer,note,status){if(!['reason','limitation','revisionReason','transferA_reason','transferB_reason','transferModeA','transferModeB'].includes(key)||!reviewer.trim()||!note.trim()||!['pending','verified','revise'].includes(status))throw Error('Choose a review field and enter teacher alias and notes.');s.reviews.push({key,reviewer:reviewer.slice(0,40),note:note.slice(0,1000),status,response:s.inputs[key]||'',fingerprint:fingerprint(s,key),at:now()});}
function reviewStatus(s,k){return [...s.reviews].reverse().find(r=>r.key===k&&r.response===(s.inputs[k]||'')&&r.fingerprint===fingerprint(s,k))?.status||'pending';}
function validateSession(raw){const fail=t=>{throw Error(t)},obj=x=>x&&typeof x==='object'&&!Array.isArray(x),str=(x,n)=>typeof x==='string'&&x.length<=n,allowed=(x,ks)=>obj(x)&&Object.keys(x).every(k=>ks.includes(k));
 if(!allowed(raw,Object.keys(newSession())))fail('Unknown or malformed save fields.');if(raw.schema!=='mcada-project-progress'||raw.projectId!=='mars-colony')fail('This is not Mars Colony progress.');if(raw.schemaVersion!=='1.0.0'||raw.contentVersion!==CONTENT||!/^0\.1\.\d+$/.test(raw.appVersion))fail('Unsupported save schema, content or app family. Export a backup and use a compatible release.');
 if(!str(raw.sessionId,100)||!/^[-\w]+$/.test(raw.sessionId)||!str(raw.teamAlias,40)||!str(raw.learnerA,40)||!str(raw.learnerB,40)||!['A','B'].includes(raw.planner)||typeof raw.brief!=='boolean'||raw.scenarioId!=='MC-BASE')fail('Invalid mission identity.');
 if(!Number.isInteger(raw.currentStage)||raw.currentStage<1||raw.currentStage>8||!Number.isInteger(raw.maxStage)||raw.maxStage<raw.currentStage||raw.maxStage>8||!Number.isSafeInteger(raw.revision)||raw.revision<0||!Number.isSafeInteger(raw.localRevision)||raw.localRevision<0||!str(raw.updatedAt,40))fail('Invalid stage or revision.');
 function cfg(c){if(!allowed(c,['o','w','h','a','b','pack'])||Object.keys(c).length!==6||!['standard','lean'].includes(c.pack))fail('Invalid equipment plan.');for(const [k,max]of Object.entries({o:6,w:6,h:6,a:8,b:4}))if(!Number.isInteger(c[k])||c[k]<0||c[k]>max)fail('Equipment count outside the catalog.');}
 cfg(raw.cfg);if(!Object.keys(names).includes(raw.resource))fail('Unknown graph resource.');
 for(const k of ['attempts','support','teacherOverrides','reviews','revisions','lessonSwaps'])if(!Array.isArray(raw[k])||raw[k].length>10000)fail('Invalid or oversized '+k+'.');
 function walk(v,depth=0){if(depth>18)fail('Save nesting too deep.');if(typeof v==='number'&&!Number.isFinite(v))fail('Nonfinite value.');if(typeof v==='string'&&(v.length>2000||/<\/?\s*(script|iframe|object|svg|img)\b/i.test(v)))fail('Unsafe or oversized saved text.');if(v&&typeof v==='object')for(const k of Object.keys(v)){if(['__proto__','constructor','prototype'].includes(k))fail('Unsafe key.');walk(v[k],depth+1);}}walk(raw);
 if(!obj(raw.inputs)||!obj(raw.checkpoints))fail('Missing answer records.');const s=clone(raw),D=definitions(s);
 for(const [k,v]of Object.entries(s.inputs))if(!D[k]||!str(v,D[k].kind==='text'?1000:200))fail('Unknown or invalid response: '+k);
 const ids=new Set();for(const a of s.attempts){if(!allowed(a,['id','key','checkpoint','response','passed','timestamp','fingerprint','context'])||!D[a.key]||a.checkpoint!==D[a.key].g||!str(a.id,100)||ids.has(a.id)||!str(a.response,1000)||typeof a.passed!=='boolean'||!str(a.timestamp,40)||!str(a.fingerprint,2000)||!allowed(a.context,['cfg','resource','revision']))fail('Malformed attempt history.');ids.add(a.id);cfg(a.context.cfg);if(!names[a.context.resource]||!Number.isInteger(a.context.revision)||a.context.revision<0)fail('Invalid attempt context.');}
 for(const r of s.teacherOverrides)if(!allowed(r,['id','group','reviewer','reason','at'])||!labels[r.group]||!str(r.id,100)||!str(r.reviewer,40)||!r.reviewer.trim()||!str(r.reason,1000)||!r.reason.trim())fail('Invalid teacher override.');
 for(const [k,r]of Object.entries(s.checkpoints)){if(!D[k]||!allowed(r,['status','response','fingerprint','firstAttemptId','lastAttemptId','overrideId'])||!['verified','inProgress','overridden','needsRecheck'].includes(r.status)||!str(r.response,1000)||!str(r.fingerprint,2000))fail('Malformed checkpoint.');if(r.status==='overridden'&&!s.teacherOverrides.some(o=>o.id===r.overrideId&&o.group===D[k].g))fail('Missing teacher override record.');if(r.status==='verified'&&(r.fingerprint!==fingerprint(s,k)||r.response!==(s.inputs[k]||'')||evaluate(s,k,r.response)||!s.attempts.some(a=>a.id===r.lastAttemptId&&a.key===k&&a.passed&&a.response===r.response&&a.fingerprint===r.fingerprint)))r.status='needsRecheck';}
 for(const r of s.reviews)if(!allowed(r,['key','reviewer','note','status','response','fingerprint','at'])||!D[r.key]||!str(r.reviewer,40)||!str(r.note,1000)||!['pending','verified','revise'].includes(r.status)||!str(r.response,1000)||!str(r.fingerprint,2000))fail('Invalid review record.');
 for(const r of s.support)if(!allowed(r,['group','at'])||!labels[r.group]||!str(r.at,40))fail('Invalid help history.');
 for(const r of s.revisions){if(!allowed(r,['at','before','key','value'])||!str(r.at,40)||!['o','w','h','a','b','pack'].includes(r.key))fail('Invalid revision history.');cfg(r.before);cfg({...r.before,[r.key]:r.value});}
 if(s.lessonSwaps.some(x=>![1,2].includes(x))||new Set(s.lessonSwaps).size!==s.lessonSwaps.length)fail('Invalid role swaps.');if(s.initialPlan!==null){if(!allowed(s.initialPlan,['cfg','at','resource'])||!str(s.initialPlan.at,40)||!names[s.initialPlan.resource])fail('Invalid first-plan snapshot.');cfg(s.initialPlan.cfg);}
 if(s.completedAt!==null&&!str(s.completedAt,40))fail('Invalid completion date.');if(s.duplicateOf!==null&&!str(s.duplicateOf,100))fail('Invalid duplicate reference.');return s;
}
function parseImport(text){if(typeof text!=='string'||new TextEncoder().encode(text).length>5*1024*1024)throw Error('Use a JSON file no larger than 5 MiB.');let v;try{v=JSON.parse(text);}catch{throw Error('This file is not valid JSON.');}if(v?.schema==='mcada-project-progress-bundle'){if(v.projectId!=='mars-colony'||v.schemaVersion!=='1.0.0'||Object.keys(v).some(k=>!['schema','schemaVersion','projectId','sessions','exportedAt'].includes(k))||!Array.isArray(v.sessions)||!v.sessions.length||v.sessions.length>25)throw Error('Invalid Mars backup bundle.');if(new Set(v.sessions.map(s=>s.sessionId)).size!==v.sessions.length)throw Error('Duplicate session IDs in backup.');return v.sessions.map(validateSession);}return [validateSession(v)];}
function bundle(sessions){if(!sessions.length||sessions.length>25)throw Error('Export between 1 and 25 sessions per backup.');return {schema:'mcada-project-progress-bundle',schemaVersion:'1.0.0',projectId:'mars-colony',sessions,exportedAt:now()};}
class Store{
 constructor(storage){this.storage=storage;this.available=false;try{storage.setItem(PREFIX+'probe','1');if(storage.getItem(PREFIX+'probe')!=='1')throw Error('Storage check failed');storage.removeItem(PREFIX+'probe');this.available=true}catch{}}
 ids(){const a=[];if(!this.available)return a;for(let i=0;i<this.storage.length;i++){let k=this.storage.key(i);if(k?.startsWith(PREFIX+'session:'))a.push(k.slice((PREFIX+'session:').length))}return a}
 read(id){const t=this.storage.getItem(PREFIX+'session:'+id);if(t===null)return null;return validateSession(JSON.parse(t),false)}
 list(){return this.ids().map(id=>{try{return {id,session:this.read(id)}}catch(e){return {id,error:e.message}}})}
 saveMany(sessions){if(!this.available)throw Error('Device storage is unavailable. Export progress before leaving.');const keys=sessions.map(s=>PREFIX+'session:'+s.sessionId),indexKey=PREFIX+'index',all=[...keys,indexKey],old=new Map(all.map(k=>[k,this.storage.getItem(k)]));try{for(let i=0;i<sessions.length;i++)this.storage.setItem(keys[i],JSON.stringify(sessions[i]));this.storage.setItem(indexKey,JSON.stringify(this.ids()));}catch(e){let rollback=true;for(const [k,v]of old){try{if(v===null)this.storage.removeItem(k);else this.storage.setItem(k,v)}catch{rollback=false}}throw Error(rollback?'Could not save. Existing saved work was retained. Export your current work.':'Storage failed during rollback. Keep this page open and export; inspect saved sessions before continuing.')}return true}
 save(s){let prev;try{prev=this.read(s.sessionId)}catch{}if(prev&&prev.localRevision>s.localRevision)throw Error('CONFLICT');const old=s.localRevision,oldTime=s.updatedAt;s.localRevision++;s.updatedAt=now();try{this.saveMany([s])}catch(e){s.localRevision=old;s.updatedAt=oldTime;throw e}return true}
 remove(ids){let failed=[];for(const id of ids){try{this.storage.removeItem(PREFIX+'session:'+id);if(this.storage.getItem(PREFIX+'session:'+id)!==null)failed.push(id)}catch{failed.push(id)}}try{const remain=this.ids();if(remain.length)this.storage.setItem(PREFIX+'index',JSON.stringify(remain));else this.storage.removeItem(PREFIX+'index')}catch{failed.push('session index')}if(failed.length)throw Error('Deletion was incomplete. Records remaining: '+failed.join(', '));return true}
}

function diagnostics(){return [['Demand',model().resources.water.demand===72],['Baseline cargo',model().mass===3185.2],['Storm energy',model().days[6].battery===18],['Extra solar',model({o:3,w:3,h:3,a:5,b:0,pack:'standard'}).ready],['Lean reserves',model({o:3,w:3,h:3,a:4,b:1,pack:'lean'}).ending==='Mission ready'],['Equivalent model',linear('18t+144').b.eq(144)]].map(([name,passed])=>({name,passed}));}
root.MC={VERSION,CONTENT,PREFIX,Q,q,linear,numeric,now,id,clone,names,units,caps,catalog,stages,labels,help,model,newSession,definitions,fingerprint,evaluate,keys,fieldState,valid,groupOK,check,setRaw,setConfig,stageGroups,pairGroups,outcome,duplicate,bypass,review,reviewStatus,validateSession,parseImport,bundle,Store,diagnostics};
if(typeof module!=='undefined')module.exports=root.MC;
})(typeof globalThis!=='undefined'?globalThis:this);
