'use strict';
const MC=(()=>{
const VERSION='0.1.0', KEYS=['water','oxygen','habitat','solar','battery'], BASE={water:3,oxygen:3,habitat:3,solar:4,battery:1,crate:'standard'}, EQUIP={water:[30,8,150,1500],oxygen:[8,12,200,2000],habitat:[24,10,400,3000],solar:[36,0,100,1000],battery:[36,0,80,800]};
const round=x=>Math.round(x*1e8)/1e8;
function number(v){if(typeof v!=='string'&&typeof v!=='number')return NaN;let t=String(v).trim().replace(/−/g,'-');if(!t||t.length>60)return NaN;let a=t.split('/');if(a.length>2)return NaN;const parse=s=>{s=s.trim();if(!/^[+-]?(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?$/.test(s))return NaN;return Number(s.replace(/,/g,''))};let n=parse(a[0]);if(a.length===2){let d=parse(a[1]);if(!d)return NaN;n/=d}return Number.isFinite(n)?n:NaN}
function validPlan(p){return p&&KEYS.every(k=>Number.isInteger(p[k])&&p[k]>=0&&p[k]<=12)&&['standard','lean'].includes(p.crate)}
function model(p){if(!validPlan(p))throw Error('Choose whole module counts from 0 to 12.');let food=p.crate==='lean'?158.4:172.8,mass=144+38.4+food+100,cost=p.crate==='lean'?800:1000,load=24;for(let k of KEYS){mass+=p[k]*EQUIP[k][2];cost+=p[k]*EQUIP[k][3];load+=p[k]*EQUIP[k][1]}const rates={water:30*p.water-72,oxygen:8*p.oxygen-19.2,food:-14.4},initial={water:144,oxygen:38.4,food},caps={water:400,oxygen:100,food:200},days=[{day:0,...initial,battery:36*p.battery,unserved:0,resourceShortage:0}];for(let d=1;d<=10;d++){let prev=days[d-1],r={day:d,unserved:0,resourceShortage:0};for(let k of ['water','oxygen','food']){let raw=prev[k]+rates[k];r[k]=round(Math.max(0,Math.min(caps[k],raw)));r.resourceShortage+=Math.max(0,-raw)}let balance=(d>=4&&d<=6?27:36)*p.solar-load,raw=prev.battery+balance;r.battery=round(Math.max(0,Math.min(36*p.battery,raw)));r.unserved=round(Math.max(0,-raw));days.push(r)}let reasons=[];if(p.habitat*8<24||p.habitat*24<72)reasons.push('Habitat capacity or floor area is too small.');if(p.water*30<72)reasons.push('Daily water production is below 72 L/day.');if(p.oxygen*8<19.2)reasons.push('Daily oxygen production is below 19.2 kg/day.');if(days.some(x=>x.resourceShortage>0))reasons.push('A resource runs out during the mission.');if(days.some(x=>x.unserved>0))reasons.push('Stored energy and solar output cannot cover every modeled day.');if(cost>26000)reasons.push('Cost exceeds the 26,000 cr budget.');if(mass>3400)reasons.push('Cargo exceeds 3,400 kg.');let last=days[10],resilient=last.water>=144&&last.oxygen>=38.4&&last.food>=28.8;return {mass:round(mass),cost,load,rates,initial,caps,days,reasons,ending:reasons.length?'Deployment delayed':resilient?'Resilient outpost':'Mission ready',budget:26000-cost,cargo:round(3400-mass),area:24*p.habitat,occupancy:8*p.habitat,perPerson:p.habitat,storm:27*p.solar,normal:36*p.solar,balance:27*p.solar-load}}
const F={};function def(id,stage,label,unit,expected,deps=[],help='Multiply the rate by the number of people or days. Example: 5 people × 2 L/person/day = 10 L/day.',options=null){F[id]={id,stage,label,unit,expected,deps,help,options};}
def('waterDaily',2,'Daily water demand','L/day',()=>72);def('oxygenDaily',2,'Daily oxygen demand','kg/day',()=>19.2);def('foodDaily',2,'Daily food demand','kg/day',()=>14.4);def('waterTotal',2,'Ten-day water demand','L',()=>720);def('oxygenTotal',2,'Ten-day oxygen demand','kg',()=>192);def('foodTotal',2,'Ten-day food demand','kg',()=>144);
for(let [id,u,value]of [['liters','L','stock'],['waterRate','L/day','rate'],['kilograms','kg','stock'],['massRate','kg/day','rate'],['energy','kWh','stock'],['energyRate','kWh/day','rate']])def(id,2,'Classify '+u,'',()=>value,[],'Stock is an amount at a moment; rate is an amount per time. Example: 5 L is stock; 5 L/day is a rate.',['stock','rate']);
def('grams',2,'Convert 0.8 kg to grams','g',()=>800,[],'Multiply kilograms by 1,000. Example: 1.2 kg = 1,200 g.');def('milliliters',2,'Convert 3 L to milliliters','mL',()=>3000,[],'Multiply liters by 1,000. Example: 2 L = 2,000 mL.');
const ceilHelp='Divide demand by one module’s capacity, then round upward to a whole module. Example: 13 ÷ 6 needs 3 modules, whose capacity is 18.';
for(let [id,label,value,unit]of [['minWater','Minimum water modules',3,'modules'],['minOxygen','Minimum oxygen modules',3,'modules'],['minHabitat','Minimum habitats',3,'habitats'],['waterCapacity','Water capacity at the minimum count',90,'L/day'],['oxygenCapacity','Oxygen capacity at the minimum count',24,'kg/day'],['housingCapacity','Occupancy at the minimum count',24,'people']])def(id,3,label,unit,()=>value,[],ceilHelp);
def('area',3,'Selected habitat floor area','m²',s=>model(s.plan).area,['habitat'],'Multiply floor area by habitat count. Example: 2 habitats × 20 m² = 40 m².');def('occupancy',3,'Selected habitat occupancy','people',s=>model(s.plan).occupancy,['habitat'],'Multiply occupancy per habitat by count. Example: 2 habitats × 6 people = 12 people.');def('perPerson',3,'Selected floor area per settler','m²/person',s=>model(s.plan).perPerson,['habitat'],'Divide total area by 24 settlers. Example: 60 m² ÷ 20 people = 3 m²/person.');
for(let[id,label,unit]of [['mass','Total cargo','kg'],['cost','Total cost','cr'],['cargo','Cargo capacity remaining (may be negative)','kg'],['budget','Budget remaining (may be negative)','cr']])def(id,4,label,unit,s=>model(s.plan)[id],[...KEYS,'crate'],'Multiply each equipment count by its mass/cost, add crate contents, then subtract from the limit. Example: a 100 cr limit − 120 cr cost = −20 cr.');
const forecastDeps=['resource','water','oxygen','crate'];
def('initial',5,'Stock equation: initial amount','selected resource units',s=>model(s.plan).initial[s.resource],forecastDeps,'Write stock = initial + net daily change × t. Example: S(t)=50+3t. Enter 50 as initial and 3 as net.');def('net',5,'Stock equation: signed net daily change','units/day',s=>round(model(s.plan).rates[s.resource]),forecastDeps,'Subtract daily use from production. Example: 12 L/day − 15 L/day = −3 L/day. Food has no daily production.');
def('xAxis',5,'Horizontal axis','',()=> 'Earth days',[],'The horizontal axis measures time in 24-hour Earth days.',['Earth days','Resource amount']);def('yAxis',5,'Vertical axis unit','',s=>s.resource==='water'?'L':'kg',forecastDeps,'Use the selected resource’s stock unit; do not use its per-day rate.',['L','kg','kWh','L/day','kg/day']);
for(let d of [0,5,10]){def('table'+d,5,'Table: stock after day '+d,'selected resource units',s=>model(s.plan).days[d][s.resource],forecastDeps,'Start with the initial amount; add net daily change each day. Apply the stated tank cap and record any unmet demand separately. Example: min(100,80+5×6)=100.');def('point'+d,5,'Plot point: y-value at x = '+d,'selected resource units',s=>model(s.plan).days[d][s.resource],forecastDeps,'Enter the ordered pair’s y coordinate from your table. Example: at day 2 with 40 L, plot (2,40).')}
def('percent',6,'Percentage of solar yield remaining','%',()=>75,[],'Subtract the loss from 100%. Example: a 10% reduction leaves 90%.');def('perArray',6,'Storm yield per array','kWh/day',()=>27,[],'Multiply normal yield by the remaining percentage as a decimal. Example: 40 × 0.8 = 32.');
for(let[id,label]of [['load','Total daily electrical load'],['normal','Normal solar output'],['storm','Storm solar output'],['balance','Signed storm surplus / deficit']])def(id,6,label,'kWh/day',s=>model(s.plan)[id],['water','oxygen','habitat','solar'],'Load = fixed load + equipment use. Balance = generation − load. Batteries store kWh; they do not generate kWh/day. Example: 80 − 90 = −10 kWh/day.');
for(let d of [3,4,5,6,7])def('battery'+d,7,'Stored energy at end of day '+d,'kWh',s=>model(s.plan).days[d].battery,KEYS,'Start full. Add daily generation minus load, bounded by zero and usable capacity. Record uncovered shortages separately. Example: 20 stored − 8 deficit = 12 kWh.');
def('unserved',7,'Total unserved energy during days 4–6','kWh',s=>round(model(s.plan).days.slice(4,7).reduce((a,x)=>a+x.unserved,0)),KEYS,'When the battery is empty, record any remaining deficit as unserved. Example: 3 stored − 8 needed leaves 5 kWh unserved.');
for(let[id,label,unit,val]of [['compareCost','Reference B minus A: cost','cr',200],['compareMass','Reference B minus A: cargo','kg',20],['compareBattery','Reference A: stored energy after day 6','kWh',18],['compareSurplus','Reference B: storm daily surplus','kWh/day',21]])def(id,7,label,unit,()=>val,[],'Compare the two standard-crate reference configurations, each with three water, oxygen and habitat modules. A: 4 arrays + 1 battery. B: 5 arrays + 0 batteries. Subtract A from B for differences. Example: 500 − 450 = 50.');
for(let[who,n]of [['A',30],['B',28]]){def('transfer'+who+'Water',8,'Partner '+who+': daily water for '+n+' settlers','L/day',()=>n*3,[],'Apply the per-person rate to the new population. Example: 12 people × 3 L/day = 36 L/day.');def('transfer'+who+'Modules',8,'Partner '+who+': minimum 30 L/day water modules','modules',()=>Math.ceil(n*3/30),[],ceilHelp)}
function fingerprint(s,f){let deps=f.deps;if(f.stage===5&&deps.includes('resource'))deps=['resource',...(s.resource==='food'?['crate']:[s.resource])];return JSON.stringify(deps.map(k=>k==='resource'?s.resource:s.plan[k]))}
function current(s,id){let c=s.checkpoints[id];return !!c&&c.ok&&c.response===s.inputs[id]&&c.fp===fingerprint(s,F[id])}
function fields(stage){return Object.values(F).filter(f=>f.stage===stage)}
function check(s,stage,filter=null){let errors=[];for(let f of fields(stage).filter(f=>!filter||filter.includes(f.id))){let raw=s.inputs[f.id]??'',exp=f.expected(s),got=typeof exp==='string'?raw:number(raw),ok=typeof exp==='string'?got===exp:Number.isFinite(got)&&Math.abs(got-exp)<1e-9;let a={field:f.id,response:raw,ok,fp:fingerprint(s,f),plan:{...s.plan},resource:s.resource,at:new Date().toISOString()};s.attempts.push(a);s.checkpoints[f.id]={ok,response:raw,fp:a.fp,first:s.checkpoints[f.id]?.first??raw};if(!ok)errors.push({id:f.id,message:f.label+': '+(String(raw).trim()===''?'enter an answer.':'recheck the calculation or unit. ')+f.help})}return errors}
function newSession(){return {schema:'mcada-project-progress',schemaVersion:'1.0.0',contentVersion:'1.0.0',projectId:'mars-colony',appVersion:VERSION,sessionId:'mc-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),teamAlias:'',currentStage:1,unlocked:1,plan:{...BASE},resource:'water',inputs:{},checkpoints:{},attempts:[],help:[],notes:{},revision:0,brief:false,completedAt:null}}
function validate(s){if(!s||s.schema!=='mcada-project-progress'||s.schemaVersion!=='1.0.0'||s.contentVersion!=='1.0.0'||s.projectId!=='mars-colony')throw Error('Wrong project or unsupported schema/content version.');if(!validPlan(s.plan)||!['water','oxygen','food'].includes(s.resource)||typeof s.teamAlias!=='string'||s.teamAlias.length>60||!Number.isInteger(s.currentStage)||s.currentStage<1||s.currentStage>8||!Number.isInteger(s.unlocked)||s.unlocked<1||s.unlocked>8||s.currentStage>s.unlocked||!Number.isInteger(s.revision)||s.revision<0||typeof s.sessionId!=='string'||!/^mc-[a-zA-Z0-9-]+$/.test(s.sessionId))throw Error('Invalid mission configuration.');if(!s.inputs||!s.notes||!s.checkpoints||!Array.isArray(s.attempts)||s.attempts.length>10000||!Array.isArray(s.help)||s.help.length>10000)throw Error('Invalid evidence records.');for(let[k,v]of Object.entries(s.inputs))if(!F[k]||typeof v!=='string'||v.length>120)throw Error('Invalid response field.');for(let[k,v]of Object.entries(s.notes))if(!['choice','reason','limitation'].includes(k)||typeof v!=='string'||v.length>1500)throw Error('Invalid reflection.');for(let[k,c]of Object.entries(s.checkpoints))if(!F[k]||!c||typeof c.ok!=='boolean'||typeof c.response!=='string'||typeof c.fp!=='string'||typeof c.first!=='string')throw Error('Invalid checkpoint.');for(let a of s.attempts)if(!a||!F[a.field]||typeof a.response!=='string'||typeof a.ok!=='boolean'||!validPlan(a.plan)||typeof a.at!=='string')throw Error('Invalid attempt.');for(let h of s.help)if(!h||!F[h.field]||typeof h.at!=='string')throw Error('Invalid help record.');const keys=Object.keys(newSession());if(Object.keys(s).some(k=>!keys.includes(k)))throw Error('Unsupported save field.');return JSON.parse(JSON.stringify(s))}
return {VERSION,BASE,KEYS,EQUIP,F,number,round,model,newSession,validate,current,check,fields,fingerprint};
})();
if(typeof module!=='undefined')module.exports=MC;
