const C=require('../src/core.js'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const checks=[];function eq(a,b,label){assert.deepEqual(a,b,label);checks.push({label,passed:true})}function rejects(fn,label){assert.throws(fn,undefined,label);checks.push({label,passed:true})}
const ANSWERS={drawW:'15',drawH:'10',real35:'14',ratio:'1:400',cellArea:'4',doubleArea:'16',lengthFactor:'2',areaFactor:'4',columns:'30',rows:'20',siteArea:'2400',area_coaster:'240',area_carousel:'144',area_theater:'160',area_food:'80',area_services:'48',area_entrance:'32',radius:'5',circleArea:'78.5',triangleArea:'24',circleFormula:'radius',triangleFormula:'half',clearance:'65.5',rideLedger:'144',shadeExtra:'0',landClass:'inside',beforeW:'20',beforeH:'12',afterW:'12',afterH:'20',beforeArea:'240',afterArea:'240',mainH:'240',mainV:'160',cross:'16',mainUnion:'384',pathArea:'432',greenArea:'480',facArea:'704',unused:'784',pathPercent:'18',greenFraction:'1/5',greenPercent:'20',expClass:'unused',expArea:'140',perimeter:'200',facilityCost:'60000',pathCost:'10800',greenCost:'4800',boundaryCost:'4000',total:'79600',balance:'10400',reserve:'11.6'};
const TRANSFER={transferAwidth:'3',transferAheight:'2',transferAarea:'96',transferApercent:'4',transferArotWidth:'2',transferArotHeight:'3',transferBwidth:'4',transferBheight:'1.5',transferBarea:'96',transferBpercent:'4',transferBrotWidth:'1.5',transferBrotHeight:'4'};
function checkedSession(){let s=C.fresh('QA Pair');s.parkName='Willow Park';s.plan=C.baseline();s.plan.rotationSeen=true;Object.assign(s.plan.raw,ANSWERS);for(let n=1;n<=7;n++)assert.equal(C.check(s,'C0'+n).length,0,'check '+n);return s}
function completed(kind='distinction'){let s=checkedSession();C.saveSnapshot(s,'A');s.plan.expansion=null;s.plan.revision++;C.check(s,'C06');C.saveSnapshot(s,'B');Object.assign(s.raw,{metric:'cost',valueA:'79600',valueB:'79600',delta:'0',chosen:kind==='approved'?'B':'A',reason:'We kept a clear 140 m² expansion zone in Plan A.'},TRANSFER);for(let g of ['C08','C09A','C09B'])assert.equal(C.check(s,g).length,0);s.currentStage=8;s.maxStage=8;return s}
function run(){let p=C.baseline(),g=C.geometry(p);eq([g.facilityArea,g.pathArea,g.greenArea,g.unused,g.cost,g.balance,g.expansionArea],[704,432,480,784,79600,10400,140],'dossier baseline exact');eq(g.errors,[],'baseline no structural errors');eq(g.connected.length,108,'108 rooted path cells');eq(Object.values(g.doors),[true,true,true,true,true,true],'six doors connected');eq(g.code,'distinction','baseline distinction');eq(C.rectCells([0,0,60,40]).length,600,'600 site cells');eq(C.MAIN.length*4,384,'main union excludes overlap');eq(C.q(10400).div(900).round(1).str(),'58/5','reserve rounding 11.6');
for(let [raw,unit,key] of [['2,400','m²',2400],['157/2','m²',78.5],['−100','cr',-100],[' 20 % ','%',20],['480/2400','',.2],['1.5 cm','cm',1.5]])eq(C.numeric(raw,unit).eq(key),true,'numeric '+raw);
for(let raw of ['', '1/0','NaN','Infinity','1,5','2,40','<img>','3+4','1e6','2/3/4'])rejects(()=>C.numeric(raw),'reject '+raw);rejects(()=>C.numeric('20 m','m²'),'wrong unit');
let d=C.fresh();eq(C.evaluate(d,'ratio','2:800'),null,'equivalent scale ratio');eq(C.evaluate(d,'ratio','1:4')!==null,true,'mixed unit ratio rejected');for(let [k,v]of [['areaFactor','2'],['radius','10'],['circleArea','314'],['triangleArea','48'],['shadeExtra','24'],['rideLedger','78.5']])eq(C.evaluate(d,k,v)!==null,true,'misconception '+k);
for(let r of [[-2,0,2,2],[0,0,0,2],[1,0,2,2],[58,38,4,2]])rejects(()=>C.rectCells(r),'invalid rectangle '+r);eq(C.rectCells([58,38,2,2]),[599],'boundary touching accepted');eq(C.touches([[10,16],[14,16]],8*30+7),false,'corner-only door rejected');eq(C.flood([0,31],[0]).size,1,'diagonal path disconnected');let rot={x:0,y:0,rotation:90};eq(C.dims(C.byId.coaster,rot),[12,20],'rotation dimensions');eq(C.segment(C.byId.coaster,rot),[[0,8],[0,12]],'rotated door follows tile');eq(C.segment(C.byId.entrance,rot,'street'),[[8,0],[8,4]],'rotated street side east');
let before=C.clone(p);rejects(()=>C.place(p,'coaster',0,18,0),'facility cannot overlap required path');eq(p,before,'invalid placement preserves work');rejects(()=>C.paint(p,'green',C.rectCells([28,0,2,2])),'green cannot cover path');eq(p,before,'invalid paint atomic');C.paint(p,'paths',p.paths);eq(C.geometry(p).cost,79600,'duplicate paint no cost');rejects(()=>C.paint(p,'paths',[C.MAIN[0]],true),'main paths nonerasable');p=C.baseline();C.setExpansion(p,[28,0,10,10]);eq(C.geometry(p).expansionOK,false,'occupied expansion cannot qualify');eq(C.geometry(p).cost,79600,'expansion no extra cost');p=C.baseline();p.paths=p.paths.filter(i=>!C.rectCells([10,16,4,2]).includes(i));g=C.geometry(p);eq(g.doors.coaster,false,'missing connector shown');eq(g.code,'revision','disconnected path design revision');
let s=checkedSession();eq(C.planOK(s),true,'all plan checkpoints complete');C.setExpansion(s.plan,null);eq(C.groupOK(s,'C05'),true,'expansion edit retains layout math');eq(C.groupOK(s,'C07'),true,'expansion edit retains budget');s=checkedSession();C.paint(s.plan,'green',C.rectCells([0,0,8,2]),true);eq(C.state(s,'greenArea'),'stale','green edit invalidates green area');eq(C.state(s,'pathArea'),'checked','green edit preserves path area');eq(C.groupOK(s,'C05'),true,'green edit preserves facility/rotation evidence');eq(C.state(s,'total'),'stale','green edit invalidates total');eq(s.plan.raw.greenArea,'480','stale answer retained');g=C.geometry(s.plan);eq([g.greenArea,g.cost,g.balance,g.code],[464,79440,10560,'revision'],'low green fixture');Object.assign(s.plan.raw,{greenArea:'464',greenFraction:'29/150',greenPercent:'19.3',unused:'800',greenCost:'4640',total:'79440',balance:'10560',reserve:'11.7'});eq(C.check(s,'C06'),[],'correct low-green math accepted');eq(C.check(s,'C07'),[],'correct cheaper weak-design costs accepted');eq(s.plan.history.filter(x=>x.key==='greenArea')[0].response,'480','first checked evidence retained');
s=completed();eq(C.outcome(s).code,'distinction','completed distinction');eq(C.outcome(completed('approved')).code,'approved','completed ordinary approval');eq(C.geometry(s.plan).expansionOK,false,'working plan differs from selected snapshot');let a=C.snapshot(s,s.aId),frozen=JSON.stringify(a);s.plan.green=[];eq(JSON.stringify(a),frozen,'snapshots immutable across working edits');eq(C.outcome(s).code,'distinction','report uses exact selected snapshot');s=completed();let rt=C.validateSession(JSON.parse(JSON.stringify(s)));eq(C.outcome(rt).code,'distinction','completed roundtrip');eq(rt.plan.history.length,s.plan.history.length,'history roundtrip');let wrong=C.clone(s);wrong.projectId='road-trip';rejects(()=>C.validateSession(wrong),'wrong project');wrong=C.clone(s);wrong.schemaVersion='2.0.0';rejects(()=>C.validateSession(wrong),'future schema');wrong=C.clone(s);wrong.snapshots[0].plan.paths.push(999);rejects(()=>C.validateSession(wrong),'bad cell in snapshot');wrong=C.clone(s);wrong.raw.inject='test';rejects(()=>C.validateSession(wrong),'unknown field');wrong=C.clone(s);wrong.raw.transferAarea='0';wrong.evidence.transferAarea.response='0';eq(C.outcome(C.validateSession(wrong)).code,'draft','claimed correct import answer rechecked');
C.bypass(s,'C09A','Teacher observed access problem');eq(C.outcome(s).code,'provisional','bypass labelled provisional');s=completed();C.deleteSnapshot(s,s.aId);eq(s.aId,null,'delete selected snapshot clears reference');eq(C.outcome(s).code,'draft','deleted comparison redrafted');eq(s.snapshots.length,1,'unrelated snapshot preserved');eq(C.outcome(C.fresh()).code,'draft','new session draft');
const mem=new Map();const store={get length(){return mem.size},key:i=>[...mem.keys()][i],getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};let db=new C.Store(store),one=completed();db.write(one);let prior=C.clone(one);db.write(one);rejects(()=>db.write(prior),'cross-tab stale write rejected');store.setItem('mcada:road-trip:session:keep','stay');db.delete([one.sessionId]);eq(store.getItem('mcada:road-trip:session:keep'),'stay','other project retained');eq(db.ids(),[],'sessions fully deleted');let dup=C.duplicate(one);eq(dup.sessionId!==one.sessionId,true,'duplicate gets independent identity');eq(C.decode(JSON.stringify({schema:'theme-park-backup',sessions:[completed()]})).length,1,'backup decode');rejects(()=>C.decode('{oops'),'malformed JSON');rejects(()=>C.decode(' '.repeat(5*1024*1024+1)),'oversized file');eq(new C.Store({setItem(){throw Error('denied')}}).available,false,'storage denial fallback');eq(C.diagnostics().every(x=>x.passed),true,'diagnostics');
let out=path.join(__dirname,'../docs/verification');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'core-results.json'),JSON.stringify({passed:checks.length,failed:0,environment:'Node '+process.version,scope:'Pure application mathematics, geometry, state and storage logic',checks},null,2));for(let kind of ['distinction','approved'])fs.writeFileSync(path.join(__dirname,'ending-'+kind+'.json'),JSON.stringify(completed(kind),null,2));console.log(checks.length+' core checks passed');}
if(require.main===module)run();module.exports={ANSWERS,TRANSFER,checkedSession,completed,run};
