const C=require('../src/core.js'),{answers,filled}=require('./fixtures.cjs'),assert=require('node:assert/strict'),fs=require('fs');let checks=[];
function test(name,f){try{f();checks.push({name,passed:true})}catch(e){checks.push({name,passed:false,error:e.message});console.error(name,e)}}
for(const t of ['A','B'])test('Complete '+t,()=>assert.equal(C.outcome(filled(C,t)),'Featured exhibit'));
for(const [g,fields]of Object.entries(answers)){test('Correct '+g,()=>{const s=filled(C);assert.deepEqual(C.evaluate(s,g),{})});for(const f of Object.keys(fields).filter(f=>!['tool','interpretation','visitor'].includes(f)))test('Wrong '+g+'.'+f,()=>{const s=filled(C);C.setInput(s,g+'.'+f,'incorrect');assert(Object.keys(C.evaluate(s,g)).length)})}
for(const [expr,expected]of [['2e-4','0.0002'],['8e-6','0.000008'],['1/640000000','1.5625e-9'],['1,280,000','1280000'],['3.15 × 10^-5','0.0000315'],['−2','-2']])test('Parse '+expr,()=>assert(C.q(expr).eq(expected)));
for(const x of ['1,28','2e25','2e-25','NaN','Infinity','1/0','1+2','<script>','', '3e1.5'])test('Reject '+x,()=>assert.throws(()=>C.q(x)));
test('Tiny zero',()=>assert(!C.q(0).eq('8e-6')));test('Normalization',()=>assert.throws(()=>C.sci('31.5','-6')));test('12-digit coefficient boundary',()=>assert(C.sci('1.23456789012','0')));test('13 digits reject',()=>assert.throws(()=>C.sci('1.234567890123','0')));
test('Zero canonical',()=>assert(C.sci('0','0').eq(0)));test('Optional exponent C05a',()=>{let s=filled(C);C.setInput(s,'C05a.n','');assert.deepEqual(C.evaluate(s,'C05a'),{})});
test('Alternative common exponent',()=>{let s=filled(C);for(const [k,v]of Object.entries({common:'-5',left:'2.4',right:'0.75'}))C.setInput(s,'C06a.'+k,v);assert.deepEqual(C.evaluate(s,'C06a'),{})});
test('Equivalent ratio',()=>{let s=filled(C);C.setInput(s,'C08A.ratioM','40000');C.setInput(s,'C08A.ratioA','2');assert.deepEqual(C.evaluate(s,'C08A'),{})});
test('Wrong ratio direction',()=>{let s=filled(C);C.setInput(s,'C08A.ratioM','1');C.setInput(s,'C08A.ratioA','20000');assert(C.evaluate(s,'C08A').ratioA)});
for(const t of ['A','B'])for(const [id,,target,tol]of C.measurements[t])for(const side of [-1,1])for(const outside of [false,true])test('Tolerance '+t+id+side+outside,()=>{let s=filled(C,t);let diff=C.q(tol).add(outside?'0.1':0).mul(side),val=C.q(target).add(diff);C.setInput(s,'C09'+t+'.'+id,val.str());C.setInput(s,'C09'+t+'.'+id+'Deviation',diff.str());assert.deepEqual(C.check(s,'C09'+t),{});assert.equal(C.fit(s),!outside);assert.equal(C.outcome(s),outside?'Calibration required':'Exhibit ready for review')});
test('Measurement unit equivalence',()=>{let s=filled(C);C.setInput(s,'C09A.cell','16');C.setInput(s,'C09A.cellUnit','cm');assert.deepEqual(C.evaluate(s,'C09A'),{})});
test('Wrong unit changes quantity',()=>{let s=filled(C);C.setInput(s,'C09A.cellUnit','m');assert(C.evaluate(s,'C09A').cellDeviation)});
test('Single upstream invalidation',()=>{let s=filled(C);C.setInput(s,'C04a.a','9');assert.equal(C.status(s,'C04a'),'needs-recheck');assert.equal(C.status(s,'C04b'),'checked');assert.equal(C.outcome(s),'Draft — finish checks');assert.equal(s.attempts[7].response.a,'2')});
test('Plan change stales downstream only',()=>{let s=filled(C);C.setInput(s,'C08A.model','0.17');assert.equal(C.status(s,'C09A'),'needs-recheck');assert.equal(C.status(s,'C121'),'checked');assert.equal(C.status(s,'C04a'),'checked')});
test('Rebuild inspection stale',()=>{let s=filled(C);s.buildRevisions.A++;assert.equal(C.reviewState(s,'inspection'),'pending');assert.equal(C.status(s,'C09A'),'needs-recheck')});
test('Track choice retains evidence',()=>{let s=filled(C);s.track='B';assert.equal(C.outcome(s),'Featured exhibit');s.track='A';assert.equal(C.outcome(s),'Featured exhibit')});
test('Pending review',()=>assert.equal(C.outcome(filled(C,'A',false)),'Exhibit ready for review'));
test('Missing labels repair',()=>{let s=filled(C);C.setInput(s,'placardA.source','');assert.equal(C.outcome(s),'Calibration required')});
test('Reviewed repair',()=>{let s=filled(C);C.review(s,'interpretation','Fixture','teacher','repair-needed','Needs numerical explanation.');assert.equal(C.outcome(s),'Calibration required')});
test('Bypass provisional',()=>{let s=filled(C);C.bypass(s,'C04a','Fixture','Test only');assert.equal(C.outcome(s),'Provisional — teacher review');C.check(s,'C04a');assert.equal(C.outcome(s),'Featured exhibit');assert.equal(s.teacherOverrides.length,1)});
test('First attempt persists',()=>{let s=filled(C);C.setInput(s,'C04a.a','9');C.check(s,'C04a');C.setInput(s,'C04a.a','2');C.check(s,'C04a');assert.equal(s.attempts.filter(a=>a.group==='C04a').length,3);assert.equal(s.attempts.find(a=>a.group==='C04a').response.a,'2')});
test('Paper review pending then accepted',()=>{let s=filled(C);C.setInput(s,'C121.mode','paper');C.setInput(s,'C121.submission','Teacher received response on paper.');C.check(s,'C121');assert.equal(C.outcome(s),'Exhibit ready for review');C.review(s,'C121','Fixture','teacher','accepted','Reviewed actual paper in this synthetic test.');assert.equal(C.outcome(s),'Featured exhibit')});
test('Independent paper review survives track switch',()=>{let s=filled(C);C.setInput(s,'C121.mode','paper');C.setInput(s,'C121.submission','Teacher received paper.');C.check(s,'C121');C.review(s,'C121','Fixture','teacher','accepted','Synthetic review.');s.track='B';assert.equal(C.reviewState(s,'C121'),'accepted');assert.equal(C.outcome(s),'Featured exhibit')});
test('Peer cannot certify interpretation',()=>assert.throws(()=>C.review(filled(C),'interpretation','Peer','peer','accepted','test')));
test('Roundtrip',()=>{let s=filled(C,'B');let out=C.parseImport(JSON.stringify(s))[0];assert.equal(C.outcome(out),'Featured exhibit');assert.equal(out.imported,true);assert.deepEqual(out.attempts,s.attempts)});
test('Bundle roundtrip',()=>assert.equal(C.parseImport(JSON.stringify(C.bundle([filled(C),filled(C,'B')]))).length,2));
test('Duplicate keeps original',()=>{let s=filled(C),copy=C.duplicate(s);assert.notEqual(copy.sessionId,s.sessionId);assert.equal(copy.duplicateOf,s.sessionId);assert.equal(copy.localRevision,0)});
for(const [label,mutate]of [['wrong project',s=>s.projectId='food-truck'],['future schema',s=>s.schemaVersion='9'],['unknown content',s=>s.contentVersion='2'],['field injection',s=>s.inputs.unknown='x'],['oversize',s=>s.inputs['C01a.a']='1'.repeat(101)],['fake bypass',s=>{s.checkpoints.C04a.bypass=true;s.checkpoints.C04a.overrideId='missing'}],['bad reviewer',s=>s.reviews[0].role='alien'],['bad revision',s=>s.buildRevisions.A=-1]])test('Import rejects '+label,()=>{let s=filled(C);mutate(s);assert.throws(()=>C.parseImport(JSON.stringify(s)))});
test('Forged checked flag recomputed',()=>{let s=filled(C);s.inputs['C04a.a']='7';s.checkpoints.C04a.fingerprint=C.fingerprint(s,'C04a');let out=C.parseImport(JSON.stringify(s))[0];assert.notEqual(C.status(out,'C04a'),'checked')});
class Memory{constructor(){this.m=new Map();this.fail=null}get length(){return this.m.size}key(i){return [...this.m.keys()][i]}getItem(k){return this.m.get(k)??null}setItem(k,v){if(this.fail?.(k))throw Error('fail');this.m.set(k,String(v))}removeItem(k){if(this.fail?.(k))throw Error('fail');this.m.delete(k)}}
test('Namespaced storage and deletion',()=>{const mem=new Memory(),db=new C.Store(mem),s=filled(C),other=filled(C,'B');mem.setItem('mcada:food-truck:session:other','retained');db.save(s);db.save(other);assert.equal(db.list().length,2);db.remove([s.sessionId]);assert.equal(db.read(s.sessionId),null);assert(db.read(other.sessionId));db.remove(db.ids());assert.equal(db.ids().length,0);assert.equal(mem.getItem('mcada:food-truck:session:other'),'retained');db.save(C.newSession());assert.equal(db.ids().length,1)});
test('Atomic index failure rollback',()=>{const mem=new Memory(),db=new C.Store(mem),s=filled(C);db.save(s);const before=mem.getItem(C.PREFIX+'session:'+s.sessionId),newer=C.clone(s);newer.teamAlias='Changed';let once=true;mem.fail=k=>k.endsWith('index')&&once?(once=false,true):false;assert.throws(()=>db.save(newer));assert.equal(mem.getItem(C.PREFIX+'session:'+s.sessionId),before)});
test('Denied storage',()=>{const mem=new Memory();mem.fail=()=>true;const db=new C.Store(mem);assert.equal(db.available,false);assert.throws(()=>db.save(C.newSession()))});
test('Newer-tab conflict',()=>{let db=new C.Store(new Memory()),s=filled(C);db.save(s);const stale=C.clone(s);db.save(s);assert.throws(()=>db.save(stale),/CONFLICT/)});
test('Partial deletion failure truthful',()=>{const mem=new Memory(),db=new C.Store(mem),s=filled(C);db.save(s);mem.fail=k=>k.includes(s.sessionId);assert.throws(()=>db.remove([s.sessionId]));assert(db.read(s.sessionId))});
test('Diagnostics pure',()=>{let s=filled(C),before=JSON.stringify(s);assert(C.diagnostics().every(c=>c.passed));assert.equal(JSON.stringify(s),before)});
const report={scope:'Pure implementation evaluators, evidence, import and storage using synthetic data',passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks};fs.writeFileSync(__dirname+'/core-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed}));if(report.failed)process.exit(1);
