const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),C=require('../src/core.js'),{filled}=require('./fixtures.cjs');const output=process.env.SN_ARTIFACT_DIR||path.join(__dirname,'artifacts');fs.mkdirSync(output,{recursive:true});let checks=[];
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.SN_CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const test=async(name,f)=>{await f();checks.push({name,passed:true})};try{
const ctx=await b.newContext();await ctx.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('Storage denied')}});const p=await ctx.newPage();await p.goto('file://'+path.resolve(__dirname,'../index.html'));
await test('Storage denial displayed without blank screen',async()=>assert.match(await p.locator('body').innerText(),/storage is unavailable/i));
await test('Unsaved work preserved on New session',async()=>{await p.locator('#team').fill('Keep-in-memory');await p.locator('[data-action="sessions"]').click();await p.locator('[data-action="new"]').click();assert.match(await p.locator('dialog').innerText(),/could not be saved/);assert.equal(await p.evaluate(()=>SNApp.state.teamAlias),'Keep-in-memory');await p.locator('[data-action="close"]').first().click()});
await test('Denied storage still exports',async()=>{const wait=p.waitForEvent('download');await p.locator('[data-action="export"]').first().click();const file=await wait;await file.saveAs(path.join(output,'denied-export.json'));assert.equal(JSON.parse(fs.readFileSync(path.join(output,'denied-export.json'))).teamAlias,'Keep-in-memory')});await ctx.close();
const q=await b.newPage();await q.goto('file://'+path.resolve(__dirname,'../index.html'));
await test('Imported HTML string is inert',async()=>{const s=filled(C);s.inputs['C11A.interpretation']='<img src=x onerror="window.injected=true">';C.check(s,'C11A');await q.evaluate(v=>SNApp.setState(SN.parseImport(JSON.stringify(v))[0]),s);assert.equal(await q.evaluate(()=>window.injected),undefined);assert.equal(await q.locator('.placard img').count(),0);assert.match(await q.locator('.placard').innerText(),/<img src=x/) });
await test('Maximum text prints with continuation labels',async()=>{const s=filled(C);s.inputs['C11A.interpretation']='Model explanation. '.repeat(31).slice(0,600);s.inputs['C11A.visitor']='Other model comparison. '.repeat(26).slice(0,600);C.check(s,'C11A');C.review(s,'interpretation','Fixture','teacher','accepted','Review note. '.repeat(30));await q.evaluate(v=>{SNApp.setState(v);document.querySelector('#print-root').innerHTML=SNApp.printHTML('report')},s);await q.emulateMedia({media:'print'});await q.pdf({path:path.join(output,'long-report-Letter.pdf'),format:'Letter',printBackground:true});assert.match(await q.locator('#print-root').innerText(),/continued on further pages/i);await q.emulateMedia({media:'screen'})});
await test('Keyboard minus button',async()=>{const s=filled(C);s.currentStage=2;await q.evaluate(v=>SNApp.setState(v),s);await q.locator('#field-C01a-n').fill('6');await q.locator('[data-action="minus"][data-target="field-C01a-n"]').click();assert.equal(await q.locator('#field-C01a-n').inputValue(),'-6')});
await test('Newer browser tab conflict preserves inputs',async()=>{await q.evaluate(()=>{SNApp.store.save(SNApp.state);const newer=SN.clone(SNApp.state);SNApp.store.save(newer);SNApp.state.inputs['C01a.a']='9'});await q.locator('[data-action="save"]').click();assert.match(await q.locator('#save-status').innerText(),/Newer work/);assert.equal(await q.evaluate(()=>SNApp.state.inputs['C01a.a']),'9')});
}catch(e){checks.push({name:'Edge check',passed:false,error:e.message});console.error(e.stack)}finally{await b.close();const r={scope:'Targeted UI storage denial, recovery, injection, long print, keyboard and tab-conflict checks',passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks};fs.writeFileSync(path.join(__dirname,'edges-results.json'),JSON.stringify(r,null,2));console.log(JSON.stringify({passed:r.passed,failed:r.failed}));if(r.failed)process.exitCode=1}})();
