/* Synthetic reference answers; not student observations. Independent expected literals. */
const answers={
C01a:{a:'8',n:'-6'},C01b:{a:'1.28',n:'7'},C01c:{value:'0.000000002'},C01d:{value:'384000000'},
C02:{first:'dna',second:'depth',third:'cell',a:'8',n:'-5',decade:'one'},C03a:{m:'0.000008',mm:'0.008',nm:'8000'},C03b:{m:'12800000'},
C04a:{c:'20',e:'-5',a:'2',n:'-4',unit:'m'},C04b:{c:'3.84',e:'8',a:'3.84',n:'8',unit:'m'},C05a:{c:'0.8',e:'1',a:'8',n:'0',unit:'widths'},C05b:{c:'0.5',e:'3',a:'5',n:'2',unit:'s'},
C06a:{common:'-6',left:'24',right:'7.5',a:'3.15',n:'-5',unit:'m'},C06b:{common:'7',left:'38.4',right:'6',a:'4.44',n:'8',unit:'m'},C07a:{common:'-6',left:'8',right:'2',a:'6',n:'-6',unit:'m'},C07b:{common:'7',left:'140',right:'1.28',a:'1.3872',n:'9',unit:'m'},
C08A:{model:'0.16',k:'20000',ratioM:'20000',ratioA:'1',direction:'enlarge'},C08B:{model:'0.02',k:'1/640000000',ratioM:'1',ratioA:'640000000',direction:'reduce',moon:'5.46875',rounded:'5.5',distance:'600'},
C09A:{cell:'160',cellUnit:'mm',cellDeviation:'0',tool:'Synthetic ruler',resolution:'1'},C09B:{earth:'20',earthUnit:'mm',earthDeviation:'0',moon:'5.5',moonUnit:'mm',moonDeviation:'0',centers:'600',centersUnit:'mm',centersDeviation:'0',tool:'Synthetic ruler',resolution:'0.5'},
C10A:{comparison:'person',size:'34000',available:'1500',actual:'1.6e12',conclusion:'impractical'},C10B:{comparison:'sun',size:'2.1875',available:'1500',actual:'1.6e12',conclusion:'impractical'},
C11A:{interpretation:'At this scale a 1.7 m person is 34 km tall. The cell model preserves diameter scale, not material or function.',visitor:'The Earth-Moon example preserves size and center distance but omits surface detail.',otherDirection:'reduce'},
C11B:{interpretation:'The Sun would be 2.1875 m wide, too large for a 0.6 m desk span. The model preserves length ratios.',visitor:'The cell model preserves diameter but not material or optional thickness.',otherDirection:'enlarge'},
C11match:{dna:'width',cell:'diameter',earth:'diameter',moon:'diameter',distance:'distance',sun:'diameter',orbit:'distance',light:'speed',image:'diagram'},
C121:{mode:'digital',a:'3',n:'-5',decimal:'0.00003',direction:'enlarge',scale:'5000'},C122:{mode:'digital',a:'6',n:'8',decimal:'600000000',direction:'reduce',scale:'5000'}};
function filled(C,t='A',reviewed=true){const s=C.newSession();s.teamAlias='Synthetic-'+t;s.students=['Test-1','Test-2'];s.track=t;s.built={A:true,B:true};s.currentStage=8;for(const [g,fs]of Object.entries(answers))for(const [f,v]of Object.entries(fs))C.setInput(s,g+'.'+f,v);for(const g of C.groups(s)){const e=C.check(s,g.id);if(Object.keys(e).length)throw Error(g.id+': '+JSON.stringify(e))}for(const t of ['A','B']){for(const [f,v]of Object.entries({title:'Synthetic exhibit '+t,property:t==='A'?'diameter':'diameter-distance',source:t==='A'?'R2':'R3/R4',scaleConfirmed:'yes'}))C.setInput(s,'placard'+t+'.'+f,v);if(reviewed){C.review(s,'inspection','Fixture','teacher','accepted','Synthetic fixture measurements, not an actual physical inspection.',t);C.review(s,'interpretation','Fixture','teacher','accepted','Synthetic interpretation accepted for test only.',t)}}return s}
module.exports={answers,filled};
