/* Hosted synthetic smoke test; fresh browser context, no existing user records. */
const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const url='https://williammcada.github.io/Applied-Math-Projects/powers-of-ten/',hash='d9a042236b8968cc172f17fb64cfeb564967b77434259a06192ffbbf4de0a7ac';
const output=process.env.SN_ARTIFACT_DIR||path.join(__dirname,'artifacts');fs.mkdirSync(output,{recursive:true});let checks=[],errors=[],requests=[];
(async()=>{const proxyURL=process.env.HTTPS_PROXY||process.env.https_proxy;const u=proxyURL?new URL(proxyURL):null;const proxy=u?{server:u.origin,...(u.username?{username:decodeURIComponent(u.username),password:decodeURIComponent(u.password)}:{})}:undefined;const b=await chromium.launch({proxy,headless:true,executablePath:process.env.SN_CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const test=async(name,f)=>{await f();checks.push({name,passed:true})};try{const ctx=await b.newContext({ignoreHTTPSErrors:!!proxy,viewport:{width:1365,height:1000},acceptDownloads:true});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>requests.push(r.url()));
for(const name of ['','PowersOfTen_v0.1.0.html'])await test('Hosted bytes '+(name||'index'),async()=>{const r=await ctx.request.get(url+name);assert.equal(r.status(),200);const bytes=await r.body();assert.equal(bytes.length,106044);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),hash)});
await p.goto(url);const click=async a=>p.locator('[data-action="'+a+'"]').first().click();
await test('Live identity and embedded images',async()=>{assert.match(await p.title(),/Powers of Ten/);assert.equal(await p.evaluate(()=>SN.VERSION),'0.1.0');assert(await p.locator('svg').count()>0);await p.screenshot({path:path.join(output,'hosted-title.png'),fullPage:true})});
await test('Hosted save and reload/resume',async()=>{await p.locator('#team').fill('Hosted-Synthetic');await p.locator('#learner1').fill('Test-One');await p.locator('#learner2').fill('Test-Two');await click('next');await click('save');await p.reload();await click('sessions');await click('resume');assert.equal(await p.evaluate(()=>SNApp.state.teamAlias),'Hosted-Synthetic');assert.equal(await p.evaluate(()=>SNApp.state.currentStage),2)});
const file=path.join(output,'hosted-progress.json');await test('Hosted actual export',async()=>{const wait=p.waitForEvent('download');await click('export');await(await wait).saveAs(file);assert.equal(JSON.parse(fs.readFileSync(file)).teamAlias,'Hosted-Synthetic')});
await test('Hosted actual import as copy',async()=>{await click('sessions');const wait=p.waitForEvent('filechooser');await click('import');await(await wait).setFiles(file);await p.getByText('Review imported progress',{exact:true}).waitFor();await click('import-copies');assert.equal(await p.evaluate(()=>SNApp.store.ids().length),2);assert.equal(await p.evaluate(()=>SNApp.state.imported),true)});
await test('Hosted print preview and selected output',async()=>{await click('print-menu');await p.locator('[data-action="preview-print"][data-mode="build"]').click();assert.match(await p.locator('dialog').innerText(),/Physical model/);await p.evaluate(()=>window.print=()=>window.printCalled=true);await click('print-now');assert.equal(await p.evaluate(()=>window.printCalled),true);await p.pdf({path:path.join(output,'hosted-build-Letter.pdf'),format:'Letter',printBackground:true});assert.match(await p.locator('#print-root').innerText(),/A WILLIAM MCADA PRODUCT/)});
await test('Hosted diagnostics and no unexpected runtime requests',async()=>{assert((await p.evaluate(()=>SN.diagnostics())).every(x=>x.passed));assert(requests.every(u=>u.startsWith(url)||u.startsWith('blob:')));assert.deepEqual(errors,[])});
for(const slug of ['road-trip-planner','food-truck-business-launch'])await test('Existing live route '+slug,async()=>{const r=await ctx.request.get('https://williammcada.github.io/Applied-Math-Projects/'+slug+'/');assert.equal(r.status(),200)});
}catch(e){checks.push({name:'Hosted step',passed:false,error:e.message});console.error(e.stack)}finally{await b.close();const report={url,checkedAt:new Date().toISOString(),environment:'Headless Chromium 153.0.8010.0; public HTTPS Pages through environment proxy; test browser ignores proxy certificate errors; fresh context with synthetic aliases',sha256:hash,passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks};fs.writeFileSync(path.join(__dirname,'hosted-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,failed:report.failed}));if(report.failed)process.exitCode=1}})();
