const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),C=require('../src/core.js'),{science,filled,answers}=require('./v2-fixtures.cjs');const out=process.env.SN_ARTIFACT_DIR||'/tmp/pot-v02-qa';fs.mkdirSync(out,{recursive:true});const results=[];async function test(name,fn){await fn();results.push({name,passed:true});console.log('PASS '+name)}
(async()=>{const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(path.join(__dirname,'../index.html')))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,executablePath:process.env.SN_CHROMIUM_PATH||'/workspace/scratch/68a72e15c634/qa-chromium',args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote','--single-process']});try{const ctx=await browser.newContext({viewport:{width:1180,height:850}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);const click=async(a,extra='')=>p.locator(`[data-action="${a}"]${extra}`).first().click();
await test('dashboard renders and keyboard Science entry',async()=>{assert.match(await p.title(),/v0.2.0/);await p.locator('[data-lesson="science"]').first().focus();await p.keyboard.press('Enter');assert.match(await p.locator('h2').first().innerText(),/Science/);});
for(const t of ['A','B']){
 await p.evaluate(()=>SNApp.setState(SN.newSession()));await click('lesson','[data-lesson="science"]');await p.locator('#meta-teamAlias').fill('UI-'+t);await p.locator('#meta-student1').fill('Alpha');await p.locator('#meta-student2').fill('Beta');await click('track',`[data-track="${t}"]`);
 for(const [k,v]of Object.entries(science(C,t).science[t])){const l=p.locator(`[data-science="${k}"]`);if(!await l.count())continue;if(await l.evaluate(x=>x.tagName)==='SELECT')await l.selectOption(v);else await l.fill(v);}
 await click('science-step','[data-step="2"]');await p.locator('[data-meta="built"]').check();await click('science-step','[data-step="3"]');for(const [k,v]of Object.entries(answers['C09'+t])){const l=p.locator(`[data-input="C09${t}.${k}"]`);if(!await l.count())continue;if(await l.evaluate(x=>x.tagName)==='SELECT')await l.selectOption(v);else await l.fill(v);}for(const k of ['preserved','omitted','other','peer'])await p.locator(`[data-science="${k}"]`).fill(science(C,t).science[t][k]);await click('confirm-measurements');await click('science-step','[data-step="4"]');
 await test(t+' Science completed through UI without math',async()=>{assert.deepEqual(await p.evaluate(()=>SN.scienceErrors(SNApp.state)),{});assert.equal(await p.evaluate(()=>Object.keys(SNApp.state.checkpoints).length),0);});
 const exportFile=path.join(out,'science-'+t+'.json');await test(t+' actual export and test saved copy',async()=>{const wait=p.waitForEvent('download');await click('export');await(await wait).saveAs(exportFile);const chooser=p.waitForEvent('filechooser');await click('test-copy');await(await chooser).setFiles(exportFile);await p.getByRole('heading',{name:'Saved copy matched'}).waitFor();await click('close');assert(await p.evaluate(()=>SNApp.state.handoff.verified.fingerprint===SN.handoffFingerprint(SNApp.state)));});
 await test(t+' fresh browser context imports matching handoff',async()=>{const c2=await browser.newContext(),p2=await c2.newPage();await p2.goto(url);const fc=p2.waitForEvent('filechooser');await p2.locator('[data-action="import"]').first().click();await(await fc).setFiles(exportFile);await p2.locator('[data-action="import-copies"]').click();const received=await p2.evaluate(()=>SN.scienceSnapshot(SNApp.state));assert.deepEqual(received,C.scienceSnapshot(JSON.parse(fs.readFileSync(exportFile))));await p2.locator('[data-lesson="math"]').first().click();assert.equal(await p2.evaluate(()=>SNApp.state.currentStage),2);/* Single-process test Chromium cannot close a secondary context safely. */});
 await test(t+' all math screens and full outcome',async()=>{await p.evaluate(state=>SNApp.setState(state),filled(C,t));for(const n of [2,3,4,6,7,8]){await click('math-stage',`[data-stage="${n}"]`);assert(await p.locator('main').isVisible());}assert.equal(await p.evaluate(()=>SN.outcome(SNApp.state)),'Exhibit ready for review');});
 await test(t+' bounded passport A4 and Letter',async()=>{const s=science(C,t);for(const k of ['prediction','preserved','omitted','other','peer'])s.science[t][k]=('Long science response with measured evidence. ').repeat(8).slice(0,C.scienceLimits[k]);s.teamAlias='T'.repeat(64);s.students=['A'.repeat(64),'B'.repeat(64)];s.science[t].label='L'.repeat(40);s.inputs['C09'+t+'.tool']='R'.repeat(60);await p.evaluate(state=>{SNApp.setState(state);document.querySelector('#print-root').innerHTML=SNApp.printHTML('passport')},s);for(const format of ['A4','Letter'])await p.pdf({path:path.join(out,`passport-${t}-${format}.pdf`),format,printBackground:false});});
}
await test('paper recovery has provenance, no invented approvals',async()=>{await click('lesson','[data-lesson="dashboard"]');await click('paper');assert.equal(await p.evaluate(()=>SNApp.state.science.A.route),'paper');assert.equal(await p.evaluate(()=>SNApp.state.reviews.length),0);assert.match(await p.locator('main').innerText(),/do not need to rebuild/);});
await test('iPad-sized layout without horizontal overflow',async()=>{await p.setViewportSize({width:768,height:1024});await p.evaluate(state=>{state.lesson='science';state.scienceStep=4;SNApp.setState(state)},science(C,'B'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(out,'science-ipad.png'),fullPage:true});});
await test('phone layout',async()=>{await p.setViewportSize({width:390,height:844});await click('science-step','[data-step="1"]');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
await test('teacher guides printable',async()=>{await p.setViewportSize({width:1180,height:850});for(const mode of ['science-guide','coordination']){await p.evaluate(mode=>document.querySelector('#print-root').innerHTML=SNApp.printHTML(mode),mode);await p.pdf({path:path.join(out,mode+'.pdf'),format:'Letter'});}await click('guides');assert.match(await p.locator('dialog').innerText(),/Mathematics/);await click('close');});
await test('blank optional method UI does not gate final',async()=>{await p.evaluate(()=>{const s=SN.newSession();s.lesson='math';s.currentStage=3;SNApp.setState(s)});for(const [k,v]of Object.entries({a:'2',n:'-4',unit:'m'})){const l=p.locator(`[data-input="C04a.${k}"]`);if(k==='unit')await l.selectOption(v);else await l.fill(v);}await click('check','[data-group="C04a"]');assert.equal(await p.evaluate(()=>SN.status(SNApp.state,'C04a')),'checked');});
await test('no JavaScript page errors',async()=>assert.deepEqual(errors,[]));fs.writeFileSync(path.join(__dirname,'v2-browser-results.json'),JSON.stringify({at:new Date().toISOString(),results,limitations:'Chromium desktop/viewport emulation only; no physical iPad or classroom timing.'},null,2));}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
