const assert=require('node:assert/strict'),fs=require('fs'),C=require('../src/core.js'),{science,filled,answers}=require('./v2-fixtures.cjs');const results=[];function test(name,fn){fn();results.push({name,passed:true});}
for(const t of ['A','B']){
 test(t+' science independent of math',()=>{const s=science(C,t);assert.deepEqual(C.scienceErrors(s),{});assert.equal(Object.keys(s.checkpoints).length,0);assert.equal(C.reviewState(s,'inspection'),'pending');});
 test(t+' all retained math + observed scale',()=>{const s=filled(C,t);assert.equal(C.outcome(s),'Exhibit ready for review');C.review(s,'inspection','Tester','teacher','accepted','Synthetic fixture only');C.review(s,'interpretation','Tester','teacher','accepted','Synthetic fixture only');assert.equal(C.outcome(s),'Featured exhibit');assert.deepEqual(C.validateSession(s).inputs,s.inputs);});
 test(t+' export verification and edit invalidation',()=>{const s=science(C,t);s.handoff.exported={fingerprint:C.handoffFingerprint(s),revision:s.localRevision,at:C.now()};const copy=C.parseImport(JSON.stringify(s))[0];C.verifyCopy(s,copy);assert.equal(s.handoff.verified.fingerprint,C.handoffFingerprint(s));s.science[t].preserved+=' Changed';assert.notEqual(s.handoff.verified.fingerprint,C.handoffFingerprint(s));assert.throws(()=>C.verifyCopy(s,copy));});
 test(t+' stale dependency and fixed arithmetic retained',()=>{const s=filled(C,t);s.inputs['C09'+t+'.'+(t==='A'?'cell':'centers')]='159';assert.equal(C.status(s,'C09'+t),'needs-recheck');assert.equal(C.status(s,'C13'+t),'needs-recheck');assert.equal(C.status(s,'C11'+t),'needs-recheck');assert.equal(C.status(s,'C04a'),'checked');assert.equal(C.status(s,'C08'+t),'checked');});
 test(t+' rebuilt model requires confirmation',()=>{const s=science(C,t);s.buildRevisions[t]++;assert(C.scienceErrors(s).measure);});
}
test('cell 159 exact observed scale and deviation',()=>{const s=science(C);s.inputs['C09A.cell']='15.9';s.inputs['C09A.cellUnit']='cm';s.inputs['C09A.cellDeviation']='-1';s.inputs['C13A.cell']='19875:1';assert.deepEqual(C.evaluate(s,'C09A'),{});assert.deepEqual(C.evaluate(s,'C13A'),{});s.inputs['C13A.cell']='20000';assert(C.evaluate(s,'C13A').cell);});
test('cosmic center 598 mm and rounding',()=>{const s=filled(C,'B');s.inputs['C09B.centers']='598';s.inputs['C09B.centersDeviation']='-2';s.inputs['C13B.centers']='299/192000000000';assert.deepEqual(C.evaluate(s,'C13B'),{});assert(C.observed(s,'B','moon').eq('11/7000000000'));assert(!C.observed(s,'B','moon').eq('1/640000000'));});
test('fit boundaries and poor model honest science',()=>{for(const [t,id,lo,hi]of [['A','cell','158','162'],['B','earth','19','21'],['B','moon','4.5','6.5'],['B','centers','595','605']]){const s=science(C,t);for(const x of [lo,hi]){s.inputs['C09'+t+'.'+id]=x;assert(C.fit(s));}s.inputs['C09'+t+'.'+id]=String(Number(hi)+0.01);assert(!C.fit(s));assert.deepEqual(C.scienceErrors(s),{});}});
test('all 8 final-only operations pass; methods separately checked',()=>{for(const o of C.ops){const s=C.newSession();for(const f of ['a','n','unit'])C.setInput(s,o.id+'.'+f,String(answers[o.id][f]));assert.deepEqual(C.check(s,o.id),{});assert.equal(C.methodErrors(s,o.id),null);const f=C.getGroup(s,o.id).fields.find(f=>!['a','n','unit'].includes(f.id));C.setInput(s,o.id+'.'+f.id,'999');assert(Object.keys(C.methodErrors(s,o.id)).length);assert.deepEqual(C.check(s,o.id),{});}});
test('exact final arithmetic still rejects tiny zero',()=>{const s=filled(C);s.inputs['C04a.a']='0';assert(C.evaluate(s,'C04a').a);});
test('valid full optional methods pass',()=>{const s=filled(C);for(const o of C.ops)assert.deepEqual(C.methodErrors(s,o.id),{});});
test('legacy copied with full original and historical reviews',()=>{const raw=JSON.parse(fs.readFileSync(__dirname+'/saved-fixtures/featured-cell.json'));const s=C.validateSession(raw);assert.notEqual(s.sessionId,raw.sessionId);assert.equal(s.duplicateOf,raw.sessionId);assert.deepEqual(s.legacy,raw);assert.equal(s.schemaVersion,'2.0.0');assert.equal(C.reviewState(s,'inspection'),'pending');assert(Object.keys(C.scienceErrors(s)).length);assert.deepEqual(C.validateSession(s).legacy,raw);});
test('bundles, malformed and unsupported records',()=>{const a=science(C),b=science(C,'B');assert.equal(C.parseImport(JSON.stringify(C.bundle([a,b]))).length,2);for(const patch of [{schemaVersion:'99'},{science:{A:{},B:{}}},{lesson:'wrong'},{handoff:{exported:{},verified:null}}])assert.throws(()=>C.validateSession({...a,...patch}));assert.throws(()=>C.parseImport('{'));assert.throws(()=>C.parseImport(JSON.stringify({...C.bundle([a,b]),sessions:[a,a]})));});
class Memory{constructor(){this.m=new Map()}get length(){return this.m.size}key(i){return [...this.m.keys()][i]}getItem(k){return this.m.get(k)??null}setItem(k,v){this.m.set(k,v)}removeItem(k){this.m.delete(k)}}
test('migration never overwrites original storage',()=>{const m=new Memory(),db=new C.Store(m),raw=JSON.parse(fs.readFileSync(__dirname+'/saved-fixtures/featured-cell.json')),key=C.PREFIX+'session:'+raw.sessionId;m.setItem(key,JSON.stringify(raw));const s=db.read(raw.sessionId);db.save(s);assert.equal(m.getItem(key),JSON.stringify(raw));assert.equal(db.ids().length,2);});
test('storage conflict, scoped deletion and corrupted storage',()=>{const m=new Memory(),db=new C.Store(m),s=science(C);db.save(s);const stale=C.clone(s);db.save(s);assert.throws(()=>db.save(stale),/CONFLICT/);m.setItem('other-app','safe');m.setItem(C.PREFIX+'session:bad','{');assert(db.list().some(x=>x.error));db.remove(db.ids());assert.equal(m.getItem('other-app'),'safe');});
test('blocked storage retains exportable state',()=>{const db=new C.Store({setItem(){throw Error('denied')}}),s=science(C);assert(!db.available);assert.throws(()=>db.save(s));assert.deepEqual(C.parseImport(JSON.stringify(s))[0].inputs,s.inputs);});
fs.writeFileSync(__dirname+'/v2-core-results.json',JSON.stringify({at:new Date().toISOString(),results},null,2));console.log(results.length+' passed');
