const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{answers,completed}=require('./core.test.cjs');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/verification');fs.mkdirSync(out,{recursive:true});const checks=[],ok=(v,n)=>{assert.ok(v,n);checks.push(n)};
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.setOffline(true);const p=await context.newPage(),exceptions=[],net=[];p.on('pageerror',e=>exceptions.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))net.push(r.url())});
const click=async a=>p.locator('[data-action="'+a+'"]').first().click(),fill=async values=>{for(const[k,v]of Object.entries(values)){let el=p.locator('[data-field="'+k+'"]');if(await el.count()!==1||!await el.isVisible())continue;const tag=await el.evaluate(e=>e.tagName);if(tag==='SELECT')await el.selectOption(v);else await el.fill(v);}},stage=async n=>ok(await p.locator('.stage-nav .active').getAttribute('data-stage')===String(n),'At stage '+n+' '+(await p.locator('#errors').allTextContents()).join());
const newPlan=async()=>{await click('new');await p.locator('#meta-teamAlias').fill('Red Horizon QA');await p.locator('#meta-learnerA').fill('Orion');await p.locator('#meta-learnerB').fill('Lyra');await p.locator('[data-meta="brief"]').check();await click('next');};
try{
await p.goto('file://'+root+'/index.html');await p.screenshot({path:path.join(out,'home.png'),fullPage:true});await newPlan();await stage(2);await fill({...answers(),daily_oxygen:'0.8'});await click('next');await stage(2);ok((await p.locator('#errors').textContent()).includes('oxygen'),'Incorrect per-person value blocked');ok((await p.locator('#f-daily_water').locator('..').textContent()).includes('Checked'),'Correct sibling retained');await p.locator('[data-action="help"][data-key="daily_oxygen"]').click();ok((await p.locator('#dialog').textContent()).includes('Five people'),'Help uses different numbers');await p.keyboard.press('Escape');ok(await p.locator('[data-help]').count()===0,'Help closed');await fill({daily_oxygen:'19.2'});await click('next');await stage(3);
for(const [k,v]of Object.entries({o:3,w:3,h:3,a:4,b:1}))await p.locator('[data-config="'+k+'"]').selectOption(String(v));await fill(answers());await click('next');await stage(4);await fill(answers());await click('next');await stage(5);await fill(answers());await click('next');await stage(6);await fill(answers());await click('next');await stage(7);await fill(answers());await click('next');await stage(8);ok((await p.locator('#main').textContent()).includes('Resilient outpost'),'Full pair journey reaches resilient ending');await fill(answers());await click('finish');ok(await p.locator('#errors').count()===0,'Digital transfers complete');
await click('save');const saved=await p.evaluate(()=>JSON.parse(Object.values(localStorage).find(x=>x.includes('Red Horizon QA')&&x.includes('mcada-project-progress'))));ok(saved.attempts.filter(a=>a.key==='daily_oxygen').map(a=>a.passed).join(',')==='false,true','First mistake preserved');ok(saved.lessonSwaps.join(',')==='1,2','Role swaps at two lesson boundaries');ok(saved.initialPlan.cfg.a===4,'Initial configuration snapshot preserved');
const downloadWait=p.waitForEvent('download');await click('export');const download=await downloadWait;await download.saveAs(path.join(out,'completed-session.json'));ok(JSON.parse(fs.readFileSync(path.join(out,'completed-session.json'))).currentStage===8,'Actual export contains completed stage');
await p.reload();await click('sessions');await click('resume');await stage(8);ok((await p.locator('#main').textContent()).includes('Resilient outpost'),'Reload resume retains outcome');await p.screenshot({path:path.join(out,'mission-control.png'),fullPage:true});
await click('report');ok((await p.locator('#dialog').textContent()).includes('First checked response'),'Report distinguishes first responses');for(const format of ['A4','Letter'])await p.pdf({path:path.join(out,'student-'+format+'.pdf'),format,printBackground:true});await click('close');await click('teacher');await click('teacherPrint');for(const format of ['A4','Letter'])await p.pdf({path:path.join(out,'teacher-'+format+'.pdf'),format,printBackground:true});await click('close');await click('slips');ok(!(await p.locator('#print-root').textContent()).includes('900'),'Transfer slips omit answers');await p.pdf({path:path.join(out,'transfer-A4.pdf'),format:'A4',printBackground:true});await click('close');await click('patch');await p.pdf({path:path.join(out,'patch-A4.pdf'),format:'A4',printBackground:true});await click('close');
for(const [w,h]of [[768,1024],[1024,768],[1440,1000]]){await p.setViewportSize({width:w,height:h});for(const n of [2,3,5,7,8]){await p.locator('[data-stage="'+n+'"]').click();ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow '+w+' stage '+n);}await p.screenshot({path:path.join(out,'layout-'+w+'.png'),fullPage:true});}await p.setViewportSize({width:1440,height:1000});
await p.locator('[data-stage="7"]').click();await p.locator('summary').click();await p.locator('[data-config="pack"]').selectOption('lean');ok((await p.locator('#main').textContent()).includes('Needs recheck'),'Crate change marks dependent comparison stale');await p.locator('[data-stage="5"]').click();ok(!(await p.locator('#group-C05').textContent()).includes('Needs recheck'),'Lean retains water model');await p.locator('[data-stage="4"]').click();await fill(answers({o:3,w:3,h:3,a:4,b:1,pack:'lean'}));await click('next');await stage(5);await click('next');await stage(6);await click('next');await stage(7);await fill(answers({o:3,w:3,h:3,a:4,b:1,pack:'lean'}));await click('next');await stage(8);ok((await p.locator('#main').textContent()).includes('Mission ready'),'Lean revised path reaches ready');
// Import complete synthetic fixtures through the actual chooser/preview.
async function importFixture(s,name){const f=path.join(out,name+'.json');fs.writeFileSync(f,JSON.stringify(s));await click('sessions');const chooser=p.waitForEvent('filechooser');await click('import');await(await chooser).setFiles(f);await p.getByRole('heading',{name:'Review import',exact:true}).waitFor();await click('importCopies');}
await importFixture(completed({o:3,w:3,h:3,a:5,b:0,pack:'standard'}),'extra-solar');ok((await p.locator('#main').textContent()).includes('5 arrays and 0 batteries'),'Solar ending copy matches plan');
await importFixture(completed({o:3,w:3,h:3,a:4,b:0,pack:'standard'}),'delayed');ok((await p.locator('#main').textContent()).includes('Deployment delayed'),'Correct weak fixture reaches delayed');ok((await p.locator('#main').textContent()).includes('day 4: 6 kWh unserved'),'Failure identifies exact day and shortage');
await click('sessions');const before=await p.locator('[data-action="resume"]').count();await click('delete');await p.locator('[data-action="close"]').filter({hasText:'Cancel'}).click();await click('sessions');ok(await p.locator('[data-action="resume"]').count()===before,'Deletion cancellation preserves records');
const backupWait=p.waitForEvent('download');await click('backup');const backup=await backupWait;await backup.saveAs(path.join(out,'backup.json'));ok(JSON.parse(fs.readFileSync(path.join(out,'backup.json'))).sessions.length===before,'Backup contains all sessions');await p.evaluate(()=>localStorage.setItem('mcada:road-trip:session:sentinel','keep'));await click('clearAll');await click('confirmDelete');ok(await p.locator('[data-action="resume"]').count()===0,'Clear-all removes Mars');ok(await p.evaluate(()=>localStorage.getItem('mcada:road-trip:session:sentinel'))==='keep','Other app untouched');await p.reload();await click('sessions');ok(await p.locator('[data-action="resume"]').count()===0,'Deletion persists after reload');const chooser=p.waitForEvent('filechooser');await click('import');await(await chooser).setFiles(path.join(out,'backup.json'));await p.getByRole('heading',{name:'Review import',exact:true}).waitFor();await click('importCopies');await click('sessions');ok(await p.locator('[data-action="resume"]').count()===before,'Backup recovery restores sessions');await click('close');
// Wrong import fails atomically.
await click('save');const countBefore=await p.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('mcada:mars-colony:session:')).length);const bad=completed();bad.projectId='other';fs.writeFileSync(path.join(out,'invalid-import.json'),JSON.stringify(bad));await click('sessions');const badChooser=p.waitForEvent('filechooser');await click('import');await(await badChooser).setFiles(path.join(out,'invalid-import.json'));await p.getByRole('heading',{name:'Import not completed'}).waitFor();ok(await p.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('mcada:mars-colony:session:')).length)===countBefore,'Invalid import changes no sessions');await click('close');
for(const [n,gs]of [[2,['C01','C02']],[3,['C03','C04']],[4,['C08']],[5,['C05']],[6,['C06']],[7,['C07','C09']],[8,['C10']]]){await p.locator('[data-stage="'+n+'"]').click();for(const g of gs){await p.locator('#group-'+g+' > .group-head [data-action="help"]').click();ok(await p.locator('#dialog h3').count()===3,'Complete help '+g);await p.keyboard.press('Escape');}}
await click('teacher');await click('diagnostics');ok(!(await p.locator('#dialog').textContent()).includes('Failed'),'Built-in diagnostics pass');await click('close');
ok(exceptions.length===0,'No uncaught browser exceptions: '+exceptions.join(';'));ok(net.length===0,'No external runtime requests');fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({passed:checks.length,checks,exceptions,net,environment:'Linux Chromium local standalone HTML in offline context',browser:await browser.version()},null,2));console.log(checks.length+' browser assertions passed.');
}catch(e){await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.txt'),(await p.locator('body').innerText())+'\n'+e.stack);throw e;}finally{await browser.close();}
})();
