const C=require('../src/core.js'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
let checks=[];const ok=(v,n)=>{assert.ok(v,n);checks.push(n)},eq=(a,b,n)=>{assert.deepEqual(a,b,n);checks.push(n)};
function reference(c={o:3,w:3,h:3,a:4,b:1,pack:'standard'}){const f=c.pack==='lean'?1584:1728,cost=2000*c.o+1500*c.w+3000*c.h+1000*c.a+800*c.b+(c.pack==='lean'?800:1000),mass10=2000*c.o+1500*c.w+4000*c.h+1000*c.a+800*c.b+1440+384+f+1000,load=24+12*c.o+8*c.w+10*c.h;let stocks=[1440,384,f],battery=36*c.b;const days=[{stock:stocks.map(x=>x/10),battery}],production=[300*c.w,80*c.o,0],demand=[720,192,144],caps=[4000,1000,2000];
for(let t=1;t<=10;t++){const r=stocks.map((v,i)=>{const balance=v+production[i]-demand[i];return {stock:Math.max(0,Math.min(caps[i],balance))/10,unmet:Math.max(0,-balance)/10,discarded:Math.max(0,balance-caps[i])/10}});stocks=r.map(x=>Math.round(x.stock*10));const gen=c.a*(t>=4&&t<=6?27:36),start=battery,raw=battery+gen-load;battery=Math.max(0,Math.min(36*c.b,raw));days.push({stock:r.map(x=>x.stock),r,battery,start,unserved:Math.max(0,-raw),curtailed:Math.max(0,raw-36*c.b)});}
const ready=c.o>=3&&c.w>=3&&c.h>=3&&cost<=26000&&mass10<=34000&&days.slice(1).every(d=>d.unserved===0&&d.r.every(r=>r.unmet===0));return {days,cost,mass:mass10/10,load,ending:ready?(c.pack==='lean'?'Mission ready':'Resilient outpost'):'Deployment delayed'};}
function answers(c={o:3,w:3,h:3,a:4,b:1,pack:'standard'},resource='water'){
const r=reference(c),idx={water:0,oxygen:1,food:2}[resource],initial=[144,38.4,c.pack==='lean'?158.4:172.8][idx],prod=[30*c.w,8*c.o,0][idx],demand=[72,19.2,14.4][idx],net=(Math.round(prod*10)-Math.round(demand*10))/10,cap=[400,100,200][idx],boundary=r.days.slice(1).findIndex(d=>d.r[idx].stock===cap||d.r[idx].unmet||d.r[idx].discarded),a={};
for(const [k,v]of Object.entries({water:72,oxygen:19.2,food:14.4})){a['daily_'+k]=String(v);a['total_'+k]=String(Math.round(v*10));}
for(const [k,v]of [['L','stock'],['L_day','rate'],['kg','stock'],['kg_day','rate'],['kWh','stock'],['kWh_day','rate']])a['unit_'+k]=v;
Object.assign(a,{convert_oxygen:'800',convert_water:'3000',convert_group:'19.2',ratio_water:'2.4',min_water:'3',enough_water:'90',fewer_water:'60',why_water:'capacity',ratio_oxygen:'2.4',min_oxygen:'3',enough_oxygen:'24',fewer_oxygen:'16',why_oxygen:'capacity',min_h:'3',places:String(8*c.h),area:String(24*c.h),perPerson:String(c.h),occupancyMet:c.h>=3?'yes':'no',areaMet:c.h>=3?'yes':'no',stock_initial:String(initial),stock_production:String(prod),stock_consumption:String(demand),stock_net:String(net),stock_rule:`${initial}+(${net})t`,stock_meaning:'until',boundary:boundary<0?'none':String(boundary+1),axisX:'days',axisY:resource});
for(let t=0;t<=10;t++){a['stock_day'+t]=String(r.days[t].stock[idx]);if(t){a['unmet_day'+t]=String(r.days[t].r[idx].unmet);a['discarded_day'+t]=String(r.days[t].r[idx].discarded);}}
for(const t of [0,1,3,6,10]){a['pointX'+t]=String(t);a['pointY'+t]=String(r.days[t].stock[idx]);}if(boundary>=0){a.boundaryX=String(boundary+1);a.boundaryY=String(r.days[boundary+1].stock[idx]);}
Object.assign(a,{energy_fixed:'24',energy_oxygen:String(12*c.o),energy_water:String(8*c.w),energy_habitat:String(10*c.h),energy_total:String(r.load),energy_normal:String(36*c.a),energy_storm:String(27*c.a),energy_normalBalance:String(36*c.a-r.load),energy_stormBalance:String(27*c.a-r.load),remaining:'75',perArray:'27',batteryCap:String(36*c.b),batteryInitial:String(36*c.b),stormDeficit:String(3*Math.max(0,r.load-27*c.a)),allCovered:r.days.slice(1).every(d=>d.unserved===0)?'yes':'no'});
for(let t=1;t<=10;t++)for(const k of ['start','battery','unserved','curtailed'])a[k+'_day'+t]=String(r.days[t][k]);
for(const [k,mass,cost]of [['o',200,2000],['w',150,1500],['h',400,3000],['a',100,1000],['b',80,800]]){a['mass_'+k]=String(c[k]*mass);a['cost_'+k]=String(c[k]*cost);}
Object.assign(a,{packMass:c.pack==='lean'?'440.8':'455.2',packCost:c.pack==='lean'?'800':'1000',totalMass:String(r.mass),totalCost:String(r.cost),cargoReserve:String((34000-Math.round(r.mass*10))/10),budgetReserve:String(26000-r.cost),cargoMet:r.mass<=3400?'yes':'no',budgetMet:r.cost<=26000?'yes':'no'});
for(const [name,p]of [['A',reference({o:3,w:3,h:3,a:4,b:1,pack:c.pack})],['B',reference({o:3,w:3,h:3,a:5,b:0,pack:c.pack})]])for(const [k,v]of Object.entries({normal:name==='A'?144:180,storm:name==='A'?108:135,load:114,battery:name==='A'?18:0,cost:p.cost,mass:p.mass,food:c.pack==='lean'?1:2}))a['compare'+name+'_'+k]=String(v);
Object.assign(a,{compareCost:'200',compareMass:'20',recommend:'A',metric:'cost',evidenceValue:'200',reason:'Strategy A costs 200 credits less.',limitation:'Daily balances do not show nighttime electricity.',revisionReason:'I considered both strategies and retained this configuration.',transferModeA:'digital',transferModeB:'digital',transferA_daily:'90',transferA_total:'900',transferA_ratio:'3',transferA_count:'3',transferA_reason:'Three modules provide 90 liters per day.',transferB_daily:'22.4',transferB_total:'224',transferB_ratio:'2.8',transferB_count:'3',transferB_reason:'Two supply only 16 kilograms; three supply 24.'});return a;
}
function completed(c,resource='water'){const s=C.newSession();s.teamAlias='Synthetic QA';s.learnerA='A';s.learnerB='B';s.brief=true;s.cfg=c||{o:3,w:3,h:3,a:4,b:1,pack:'standard'};s.resource=resource;s.inputs={...s.inputs,...answers(s.cfg,resource)};for(const g of Object.keys(C.labels)){const e=C.check(s,g);assert.deepEqual(e,[],g+JSON.stringify(e));}s.currentStage=8;s.maxStage=8;s.initialPlan={cfg:C.clone(s.cfg),resource,at:C.now()};return s;}
function main(){for(const f of require('./reference-cases-v0.1.0.json').fixtures){const m=C.model(f.cfg);for(const [key,value]of Object.entries(f.expected))eq(key.split('.').reduce((o,k)=>o[k],m),value,f.id+' '+key);}for(const e of C.diagnostics())ok(e.passed,e.name);for(const [raw,n]of [['19.2',19.2],['96/5',19.2],['−6',-6],['3,185.2',3185.2],['18/6',3]])ok(C.numeric(raw).eq(n),'numeric '+raw);
for(const raw of ['', '1,2','NaN','Infinity','1/0','1e309','<script>','t*t','z+1','9999999999999999999'])assert.throws(()=>C.numeric(raw),raw),checks.push('Reject '+raw);
for(const raw of ['144+18t','18*t+144','144+(90-72)t','18(t+8)','(288+36t)/2'])ok(C.linear(raw).m.eq(18)&&C.linear(raw).b.eq(144),'Equivalent '+raw);
const cases=[[3,3,3,4,1,'standard'],[3,3,3,5,0,'standard'],[3,3,3,4,1,'lean'],[3,3,3,5,0,'lean'],[3,3,3,4,2,'lean'],[3,3,3,4,0,'standard'],[3,3,3,3,0,'standard'],[3,3,2,4,1,'standard'],[3,2,3,4,1,'standard'],[3,4,3,5,0,'standard'],[0,0,3,4,1,'standard']];
for(const arr of cases){const c=Object.fromEntries(['o','w','h','a','b','pack'].map((k,i)=>[k,arr[i]])),ref=reference(c),m=C.model(c);eq([m.cost,m.mass,m.load,m.ending],[ref.cost,ref.mass,ref.load,ref.ending],'Fixture '+arr);for(let t=0;t<=10;t++)eq([Object.values(m.days[t].stocks),m.days[t].battery],[ref.days[t].stock,ref.days[t].battery],'Daily '+arr+' '+t);}
let counts={'Resilient outpost':0,'Mission ready':0,'Deployment delayed':0};for(let o=0;o<=6;o++)for(let w=0;w<=6;w++)for(let h=0;h<=6;h++)for(let a=0;a<=8;a++)for(let b=0;b<=4;b++)for(const pack of ['standard','lean']){const c={o,w,h,a,b,pack},m=C.model(c);assert.equal(m.ending,reference(c).ending);counts[m.ending]++;}eq(counts,{'Resilient outpost':2,'Mission ready':3,'Deployment delayed':30865},'All 30870 configurations agree with independent oracle');
for(const resource of ['water','oxygen','food']){const s=completed(undefined,resource);eq(C.outcome(s).title,'Resilient outpost','All fields valid '+resource);eq(C.outcome(C.parseImport(JSON.stringify(s))[0]).title,'Resilient outpost','Roundtrip '+resource);}
let s=completed();C.setConfig(s,'a',5);ok(C.groupOK(s,'C01')&&C.groupOK(s,'C05')&&C.groupOK(s,'C04'),'Solar preserves demand/resources/housing');ok(!C.groupOK(s,'C06')&&!C.groupOK(s,'C07')&&!C.groupOK(s,'C08'),'Solar invalidates power battery manifest');eq(C.outcome(s).code,'draft','Stale final report');
s=completed();C.setConfig(s,'pack','lean');ok(C.groupOK(s,'C05')&&C.groupOK(s,'C06'),'Lean preserves water and energy');ok(!C.groupOK(s,'C08')&&!C.groupOK(s,'C09'),'Lean invalidates manifest/comparison');
s=completed();C.setRaw(s,'daily_water','3');let errs=C.check(s,'C01');ok(errs.some(e=>e.key==='daily_water'),'Wrong per-person total blocked');C.setRaw(s,'daily_water','72');C.check(s,'C01');eq(s.attempts.filter(a=>a.key==='daily_water').map(a=>a.passed),[true,false,true],'History preserves corrections');
s=completed();C.setRaw(s,'stock_rule','144+17t');ok(!!C.evaluate(s,'stock_rule',s.inputs.stock_rule),'Correct total cannot replace wrong rule');C.bypass(s,'C05','Teacher','Test inaccessible field');eq(C.outcome(s).code,'provisional','Active bypass provisional');
s=completed();s.inputs.transferModeA='paper';ok(!C.keys(s,'C10').includes('transferA_daily'),'Paper excludes automatic marking');eq(C.reviewStatus(s,'transferModeA'),'pending','Paper pending');C.review(s,'transferModeA','Teacher','Paper checked','verified');eq(C.reviewStatus(s,'transferModeA'),'verified','Paper reviewed');
for(const mutate of [s=>s.projectId='food-truck',s=>s.schemaVersion='9.0.0',s=>s.cfg.a=99,s=>s.cfg.w=-1,s=>s.attempts[0].key='missing',s=>s.teamAlias='<script>alert(1)</script>',s=>s.extra='x',s=>s.revisions=[{before:{},key:'a',value:1,at:C.now()}]]){let copy=completed();mutate(copy);assert.throws(()=>C.parseImport(JSON.stringify(copy)));checks.push('Invalid import rejected');}
s=completed();s.inputs.daily_water='7';ok(!C.groupOK(C.parseImport(JSON.stringify(s))[0],'C01'),'Forged correct status revalidated');s=completed();s.appVersion='0.1.1';eq(C.validateSession(s).appVersion,'0.1.1','Compatible patch save');
class Memory{constructor(){this.map=new Map()}get length(){return this.map.size}key(i){return [...this.map.keys()][i]}getItem(k){return this.map.get(k)??null}setItem(k,v){this.map.set(k,v)}removeItem(k){this.map.delete(k)}}
const memory=new Memory,store=new C.Store(memory);s=completed();store.save(s);const stale=C.clone(s);store.save(s);assert.throws(()=>store.save(stale),/CONFLICT/);checks.push('Concurrent revision refused');memory.setItem('mcada:road-trip:session:sentinel','keep');store.remove([s.sessionId]);eq(store.ids(),[],'Deleted complete session');eq(memory.getItem('mcada:road-trip:session:sentinel'),'keep','Other app retained');store.save(C.newSession());eq(store.ids().length,1,'Fresh session after delete');
const output=path.resolve(__dirname,'../docs/verification');fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'core-results.json'),JSON.stringify({passed:checks.length,configurationComparisons:30870,counts,checks,node:process.version},null,2));console.log(checks.length+' named checks plus 30,870 configuration comparisons passed.');}
if(require.main===module)main();module.exports={answers,completed,reference};
