// In-process integration evidence only. jsdom does not verify layout, real dialogs,
// file downloads, printing, accessibility trees, browser storage or device behavior.
const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {answers,completed}=require('./core.test.cjs'),C=require('../src/core.js');
const root=path.resolve(__dirname,'..'),checks=[],exceptions=[],downloads=[];
const ok=(v,n)=>{assert.ok(v,n);checks.push(n)},html=fs.readFileSync(path.join(root,'index.html'),'utf8');
let pendingFile=null,printCalls=0,dom;
function boot(state={}){const vc=new VirtualConsole();vc.on('jsdomError',e=>exceptions.push(e.message));dom=new JSDOM(html,{runScripts:'dangerously',url:'https://example.test/mars-colony/',virtualConsole:vc,beforeParse(w){
 w.scrollTo=()=>{};w.print=()=>{printCalls++};w.Blob=Blob;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 const blobs=new Map();w.URL.createObjectURL=b=>{const url='blob:mock-'+blobs.size;blobs.set(url,b);return url};w.URL.revokeObjectURL=url=>blobs.delete(url);
 w.HTMLAnchorElement.prototype.click=function(){if(this.download)downloads.push({name:this.download,blob:blobs.get(this.href)});};
 const inputClick=w.HTMLInputElement.prototype.click;w.HTMLInputElement.prototype.click=function(){if(this.type==='file'){assert.ok(pendingFile,'Choose an explicit mock file');const raw=pendingFile;pendingFile=null;Object.defineProperty(this,'files',{value:[{size:Buffer.byteLength(raw),text:async()=>raw}]});this.dispatchEvent(new w.Event('change'));}else inputClick.call(this);};
 for(const[k,v]of Object.entries(state))w.localStorage.setItem(k,v);
 }});}
const $=s=>dom.window.document.querySelector(s),$$=s=>Array.from(dom.window.document.querySelectorAll(s)),settle=async()=>{for(let i=0;i<5;i++)await Promise.resolve();};
async function click(a){const el=$('#dialog[open] [data-action="'+a+'"]')||$('[data-action="'+a+'"]');assert.ok(el,'Button '+a);el.click();await settle();}
async function set(selector,value){const el=$(selector);assert.ok(el,selector);if(el.type==='checkbox')el.checked=!!value;else el.value=String(value);el.dispatchEvent(new dom.window.Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));await settle();}
async function fill(values){for(const[k,v]of Object.entries(values))if($('[data-field="'+k+'"]'))await set('[data-field="'+k+'"]',v);}
async function nav(n){$('[data-stage="'+n+'"]').click();await settle();}
function stage(n){ok($('.stage-nav .active')?.dataset.stage===String(n),'Stage '+n+': '+($('#errors')?.textContent||'no validation errors'));}
const storage=()=>Object.fromEntries(Object.keys(dom.window.localStorage).map(k=>[k,dom.window.localStorage.getItem(k)]));
const saved=()=>Object.values(storage()).map(v=>{try{return JSON.parse(v)}catch{return null}}).filter(v=>v?.schema==='mcada-project-progress');
async function fixture(s){await click('sessions');pendingFile=JSON.stringify(s);await click('import');ok($('#dialog-title').textContent==='Review import','Import preview validates fixture');await click('importCopies');}
(async()=>{boot();try{
 ok($('h1').textContent.includes('A new horizon'),'Home renders');await click('new');await set('#meta-teamAlias','Red Horizon QA');await set('#meta-learnerA','Orion');await set('#meta-learnerB','Lyra');await set('[data-meta="brief"]',true);await click('next');stage(2);
 await fill({...answers(),daily_oxygen:'0.8'});await click('next');stage(2);ok($('#errors').textContent.includes('oxygen'),'Wrong per-person answer blocks stage');ok($('#f-daily_water').parentElement.textContent.includes('Checked'),'Valid sibling retained');
 $('[data-action="help"][data-key="daily_oxygen"]').click();await settle();ok($('#dialog').textContent.includes('Five people'),'Help uses different example values');$('#dialog').dispatchEvent(new dom.window.Event('cancel',{cancelable:true}));ok(!$('#dialog').open,'Cancel closes help dialog');
 await fill({daily_oxygen:'19.2'});await click('next');stage(3);for(const[k,v]of Object.entries({o:3,w:3,h:3,a:4,b:1}))await set('[data-config="'+k+'"]',v);
 for(let n=3;n<=7;n++){await fill(answers());await click('next');stage(n+1);}ok($('#main').textContent.includes('Resilient outpost'),'Complete standard journey earns resilient ending');await fill(answers());await click('finish');ok(!$('#errors'),'Independent digital transfers accepted');await click('save');
 let s=saved().find(s=>s.teamAlias==='Red Horizon QA');ok(s.attempts.filter(a=>a.key==='daily_oxygen').map(a=>a.passed).join(',')==='false,true','Attempt history preserves initial misconception');ok(s.lessonSwaps.join(',')==='1,2','Two lesson role swaps');ok(s.initialPlan.cfg.a===4,'Initial configuration preserved');
 await click('export');const exported=JSON.parse(await downloads.at(-1).blob.text());ok(exported.completedAt&&exported.currentStage===8,'Export handler produces complete portable JSON');
 let state=storage();dom.window.close();boot(state);await click('sessions');await click('resume');stage(8);ok($('#main').textContent.includes('Resilient outpost'),'Save and resume across separate DOM instances');
 await click('report');ok($('#print-root').textContent.includes('First checked response'),'Student report preserves response evidence');ok($('#print-root svg'),'Student report has code-generated SVG');await click('print');ok(printCalls===1,'Print control invokes print handler');await click('close');
 await click('teacher');await click('teacherPrint');ok($('#print-root').textContent.includes('25,300'),'Teacher reference includes fixed baseline');await click('close');await click('slips');ok(!$('#print-root').textContent.includes('900'),'Transfer slips omit worked answers');await click('close');await click('patch');ok($('#print-root svg')&&$('#print-root').textContent.includes('Red Horizon QA'),'Mission patch includes alias and vector art');await click('close');
 await nav(7);await set('[data-config="pack"]','lean');ok($('#group-C09').textContent.includes('Needs recheck'),'Crate change invalidates comparison');await nav(8);ok($('#main').textContent.includes('Draft — finish checks'),'Stale work produces draft');ok(!$('#main').textContent.includes('25,100'),'Draft view hides unchecked total');await click('report');ok(!$('#print-root').textContent.includes('25,100'),'Draft report hides new answer key');await click('close');
 await nav(5);ok(!$('#group-C05').textContent.includes('Needs recheck'),'Crate change retains water calculations');await nav(4);for(let n=4;n<=7;n++){await fill(answers({o:3,w:3,h:3,a:4,b:1,pack:'lean'}));await click('next');stage(n+1);}ok($('#main').textContent.includes('Mission ready'),'Complete lean revision earns ready ending');
 await fixture(completed({o:3,w:3,h:3,a:5,b:0,pack:'standard'}));ok($('#main').textContent.includes('5 arrays and 0 batteries'),'Extra solar ending reflects retained plan');
 await fixture(completed({o:3,w:3,h:3,a:4,b:0,pack:'standard'}));ok($('#main').textContent.includes('Deployment delayed'),'Correct weak design reaches delayed');ok($('#main').textContent.includes('day 4: 6 kWh unserved'),'Delayed explanation names shortage and day');
 await click('sessions');let count=$$('[data-action="resume"]').length;await click('delete');await click('close');await click('sessions');ok($$('[data-action="resume"]').length===count,'Cancel deletion retains sessions');
 await click('backup');const backup=JSON.parse(await downloads.at(-1).blob.text());ok(backup.sessions.length===count,'Backup handler captures all sessions');dom.window.localStorage.setItem('mcada:road-trip:session:sentinel','keep');await click('clearAll');await click('confirmDelete');ok(saved().length===0,'Clear-all deletes Mars work');dom.window.dispatchEvent(new dom.window.Event('beforeunload'));ok(saved().length===0,'Unload does not resurrect deleted session');ok(dom.window.localStorage.getItem('mcada:road-trip:session:sentinel')==='keep','Other project data retained');
 state=storage();dom.window.close();boot(state);await click('sessions');ok($$('[data-action="resume"]').length===0,'Deletion persists through new DOM instance');await fixture(backup);await click('sessions');ok($$('[data-action="resume"]').length===count,'Backup import restores independent copies');await click('close');
 const bad=completed();bad.projectId='other';await click('sessions');const before=JSON.stringify(storage());pendingFile=JSON.stringify(bad);await click('import');ok($('#dialog-title').textContent==='Import not completed','Wrong-project import rejected');ok(JSON.stringify(storage())===before,'Invalid import is atomic');await click('close');
 for(const[n,gs]of [[2,['C01','C02']],[3,['C03','C04']],[4,['C08']],[5,['C05']],[6,['C06']],[7,['C07','C09']],[8,['C10']]]){await nav(n);for(const g of gs){$('#group-'+g+' > .group-head [data-action="help"]').click();await settle();ok($$('#dialog h3').length===3,'Three-part help '+g);await click('close');}}
 await click('teacher');await click('diagnostics');ok(!$('#dialog').textContent.includes('Failed'),'Built-in arithmetic diagnostics pass');await click('close');
 // Review, oral evidence, paper transfer and bypass use the same actual controls.
 await nav(8);await fill({transferModeA:'paper'});await click('teacher');await set('#review-key','transferModeA');await set('#reviewer','Teacher');await set('#review-note','Paper reasoning inspected');await click('review');await click('save');ok(saved().some(s=>s.reviews.some(r=>r.key==='transferModeA'&&r.status==='verified')),'Paper review retained');await set('#review-key','limitation');await set('#reviewer','Teacher');await set('#review-note','Daily accounting does not model nighttime.');await click('oral');ok($('#dialog').textContent.includes('Teacher desk'),'Oral evidence can be recorded');await set('#reviewer','Teacher');await set('#review-note','Demonstrate inaccessible gate bypass');await set('#bypass-group','C10');await click('bypass');await click('close');ok($('#main').textContent.includes('Provisional'),'Transfer bypass makes ending provisional');
 // Concurrent-tab conflict must not overwrite newer data.
 await click('save');s=saved().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];const key=C.PREFIX+'session:'+s.sessionId;s.localRevision+=1;s.teamAlias='Newer tab';dom.window.localStorage.setItem(key,JSON.stringify(s));dom.window.dispatchEvent(new dom.window.StorageEvent('storage',{key,newValue:JSON.stringify(s)}));ok($('#dialog-title').textContent==='Newer work exists','Concurrent revision prompts conflict resolution');await click('conflictCopy');ok(saved().length===count+1,'Conflict creates independent copy');
 // Cross-tab deletion must retain only an export opportunity.
 await click('export');const current=JSON.parse(await downloads.at(-1).blob.text()),activeKey=C.PREFIX+'session:'+current.sessionId;dom.window.localStorage.removeItem(activeKey);dom.window.dispatchEvent(new dom.window.StorageEvent('storage',{key:activeKey,newValue:null}));ok($('#dialog-title').textContent==='Mission removed in another tab','Cross-tab deletion shown');dom.window.dispatchEvent(new dom.window.Event('beforeunload'));ok(!dom.window.localStorage.getItem(activeKey),'Cross-tab deletion never autosaves old record');await click('exportDeleted');ok(JSON.parse(await downloads.at(-1).blob.text()).sessionId===current.sessionId,'Deleted-tab unsaved work can be exported');
 ok(exceptions.length===0,'No uncaught script errors: '+exceptions.join(';'));
 fs.writeFileSync(path.join(root,'docs/verification/dom-results.json'),JSON.stringify({passed:checks.length,checks,exceptions,node:process.version,jsdom:require('jsdom/package.json').version,environment:'In-process jsdom integration; browser APIs shimmed',limitations:['No rendering, layout, real browser interaction, accessibility tree, real filesystem download, PDF or physical device validation','Dialog, scroll, print, object URL and file chooser APIs shimmed; storage persisted by copying serialized values between DOM instances']},null,2));console.log(checks.length+' DOM integration checks passed.');
 }catch(e){fs.writeFileSync(path.join(root,'docs/verification/dom-failure.txt'),dom.window.document.body.textContent+'\n'+e.stack);throw e;}finally{dom.window.close();}
})();
