/* Theme Park Designer · A WILLIAM MCADA PRODUCT. No runtime dependencies. */
(function(root){'use strict';
const VERSION='0.1.0',CONTENT='1.0.0',PREFIX='mcada:theme-park:',MAX_HISTORY=10000,MAX_SNAPSHOTS=30;
const clone=x=>JSON.parse(JSON.stringify(x)),now=()=>new Date().toISOString(),uid=()=>globalThis.crypto?.randomUUID?.()||'tp-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const gcd=(a,b)=>{a=a<0n?-a:a;b=b<0n?-b:b;while(b)[a,b]=[b,a%b];return a||1n};
class Q{constructor(n,d=1n){n=BigInt(n);d=BigInt(d);if(!d)throw Error('A fraction cannot have a zero denominator.');if(d<0n){n=-n;d=-d}const g=gcd(n,d);this.n=n/g;this.d=d/g}add(v){v=q(v);return new Q(this.n*v.d+v.n*this.d,this.d*v.d)}sub(v){v=q(v);return this.add(new Q(-v.n,v.d))}mul(v){v=q(v);return new Q(this.n*v.n,this.d*v.d)}div(v){v=q(v);return new Q(this.n*v.d,this.d*v.n)}eq(v){v=q(v);return this.n===v.n&&this.d===v.d}num(){return Number(this.n)/Number(this.d)}str(){return this.d===1n?''+this.n:this.n+'/'+this.d}round(p=1){const k=10n**BigInt(p),n=(this.n<0n?-this.n:this.n)*k,c=(2n*n+this.d)/(2n*this.d);return new Q(this.n<0n?-c:c,k)}toJSON(){return this.str()}}
function q(v){if(v instanceof Q)return v;let s=String(v);if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)||s.replace(/\D/g,'').length>12)throw Error('Use a finite decimal with at most 12 digits.');let sign=s[0]==='-'?-1n:1n;s=s.replace(/^[+-]/,'');let[a,b='']=s.split('.');return new Q(BigInt((a||'0')+b)*sign,10n**BigInt(b.length))}
function numeric(raw,unit=''){let s=String(raw??'').trim().replace(/[−–]/g,'-');if(!s)throw Error('Enter an answer.');if(s.length>64)throw Error('Use at most 64 characters.');const units={m:/\s*m$/,cm:/\s*cm$/, 'm²':/\s*m(?:²|\^2|2)$/,cr:/\s*cr$/i,'%':/\s*%$/};if(units[unit])s=s.replace(units[unit],'').trim();if(s.includes(',')){if(!/^[+-]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(s))throw Error('Use a decimal point; commas only separate thousands.');s=s.replace(/,/g,'')}if(s.includes('/')){const t=s.split('/');if(t.length!==2)throw Error('Use one fraction, such as 3/4.');return q(t[0].trim()).div(q(t[1].trim()))}return q(s)}
const FAC=[
{id:'coaster',name:'Coaster',w:20,h:12,cost:24000,color:'#f2a15b',door:[[8,12],[12,12]],base:[2,4]},
{id:'carousel',name:'Carousel',w:12,h:12,cost:12000,color:'#b49ad6',door:[[4,12],[8,12]],base:[42,4]},
{id:'theater',name:'Theater',w:16,h:10,cost:10000,color:'#e48688',door:[[6,0],[10,0]],base:[2,26]},
{id:'food',name:'Food pavilion',w:10,h:8,cost:8000,color:'#efc459',door:[[4,0],[8,0]],base:[42,26]},
{id:'services',name:'Services',w:6,h:8,cost:4000,color:'#85b9c5',door:[[6,2],[6,6]],base:[22,8]},
{id:'entrance',name:'Entrance',w:4,h:8,cost:2000,color:'#8396c4',door:[[4,2],[4,6]],street:[[0,0],[4,0]],base:[24,0]}];
const byId=Object.fromEntries(FAC.map(f=>[f.id,f]));
function rectCells(r){if(!Array.isArray(r)||r.length!==4||r.some(v=>!Number.isInteger(v)||v%2)||r[2]<=0||r[3]<=0)throw Error('Use positive dimensions and coordinates on the 2 m grid.');let[x,y,w,h]=r;if(x<0||y<0||x+w>60||y+h>40)throw Error('Keep the complete rectangle inside the 60 m × 40 m site.');let a=[];for(let j=y;j<y+h;j+=2)for(let i=x;i<x+w;i+=2)a.push(j/2*30+i/2);return a}
const MAIN=[...new Set([...rectCells([0,18,60,4]),...rectCells([28,0,4,40])])].sort((a,b)=>a-b),sortSet=a=>[...new Set(a)].sort((x,y)=>x-y),xy=i=>[i%30*2,Math.floor(i/30)*2];
function dims(f,t){return t?.rotation===90?[f.h,f.w]:[f.w,f.h]}
function segment(f,t,kind='door'){return f[kind].map(([u,v])=>t.rotation===90?[t.x+f.h-v,t.y+u]:[t.x+u,t.y+v])}
function touches(seg,i){let [[a,b],[c,d]]=seg,[x,y]=xy(i);return b===d?((b===y||b===y+2)&&Math.min(Math.max(a,c),x+2)>Math.max(Math.min(a,c),x)):((a===x||a===x+2)&&Math.min(Math.max(b,d),y+2)>Math.max(Math.min(b,d),y))}
function flood(paths,seeds){let available=new Set(paths),seen=new Set(),todo=seeds.filter(i=>available.has(i));while(todo.length){let i=todo.pop();if(seen.has(i))continue;seen.add(i);let c=i%30,r=Math.floor(i/30);for(let j of [c>0?i-1:-1,c<29?i+1:-1,r>0?i-30:-1,r<19?i+30:-1])if(available.has(j)&&!seen.has(j))todo.push(j)}return seen}
function newPlan(){return {revision:0,facilities:{},paths:[...MAIN],green:[],expansion:null,mainDrawn:false,rotationSeen:false,raw:{},evidence:{},history:[],support:[],overrides:[]}}
function baseline(){let p=newPlan();for(let f of FAC)p.facilities[f.id]={x:f.base[0],y:f.base[1],rotation:0};p.paths=sortSet([...MAIN,...[[10,16,4,2],[46,16,4,2],[8,22,4,4],[46,22,4,4]].flatMap(rectCells)]);p.green=sortSet([[0,0,24,4],[32,0,28,4],[0,36,28,4],[32,36,28,4],[20,26,6,8]].flatMap(rectCells));p.expansion=[32,4,10,14];p.mainDrawn=true;return p}
function designFP(p){return JSON.stringify([FAC.map(f=>[f.id,p.facilities[f.id]||null]),sortSet(p.paths),sortSet(p.green),p.expansion])}
function geometry(p){let errors=[],build=new Set(),owners={},paths=new Set(p.paths),green=new Set(p.green);for(let f of FAC){let t=p.facilities[f.id];if(!t){errors.push({kind:'missing',id:f.id,text:'Place the '+f.name.toLowerCase()+'.'});continue}try{if(![0,90].includes(t.rotation))throw Error('Use 0° or 90° rotation.');let[w,h]=dims(f,t),cs=rectCells([t.x,t.y,w,h]);for(let i of cs){if(build.has(i)){errors.push({kind:'overlap',id:f.id,cell:i,text:f.name+' overlaps '+byId[owners[i]].name+'.'});break}}cs.forEach(i=>{build.add(i);owners[i]=f.id});if(f.street){let seg=segment(f,t,'street'),legal=(seg.every(([x,y])=>y===0)||seg.every(([x,y])=>x===60));if(!legal)errors.push({kind:'street',id:f.id,text:'Place the entrance street edge on the south boundary (0°) or east boundary (90°).'})}}catch(e){errors.push({kind:'bounds',id:f.id,text:f.name+': '+e.message})}}
for(let [a,b,n]of [[paths,build,'Path overlaps a facility'],[green,build,'Green space overlaps a facility'],[green,paths,'Green space overlaps a path']]){let cell=[...a].find(i=>b.has(i));if(cell!==undefined)errors.push({kind:'allocation',cell,text:n+'. Erase that cell before changing its use.'})}if(MAIN.some(i=>!paths.has(i)))errors.push({kind:'main',text:'Restore both required main paths.'});let ent=p.facilities.entrance,roots=ent?[...paths].filter(i=>touches(segment(byId.entrance,ent),i)):[],connected=flood(paths,roots),doors={};for(let f of FAC){let t=p.facilities[f.id];doors[f.id]=!!t&&[...connected].some(i=>touches(segment(f,t),i))}
let expansionOK=false,expansionArea=0;if(p.expansion){try{let cs=rectCells(p.expansion);expansionArea=cs.length*4;expansionOK=cs.every(i=>!build.has(i)&&!paths.has(i)&&!green.has(i))}catch{}}let pathArea=paths.size*4,greenArea=green.size*4,facilityArea=build.size*4,unused=2400-facilityArea-pathArea-greenArea,cost=FAC.filter(f=>p.facilities[f.id]).reduce((n,f)=>n+f.cost,0)+pathArea*25+greenArea*10+4000,balance=90000-cost;
let findings=[];if(!roots.length)findings.push({id:'entrance',text:'The entrance park door has no connected path.'});for(let f of FAC.filter(f=>f.id!=='entrance'))if(!doors[f.id])findings.push({id:f.id,text:f.name+' has no route to the entrance.'});if(connected.size!==paths.size)findings.push({text:(paths.size-connected.size)+' path cells are disconnected from the entrance.'});if(pathArea<240||pathArea>600)findings.push({text:'Paths occupy '+pathArea+' m²; the allowed range is 240–600 m².'});if(greenArea<480)findings.push({text:'Green space needs '+(480-greenArea)+' m² more to reach 480 m² (20%).'});if(cost>90000)findings.push({text:'Construction is '+(cost-90000)+' cr over the budget.'});let feasible=!errors.length&&!findings.length,distinction=feasible&&balance>=4500&&expansionOK&&expansionArea>=100;
return {errors,build:[...build],owners,roots,connected:[...connected],doors,pathArea,greenArea,facilityArea,unused,cost,balance,expansionArea,expansionOK,findings,feasible,distinction,code:feasible?(distinction?'distinction':'approved'):'revision',pathPercent:q(pathArea).div(24).round(1),greenPercent:q(greenArea).div(24).round(1),reservePercent:q(balance).div(900).round(1)}}
function edit(p,fn){let old=clone(p),next=clone(p);fn(next);let g=geometry(next),blocking=g.errors.filter(e=>e.kind!=='missing');if(blocking.length)throw Error(blocking[0].text);next.revision++;Object.assign(p,next);return old}
function place(p,id,x,y,rotation){if(!byId[id])throw Error('Choose a known facility.');return edit(p,n=>{n.facilities[id]={x,y,rotation};if(rotation===90&&byId[id].w!==byId[id].h)n.rotationSeen=true})}
function paint(p,layer,ids,erase=false){if(!['paths','green'].includes(layer))throw Error('Choose a land layer.');if(ids.some(i=>!Number.isInteger(i)||i<0||i>=600))throw Error('Choose cells inside the site.');return edit(p,n=>{if(erase&&layer==='paths'&&ids.some(i=>MAIN.includes(i)))throw Error('The two main paths are required.');n[layer]=sortSet(erase?n[layer].filter(i=>!ids.includes(i)):[...n[layer],...ids])})}
function setExpansion(p,r){if(r)rectCells(r);return edit(p,n=>{n.expansion=r})}
function fresh(alias='Pair-01'){return {schema:'mcada-project-progress',schemaVersion:'1.0.0',projectId:'theme-park',appVersion:VERSION,contentVersion:CONTENT,sessionId:uid(),scenarioId:'TP-BASE',teamAlias:alias,partnerA:'Learner A',partnerB:'Learner B',parkName:'',planner:'A',brief:false,currentStage:1,maxStage:1,lessonSwaps:[],plan:newPlan(),snapshots:[],aId:null,bId:null,raw:{},evidence:{},history:[],support:[],overrides:[],reviews:[],transferMode:{A:'digital',B:'digital'},transferPaper:{},calculator:true,transferCalculator:false,localRevision:0,updatedAt:now(),completedAt:null}}
const stages=['Land offer','Survey desk','Attraction studio','Design table','Paths & landscape','Quantity surveyor','Inspection','Opening day'];
const labels={C01:'The scale drawing',C02:'Length and area scale',C03:'Areas of the park',C04:'Space a ride reserves',C05:'Place and rotate',C06:'The land-use ledger',C07:'Construction budget',C08:'Compare two plans',C09A:'Individual transfer · A',C09B:'Individual transfer · B'};
const help={
C01:['Scale','The scale compares drawing length with real length. Use the labeled units.','Divide real meters by meters per drawing centimeter. Put both lengths in the same unit for a ratio.','At 1 cm:5 m, a 20 m wall is 4 cm on paper; 1 cm:500 cm is 1:500.'],
C02:['Area scale','A square has two dimensions. Count columns and rows separately.','Square the length factor to find the area factor.','A 3 m square is 9 m². A 6 m square is 36 m²: twice the length, four times the area.'],
C03:['Shape areas','Use the rectangle, circle or triangle formula. Area is in square meters.','For a circle, halve the diameter first. For a triangle, use the perpendicular height. Use π=3.14.','A 6 m diameter circle has radius 3 m and area 28.26 m². A triangle with base 10 m and height 4 m has area 20 m².'],
C04:['Reserved footprint','The occupied shape and its reserved space are different. The roof is already inside its facility.','Count the whole reserved footprint in the land ledger. Subtract platform area to find clearance.','A 6×6 m reservation containing a 20 m² platform still reserves 36 m². Its clearance is 16 m².'],
C05:['Coordinates and rotation','Coordinates are actual meters from the lower-left. Use multiples of 2.','Choose a tile, set its lower-left point, and use 0° or 90°. A preview counts as rotation evidence.','A 6×10 m rectangle rotates to 10×6 m; both cover 60 m². Its door rotates with it.'],
C06:['Land allocation','Union means the space used at least once. Each grid cell is 4 m².','Add the two path areas, subtract overlap once, then count new connector cells once. Percentage = area ÷ 2400 × 100. Round percent answers to 0.1 percentage point.','Paths of 80 m² and 50 m² with a 10 m² overlap occupy 120 m². A 60 m² zone in a 300 m² site is 1/5 or 20%.'],
C07:['Quantity × rate','Area rates use m²; boundary treatment uses length in m. The quoted gate is included.','Multiply each quantity by its rate. Add the costs; subtract the total from the budget. Round the reserve percentage to 0.1 percentage point.','80 m² at 12 cr/m² costs 960 cr. A 1000 cr budget minus 1100 cr gives −100 cr: an overrun.'],
C08:['A numerical tradeoff','Compare actual checked snapshots. The best plan is not always the cheapest.','Choose a metric, enter its two values and B−A change, then recommend a plan using a short reason.','Adding 12 m² of green at 10 cr/m² costs 120 cr more. Landscape improves while budget reserve falls.'],
C09A:['Independent transfer','Use the new pavilion dimensions, not your pair’s park values.','Convert each length; calculate area; compare with the whole site. Record help or calculator use honestly.','At 1 cm:5 m, a 10×15 m pavilion is 2×3 cm. It uses 150 m². Rotation swaps the drawing lengths.'],
C09B:['Independent transfer','Use the new pavilion dimensions, not your pair’s park values.','Convert each length; calculate area; compare with the whole site. Record help or calculator use honestly.','At 1 cm:5 m, a 10×15 m pavilion is 2×3 cm. It uses 150 m². Rotation swaps the drawing lengths.']};
function snapshot(s,id){return s.snapshots.find(x=>x.id===id)}
function defs(s,p=s.plan){let d={},g=geometry(p);const num=(group,key,label,n,unit='',hint='Recheck the quantities and units.')=>d[key]={group,key,label,kind:'num',expected:q(n),unit,hint};const sel=(group,key,label,expected,options,hint='Choose the statement that matches the quantity.')=>d[key]={group,key,label,kind:'select',expected,options,hint};
num('C01','drawW','Drawing width',15,'cm');num('C01','drawH','Drawing height',10,'cm');num('C01','real35','Actual length represented by 3.5 cm',14,'m');d.ratio={group:'C01',key:'ratio',label:'Drawing : real (same-unit ratio)',kind:'ratio',expected:q(1).div(400),hint:'Convert meters to centimeters before comparing.'};
for(let[k,l,n,u]of [['cellArea','One 2 m square cell',4,'m²'],['doubleArea','One 4 m square',16,'m²'],['lengthFactor','Length scale factor',2,''],['areaFactor','Area scale factor',4,''],['columns','Number of columns',30,''],['rows','Number of rows',20,'']])num('C02',k,l,n,u);
num('C03','siteArea','Site area',2400,'m²');for(let f of FAC)num('C03','area_'+f.id,f.name+' reserved area',f.w*f.h,'m²');num('C03','radius','Carousel radius',5,'m','The diameter is twice the radius.');num('C03','circleArea','Carousel platform area',78.5,'m²','Use π=3.14 and radius 5 m, not diameter 10 m.');num('C03','triangleArea','Shade triangle area',24,'m²','Halve base × perpendicular height.');sel('C03','circleFormula','Circle calculation','radius',[['radius','π × radius × radius'],['diameter','π × diameter × diameter']]);sel('C03','triangleFormula','Triangle calculation','half',[['half','base × perpendicular height ÷ 2'],['rect','base × height']]);
num('C04','clearance','Reserved clearance',65.5,'m²');num('C04','rideLedger','Carousel area in land ledger',144,'m²');num('C04','shadeExtra','Additional land for shade roof',0,'m²');sel('C04','landClass','Platform and clearance are…','inside',[['inside','Both inside the reserved footprint'],['extra','Added to the footprint as extra land']]);
num('C05','beforeW','Preview: coaster width before rotation',20,'m');num('C05','beforeH','Preview: coaster height before rotation',12,'m');num('C05','afterW','Preview: coaster width after 90°',12,'m');num('C05','afterH','Preview: coaster height after 90°',20,'m');num('C05','beforeArea','Coaster area before',240,'m²');num('C05','afterArea','Coaster area after',240,'m²');d.layout={group:'C05',key:'layout',label:'All six placements and rotation preview',kind:'struct',expected:JSON.stringify([FAC.map(f=>[f.id,p.facilities[f.id]||null]),p.rotationSeen])};
for(let[k,l,n]of [['mainH','Horizontal main path',240],['mainV','Vertical main path',160],['cross','Crossroads overlap',16],['mainUnion','Main-path union',384],['pathArea','All paths',g.pathArea],['greenArea','Green space',g.greenArea],['facArea','All reserved facilities',g.facilityArea],['unused','Undeveloped land',g.unused]])num('C06',k,l,n,'m²');num('C06','pathPercent','Paths — nearest 0.1 percentage point',g.pathPercent,'%');num('C06','greenFraction','Green as a fraction of the site',q(g.greenArea).div(2400));num('C06','greenPercent','Green — nearest 0.1 percentage point',g.greenPercent,'%');sel('C06','expClass','Expansion is…','unused',[['unused','Part of undeveloped land'],['extra','An extra area added to the site']]);if(p.expansion)num('C06','expArea','Designated expansion rectangle',g.expansionArea,'m²');d.mainBuilt={group:'C06',key:'mainBuilt',label:'Construct both main paths',kind:'struct',expected:p.mainDrawn};
for(let[k,l,n,u]of [['perimeter','Full boundary length, including gate',200,'m'],['facilityCost','Six facilities',60000,'cr'],['pathCost','Paths at 25 cr/m²',g.pathArea*25,'cr'],['greenCost','Landscape at 10 cr/m²',g.greenArea*10,'cr'],['boundaryCost','Boundary at 20 cr/m',4000,'cr'],['total','Total construction cost',g.cost,'cr'],['balance','Signed budget balance',g.balance,'cr'],['reserve','Reserve — nearest 0.1 percentage point',g.reservePercent,'%']])num('C07',k,l,n,u);
let A=snapshot(s,s.aId),B=snapshot(s,s.bId);d.compare={group:'C08',key:'compare',label:'Two different inspected plans',kind:'struct',expected:[A?.id,B?.id,A?designFP(A.plan):'',B?designFP(B.plan):'']};const metrics=[['cost','Construction cost (cr)'],['greenArea','Green area (m²)'],['pathArea','Path area (m²)'],['unused','Unused area (m²)'],['balance','Budget balance (cr)'],['connectedDoors','Connected facility doors']];d.metric={group:'C08',key:'metric',label:'Compare this quantity',kind:'choice',options:metrics};let metric=s.raw.metric||'cost',value=z=>z?(metric==='connectedDoors'?Object.values(geometry(z.plan).doors).filter(Boolean).length:geometry(z.plan)[metric]):0;num('C08','valueA','Plan A value',value(A));num('C08','valueB','Plan B value',value(B));num('C08','delta','Change: B − A',value(B)-value(A));d.chosen={group:'C08',key:'chosen',label:'Our recommendation',kind:'choice',options:[['A','Plan A'],['B','Plan B']]};d.reason={group:'C08',key:'reason',label:'One short reason or teacher-recorded oral response',kind:'text'};
for(let who of ['A','B']){let gr='C09'+who,vals=who==='A'?[3,2,96,4,2,3]:[4,1.5,96,4,1.5,4];['width','height','area','percent','rotWidth','rotHeight'].forEach((k,i)=>num(gr,'transfer'+who+k,['Drawing width','Drawing height','Actual area','Percent of site','Rotated drawing width','Rotated drawing height'][i],vals[i],['cm','cm','m²','%','cm','cm'][i]));}
for(let v of Object.values(d)){v.global=v.group==='C08'||v.group.startsWith('C09');v.id='TP-'+v.group+'.'+v.key;v.objective='TP-'+v.group.slice(1,3)}return d}
const target=(s,d,p=s.plan)=>d.global?s:p;
function fp(s,key,p=s.plan){let d=defs(s,p)[key];if(!d)throw Error('Unknown field');return JSON.stringify([CONTENT,key,d.expected??d.options??d.kind,d.group==='C08'?[s.aId,s.bId,s.raw.metric,s.raw.chosen]:null])}
function evaluate(s,key,raw,p=s.plan){let d=defs(s,p)[key];if(!d)return 'Unknown field.';try{if(d.kind==='struct'){if(key==='layout'){let e=geometry(p).errors;return e.length?e[0].text:!p.rotationSeen?'Use the rotation preview at least once.':null}if(key==='mainBuilt')return p.mainDrawn?null:'Construct the two required main paths.';if(key==='compare'){let A=snapshot(s,s.aId),B=snapshot(s,s.bId);if(!A||!B)return 'Save an inspected Plan A and Plan B.';if(!planOK(s,A.plan)||!planOK(s,B.plan))return 'Both snapshots need current mathematics.';return designFP(A.plan)!==designFP(B.plan)?null:'Change a facility, path, green cell or expansion designation for Plan B.'}}if(!String(raw??'').trim())return 'Enter '+d.label.toLowerCase()+'.';if(d.kind==='num')return numeric(raw,d.unit).eq(d.expected)?null:d.hint;if(d.kind==='ratio'){let t=String(raw).split(':');return t.length===2&&numeric(t[0]).num()>0&&numeric(t[1]).num()>0&&numeric(t[0]).div(numeric(t[1])).eq(d.expected)?null:d.hint}if(d.kind==='select')return raw===d.expected?null:d.hint;if(d.kind==='choice')return d.options.some(x=>x[0]===raw)?null:'Choose an option.';if(d.kind==='text')return String(raw).length<=2000?null:'Use at most 2000 characters.'}catch(e){return e.message}return null}
function state(s,key,p=s.plan){let d=defs(s,p)[key],t=target(s,d,p),e=t.evidence[key];if(!e)return 'empty';let response=d.kind==='struct'?'':String(t.raw[key]??'');return e.fp===fp(s,key,p)&&e.response===response&&e.passed?'checked':e.fp!==fp(s,key,p)?'stale':'retry'}
function groupFingerprint(s,gr,p=s.plan){return JSON.stringify(Object.values(defs(s,p)).filter(d=>d.group===gr).map(d=>fp(s,d.key,p)))}
function overridden(s,gr,p=s.plan){let t=gr==='C08'||gr.startsWith('C09')?s:p;return t.overrides.some(x=>x.group===gr&&x.fp===groupFingerprint(s,gr,p))}
function groupOK(s,gr,p=s.plan){if(gr.startsWith('C09')&&s.transferMode[gr.slice(-1)]!=='digital')return !!s.transferPaper[gr.slice(-1)]||overridden(s,gr,p);if(gr==='C05'&&geometry(p).errors.length)return false;if(overridden(s,gr,p))return true;return Object.values(defs(s,p)).filter(d=>d.group===gr).every(d=>state(s,d.key,p)==='checked')}
function check(s,gr,p=s.plan){let errors=[],ds=Object.values(defs(s,p)).filter(d=>d.group===gr);if(gr.startsWith('C09')&&s.transferMode[gr.slice(-1)]!=='digital'){return s.transferPaper[gr.slice(-1)]?[]:[{key:'paper',message:'Ask the teacher to record this paper or oral response.'}]}let t=gr==='C08'||gr.startsWith('C09')?s:p;if(t.history.length+ds.length>MAX_HISTORY)throw Error('Attempt history is full. Export a backup before starting a new session.');for(let d of ds){let raw=d.kind==='struct'?'':String(t.raw[d.key]??''),err=evaluate(s,d.key,raw,p),a={key:d.key,group:gr,response:raw,fp:fp(s,d.key,p),passed:!err,at:now(),revision:p.revision};t.history.push(a);t.evidence[d.key]=clone(a);if(err)errors.push({key:d.key,message:err})}return errors}
function planOK(s,p=s.plan){return !geometry(p).errors.length&&['C01','C02','C03','C04','C05','C06','C07'].every(gr=>groupOK(s,gr,p))}
function saveSnapshot(s,label){if(!planOK(s))throw Error('Check all seven design checkpoints before saving an inspected plan.');if(s.snapshots.length>=MAX_SNAPSHOTS)throw Error('Snapshot limit reached. Export and delete an unneeded snapshot.');if(label==='B'){let a=snapshot(s,s.aId);if(!a)throw Error('Save Plan A first.');if(designFP(a.plan)===designFP(s.plan))throw Error('Plan B needs a change to the design, not just its name.')}let x={id:uid(),label,at:now(),plan:clone(s.plan)};s.snapshots.push(x);s[label==='A'?'aId':'bId']=x.id;s.completedAt=null;return x}
function deleteSnapshot(s,id){s.snapshots=s.snapshots.filter(x=>x.id!==id);if(s.aId===id)s.aId=null;if(s.bId===id)s.bId=null;s.completedAt=null;s.reviews=s.reviews.filter(r=>r.snapshotId!==id);s.history=s.history.filter(r=>r.snapshotId!==id)}
function outcome(s){let chosen=snapshot(s,s.raw.chosen==='A'?s.aId:s.bId),g=chosen?geometry(chosen.plan):geometry(s.plan);let complete=chosen&&planOK(s,chosen.plan)&&groupOK(s,'C08')&&groupOK(s,'C09A')&&groupOK(s,'C09B');let code=!complete?'draft':([...chosen.plan.overrides,...s.overrides].length?'provisional':g.code);return {...g,code,title:({draft:'Draft — finish checks',provisional:'Provisional — review required',distinction:'Opening-day distinction',approved:'Park approved',revision:'Return to the design table'})[code],chosen,complete:!!complete}}
function validateSession(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Choose a Theme Park progress file.');let s=clone(input);if(s.schema!=='mcada-project-progress'||s.projectId!=='theme-park')throw Error('This is not a Theme Park progress file.');if(s.schemaVersion!=='1.0.0'||s.contentVersion!==CONTENT||s.scenarioId!=='TP-BASE')throw Error('Unsupported schema, content version, or scenario. Current work is unchanged.');if(typeof s.appVersion!=='string'||!/^0\.1\.\d+$/.test(s.appVersion))throw Error('This application version needs a defined migration.');
const allowed=Object.keys(fresh());for(let k of Object.keys(s))if(!allowed.includes(k)&&!['duplicateOf','imported'].includes(k))throw Error('Unknown session field: '+k);let base=fresh();for(let k of allowed)if(!(k in s))throw Error('Missing required session field: '+k);for(let k of ['teamAlias','partnerA','partnerB','parkName'])if(typeof s[k]!=='string'||s[k].length>80)throw Error('Invalid '+k);if(typeof s.sessionId!=='string'||!/^[-\w]{1,100}$/.test(s.sessionId))throw Error('Invalid session identity.');if(!Number.isInteger(s.currentStage)||s.currentStage<1||s.currentStage>8||!Number.isInteger(s.maxStage)||s.maxStage<1||s.maxStage>8)throw Error('Invalid stage.');
function rawCheck(o){if(!o||typeof o!=='object'||Array.isArray(o))throw Error('Invalid response record.');for(let[k,v]of Object.entries(o))if(typeof v!=='string'||v.length>2000||['__proto__','constructor','prototype'].includes(k))throw Error('Invalid response value.');}
function history(a){if(!Array.isArray(a)||a.length>MAX_HISTORY)throw Error('Invalid or excessive history.');for(let x of a)if(!x||typeof x!=='object'||JSON.stringify(x).length>30000)throw Error('Invalid history record.')}
function planCheck(p){if(!p||typeof p!=='object')throw Error('Missing plan.');for(let k of Object.keys(p))if(!Object.keys(newPlan()).includes(k))throw Error('Unknown plan field: '+k);for(let k of Object.keys(newPlan()))if(!(k in p))throw Error('Missing plan field: '+k);if(!Number.isInteger(p.revision)||p.revision<0||typeof p.mainDrawn!=='boolean'||typeof p.rotationSeen!=='boolean')throw Error('Invalid plan metadata.');if(!p.facilities||typeof p.facilities!=='object'||Array.isArray(p.facilities))throw Error('Invalid facilities.');for(let[id,t]of Object.entries(p.facilities)){if(!byId[id]||!t||Object.keys(t).sort().join(',')!=='rotation,x,y'||![0,90].includes(t.rotation))throw Error('Invalid facility transform.');let[w,h]=dims(byId[id],t);rectCells([t.x,t.y,w,h])}for(let l of ['paths','green'])if(!Array.isArray(p[l])||p[l].length>600||p[l].some(i=>!Number.isInteger(i)||i<0||i>=600)||new Set(p[l]).size!==p[l].length)throw Error('Invalid or repeated land cells.');if(p.expansion)rectCells(p.expansion);rawCheck(p.raw);rawCheckEvidence(p.evidence);history(p.history);history(p.support);history(p.overrides);}
function rawCheckEvidence(o){if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).length>200)throw Error('Invalid checkpoint evidence.');for(let v of Object.values(o))if(!v||typeof v!=='object'||typeof v.fp!=='string'||v.fp.length>15000||typeof v.response!=='string'||v.response.length>2000||typeof v.passed!=='boolean')throw Error('Invalid checkpoint result.')}
planCheck(s.plan);if(!Array.isArray(s.snapshots)||s.snapshots.length>MAX_SNAPSHOTS)throw Error('Too many snapshots.');let ids=new Set();for(let x of s.snapshots){if(!x||typeof x.id!=='string'||ids.has(x.id)||!['A','B'].includes(x.label))throw Error('Invalid snapshot identity.');ids.add(x.id);planCheck(x.plan)}for(let id of [s.aId,s.bId])if(id!==null&&!ids.has(id))throw Error('A comparison points to a missing snapshot.');rawCheck(s.raw);rawCheckEvidence(s.evidence);for(let k of ['history','support','overrides','reviews','lessonSwaps'])history(s[k]);for(let who of ['A','B']){if(!['digital','paper','oral'].includes(s.transferMode?.[who]))throw Error('Invalid transfer mode.');if(s.transferPaper?.[who]&&(typeof s.transferPaper[who].note!=='string'||!s.transferPaper[who].note.trim()||s.transferPaper[who].note.length>2000))throw Error('Invalid paper review.');}
if(!Number.isInteger(s.localRevision)||s.localRevision<0||typeof s.brief!=='boolean'||typeof s.calculator!=='boolean'||typeof s.transferCalculator!=='boolean'||!['A','B'].includes(s.planner))throw Error('Invalid session settings.');
let all=Object.assign({},...([s.plan,...s.snapshots.map(x=>x.plan)].map(p=>defs(s,p))));for(let p of [s.plan,...s.snapshots.map(x=>x.plan)]){for(let k of Object.keys(p.raw))if(!all[k]||all[k].global)throw Error('Unknown plan answer: '+k);for(let[k,e]of Object.entries(p.evidence)){if(!all[k]||all[k].global)throw Error('Unknown checkpoint: '+k);if(e.fp===fp(s,k,p)&&evaluate(s,k,p.raw[k]??'',p)!==null)e.passed=false}}
for(let k of Object.keys(s.raw))if(!all[k]||!all[k].global)throw Error('Unknown global answer: '+k);for(let[k,e]of Object.entries(s.evidence)){if(!all[k]||!all[k].global)throw Error('Unknown checkpoint: '+k);if(e.fp===fp(s,k)&&evaluate(s,k,s.raw[k]??'')!==null)e.passed=false}
s.appVersion=VERSION;if(!outcome(s).complete)s.completedAt=null;return s}
function decode(text){if(new TextEncoder().encode(text).length>5*1024*1024)throw Error('Progress files must be no larger than 5 MiB.');let a;try{a=JSON.parse(text)}catch{throw Error('This file is not valid JSON.')}if(a?.schema==='theme-park-backup'){if(!Array.isArray(a.sessions)||a.sessions.length>100)throw Error('Invalid session backup.');return a.sessions.map(validateSession)}return [validateSession(a)]}
class Store{constructor(storage){this.storage=storage;this.available=true;try{storage.setItem(PREFIX+'probe','1');if(storage.getItem(PREFIX+'probe')!=='1')throw Error();storage.removeItem(PREFIX+'probe')}catch{this.available=false}}ids(){if(!this.available)return [];let ids=[];for(let i=0;i<this.storage.length;i++){let k=this.storage.key(i);if(k?.startsWith(PREFIX+'session:'))ids.push(k.slice((PREFIX+'session:').length))}return ids}read(id){return validateSession(JSON.parse(this.storage.getItem(PREFIX+'session:'+id)))}write(s){if(!this.available)throw Error('Storage unavailable. Export progress to keep your work.');let old=this.storage.getItem(PREFIX+'session:'+s.sessionId);if(old){let n=JSON.parse(old);if(n.localRevision>s.localRevision)throw Error('NEWER_REVISION')}let next=clone(s);next.localRevision++;next.updatedAt=now();this.storage.setItem(PREFIX+'session:'+s.sessionId,JSON.stringify(next));s.localRevision=next.localRevision;s.updatedAt=next.updatedAt;return s.updatedAt}delete(ids){for(let id of ids)this.storage.removeItem(PREFIX+'session:'+id);for(let id of ids)if(this.storage.getItem(PREFIX+'session:'+id)!==null)throw Error('Deletion could not be confirmed.');}}
function duplicate(s){let n=clone(s);n.duplicateOf=s.sessionId;n.sessionId=uid();n.localRevision=0;n.updatedAt=now();return n}
function bypass(s,gr,reason){if(!String(reason).trim())throw Error('Record a reason for the teacher bypass.');let t=gr==='C08'||gr.startsWith('C09')?s:s.plan;if(t.overrides.length>=1000)throw Error('Override limit reached.');t.overrides.push({group:gr,fp:groupFingerprint(s,gr),reason:String(reason).slice(0,2000),at:now()})}
function diagnostics(){let p=baseline(),g=geometry(p);return [['Facility area',g.facilityArea===704],['Path union',g.pathArea===432],['Green space',g.greenArea===480],['Budget',g.cost===79600&&g.balance===10400],['Rooted access',g.connected.length===108&&Object.values(g.doors).every(Boolean)],['Expansion',g.expansionOK&&g.expansionArea===140],['Corner contact rejected',!touches([[10,16],[14,16]],8*30+7)],['Exact fractions',numeric('157/2').eq('78.5')],['Baseline distinction',g.distinction]].map(([name,passed])=>({name,passed}))}
const API={VERSION,CONTENT,PREFIX,MAX_HISTORY,MAX_SNAPSHOTS,clone,now,uid,Q,q,numeric,FAC,byId,MAIN,rectCells,xy,dims,segment,touches,flood,newPlan,baseline,designFP,geometry,edit,place,paint,setExpansion,fresh,stages,labels,help,snapshot,defs,fp,evaluate,state,groupOK,check,planOK,saveSnapshot,deleteSnapshot,outcome,validateSession,decode,Store,duplicate,bypass,diagnostics};root.TP=API;if(typeof module!=='undefined')module.exports=API;
})(globalThis);
