/* Powers of Ten — A WILLIAM MCADA PRODUCT. Exact mathematics and evidence model. */
(function(root){'use strict';
const VERSION='0.1.0',CONTENT='1.0.0',PREFIX='mcada:powers-of-ten:',now=()=>new Date().toISOString(),clone=x=>JSON.parse(JSON.stringify(x)),uid=()=>globalThis.crypto?.randomUUID?.()||'sn-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const gcd=(a,b)=>{a=a<0n?-a:a;b=b<0n?-b:b;while(b)[a,b]=[b,a%b];return a||1n};
class Q{constructor(n,d=1n){n=BigInt(n);d=BigInt(d);if(!d)throw Error('A denominator cannot be zero.');if(d<0n){n=-n;d=-d}let g=gcd(n,d);this.n=n/g;this.d=d/g}add(b){b=q(b);return new Q(this.n*b.d+b.n*this.d,this.d*b.d)}sub(b){b=q(b);return new Q(this.n*b.d-b.n*this.d,this.d*b.d)}mul(b){b=q(b);return new Q(this.n*b.n,this.d*b.d)}div(b){b=q(b);return new Q(this.n*b.d,this.d*b.n)}eq(b){b=q(b);return this.n===b.n&&this.d===b.d}cmp(b){const x=this.sub(b);return x.n<0n?-1:x.n>0n?1:0}abs(){return new Q(this.n<0n?-this.n:this.n,this.d)}str(){return this.d===1n?String(this.n):this.n+'/'+this.d}num(){return Number(this.n)/Number(this.d)}toJSON(){return this.str()}}
const ten=n=>n>=0?new Q(10n**BigInt(n)):new Q(1n,10n**BigInt(-n));
function clean(raw){let s=String(raw??'').trim().replace(/[−–]/g,'-');if(s.length>100)throw Error('Use at most 100 characters.');if(s.includes(',')){if(!/^[+-]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(s))throw Error('Use a decimal point; commas only group thousands.');s=s.replaceAll(',','')}return s}
function dec(raw){const s=clean(raw);if(!s)throw Error('Enter a value.');if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s))throw Error('Use ordinary decimal notation.');const neg=s.startsWith('-'),[a,b='']=s.replace(/^[+-]/,'').split('.');return new Q(BigInt((a||'0')+b)*(neg?-1n:1n),10n**BigInt(b.length))}
function integer(raw){const s=clean(raw);if(!/^[+-]?\d+$/.test(s))throw Error('Use a whole-number exponent.');const n=Number(s);if(!Number.isSafeInteger(n)||n< -24||n>24)throw Error('Use an exponent from −24 to 24.');return n}
function q(raw){if(raw instanceof Q)return raw;const s=clean(raw);if(s.includes('/')){const p=s.split('/');if(p.length!==2)throw Error('Use one fraction bar.');return dec(p[0]).div(dec(p[1]))}const m=s.match(/^(.+?)(?:[eE]|\s*[×*]\s*10\s*\^\s*)([+-]?\d+)$/);return m?dec(m[1]).mul(ten(integer(m[2]))):dec(s)}
function sci(a,n,normalized=true,allowInteger=false){const aa=clean(a);if(aa.replace(/^[+-]/,'').replace('.','').replace(/^0+/,'').length>12)throw Error('Use at most 12 significant coefficient digits.');const c=dec(a),e=allowInteger&&String(n??'').trim()===''?0:integer(n);if(normalized&&c.n!==0n&&(c.abs().cmp(1)<0||c.abs().cmp(10)>=0))throw Error('Normalize: the coefficient must be at least 1 and less than 10.');return c.mul(ten(e))}
function eq(raw,want){if(!q(raw).eq(want))throw Error('Recheck the calculation using the supplied values.');return true}
const unitFactors={m:'1000',cm:'10',mm:'1','µm':'0.001','μm':'0.001',um:'0.001',nm:'0.000001'};
function mm(v,u){if(!unitFactors[u])throw Error('Choose a supported length unit.');return q(v).mul(unitFactors[u])}
const stages=['Museum commission','Notation lab','Scientific calculations','Exhibit planning','Construction bench','Verification desk','Mini gallery','Publish exhibit'];
const objects=[['dna','DNA helix','width','2 × 10⁻⁹','m','R1'],['cell','Red blood cell','diameter','8 × 10⁻⁶','m','R2'],['earth','Earth','diameter','1.28 × 10⁷','m','R3'],['moon','Moon','diameter','3.5 × 10⁶','m','R4'],['distance','Earth–Moon','distance','3.84 × 10⁸','m','R4'],['sun','Sun','diameter','1.4 × 10⁹','m','R5'],['orbit','Earth–Sun','distance','1.5 × 10¹¹','m','R3'],['light','Light in vacuum','speed','3 × 10⁸','m/s','R6']];
const sources={R1:['NHGRI — DNA width','https://www.genome.gov/27550069/2012-release-new-nihnhgri-grants-to-harness-nanoscale-technologies-to-cut-dna-sequencing-costs'],R2:['Histology Guide — blood cells','https://histologyguide.com/slideview/MH-033hr-blood-smear/07-slide-1.html'],R3:['NASA — Earth facts','https://science.nasa.gov/earth/facts/'],R4:['NASA — Moon facts','https://science.nasa.gov/moon/facts/'],R5:['NASA — Sun facts','https://science.nasa.gov/sun/facts/'],R6:['NIST — meter','https://www.nist.gov/si-redefinition/meter']};
const ops=[
{id:'C04a',title:'A row of cells',domain:'Microscopic',op:'×',x:['8',-6],y:['2.5',1],unit:'m',prompt:'Place 25 cell diameters end to end. Calculate the total length.',expression:'(8 × 10⁻⁶ m) × (2.5 × 10¹)',c:'20',e:-5,a:'2',n:-4},
{id:'C04b',title:'A pulse of light',domain:'Astronomical',op:'×',x:['3',8],y:['1.28',0],unit:'m',prompt:'Light travels for 1.28 seconds in our model. How far does it travel?',expression:'(3 × 10⁸ m/s) × (1.28 s)',c:'3.84',e:8,a:'3.84',n:8},
{id:'C05a',title:'Across a viewing window',domain:'Microscopic',op:'÷',x:['6.4',-5],y:['8',-6],unit:'widths',prompt:'How many cell diameters span this viewing width? This counts a straight row, not cells packed into an area.',expression:'(6.4 × 10⁻⁵ m) ÷ (8 × 10⁻⁶ m)',c:'0.8',e:1,a:'8',n:0},
{id:'C05b',title:'Sunlight travel time',domain:'Astronomical',op:'÷',x:['1.5',11],y:['3',8],unit:'s',prompt:'Use our mean distance and rounded light speed to calculate the travel time.',expression:'(1.5 × 10¹¹ m) ÷ (3 × 10⁸ m/s)',c:'0.5',e:3,a:'5',n:2},
{id:'C06a',title:'A microscopic path',domain:'Microscopic',op:'+',x:['2.4',-5],y:['7.5',-6],unit:'m',prompt:'Add two straight microchannel segments. Rewrite both using the same power of ten.',expression:'2.4 × 10⁻⁵ m + 7.5 × 10⁻⁶ m',a:'3.15',n:-5},
{id:'C06b',title:'A probe’s logged journey',domain:'Astronomical',op:'+',x:['3.84',8],y:['6',7],unit:'m',prompt:'Add two sequential path lengths. These are logged travel distances, not orbital radii.',expression:'3.84 × 10⁸ m + 6 × 10⁷ m',a:'4.44',n:8},
{id:'C07a',title:'Beneath the coating',domain:'Microscopic',op:'−',x:['8',-6],y:['2',-6],unit:'m',prompt:'A specimen is 8 × 10⁻⁶ m deep. A coating occupies 2 × 10⁻⁶ m. Find the uncoated depth.',expression:'8 × 10⁻⁶ m − 2 × 10⁻⁶ m',a:'6',n:-6},
{id:'C07b',title:'Two very different diameters',domain:'Astronomical',op:'−',x:['1.4',9],y:['1.28',7],unit:'m',prompt:'Find the difference between the supplied Sun and Earth diameters.',expression:'1.4 × 10⁹ m − 1.28 × 10⁷ m',a:'1.3872',n:9}
];
const measurements={A:[['cell','Cell diameter','160','2']],B:[['earth','Earth diameter','20','1'],['moon','Moon diameter','5.5','1'],['centers','Center-to-center distance','600','5']]};
const help={
notation:['Coefficient and exponent','A coefficient tells how many; an exponent tells the power of ten.','Enter the coefficient and a signed whole-number exponent.','0.00045 = 4.5 × 10⁻⁴. For ordinary notation, write every digit.'],
magnitude:['Magnitude','One decade is a factor of ten, not an increase of ten.','Compare the complete values, including coefficients.','3 × 10⁻⁵ is smaller than 7 × 10⁻⁵; ten times 3 × 10⁻⁵ is 3 × 10⁻⁴.'],
units:['Preserve the quantity','The number changes with the unit; the length does not.','Use 1 m = 100 cm = 1000 mm = 10⁶ µm = 10⁹ nm.','12 µm = 0.012 mm = 0.000012 m.'],
multiply:['Multiply in scientific notation','Multiply coefficients; add exponents. Units multiply too.','Keep the raw coefficient/exponent work, then normalize.','(4 × 10⁻³)(3 × 10²) = 12 × 10⁻¹ = 1.2 × 10⁰.'],
divide:['Divide in scientific notation','Divide coefficients; subtract the second exponent.','Normalize afterwards. Length ÷ length is a count; length ÷ speed is time.','(9 × 10⁴)/(3 × 10⁻²) = 3 × 10⁶.'],
add:['Match powers before combining','Adding or subtracting needs the same power of ten.','Choose one exponent and rewrite both coefficients without changing either quantity.','2 × 10⁻³ + 4 × 10⁻⁴ = (2 + 0.4) × 10⁻³.'],
scale:['Model compared with actual','k = model length ÷ actual length, in the same units.','A ratio is model:actual. k > 1 enlarges; 0 < k < 1 reduces.','A 0.3 m model of a 0.003 m object gives k = 100 and model:actual = 100:1.'],
measure:['Report what you measured','A measurement records your physical model, not the ideal target.','Convert to mm; deviation = measured − target. Compare the absolute deviation with tolerance.','Target 50 mm, tolerance ±2 mm: 48 mm is within tolerance; 47 mm needs repair.'],
limit:['A model has limits','A linear scale preserves length ratios; it cannot make every detail practical.','Calculate a predicted size, then compare it with the available space or smallest visible detail.','A 4 m display with a 5 mm visible minimum has a size ratio of 800.'],
science:['Data, pictures, and evidence','Width, diameter, distance, and speed describe different properties.','A diagram explains; a measured observation needs a reliable method and scale. Name your source.','“The model preserves length ratios, but this illustration does not show surface detail.”'],
transfer:['Your own exit response','This is separate evidence for each learner.','Work independently; your first response is retained even if you revise.','For paper/oral work, a teacher records receipt and reviews the actual response.']};
function newSession(){return{schema:'mcada-project-progress',schemaVersion:'1.0.0',projectId:'powers-of-ten',appVersion:VERSION,contentVersion:CONTENT,sessionId:uid(),scenarioId:'SN-BASE',teamAlias:'',students:['',''],currentStage:1,track:'A',inputs:{},checkpoints:{},attempts:[],support:[],teacherOverrides:[],reviews:[],buildRevisions:{A:0,B:0},built:{A:false,B:false},roles:{planner:'1',builder:'1'},completedAt:null,localRevision:0,updatedAt:now(),imported:false,duplicateOf:null}}
const textfield=(id,label,expected,kind='num',options=null)=>({id,label,expected,kind,options});
function groups(s){const gs=[];const add=(id,stage,title,prompt,fields,type='normal',h='notation')=>gs.push({id,stage,title,prompt,fields,type,help:h});const f=textfield,choice=(id,label,w,options)=>f(id,label,w,'select',options);
[['a','0.000008 m → scientific notation','8',-6],['b','12,800,000 m → scientific notation','1.28',7]].forEach(([k,label,a,n])=>add('C01'+k,2,label,'Write the value in normalized scientific notation.',[f('a','Coefficient',a,'coefficient'),f('n','Exponent',n,'exponent')],'sci'));
add('C01c',2,'2 × 10⁻⁹ m → ordinary notation','Write every digit, using a decimal point.',[f('value','Length in meters','0.000000002','decimal')]);add('C01d',2,'3.84 × 10⁸ m → ordinary notation','Write the ordinary decimal value.',[f('value','Length in meters','384000000','decimal')]);
const order=[['dna','DNA • 2 × 10⁻⁹ m'],['depth','Specimen • 6 × 10⁻⁶ m'],['cell','Cell • 8 × 10⁻⁶ m']];add('C02',2,'Small, smaller, smallest','Order the three lengths, then multiply the cell diameter by ten.',[choice('first','Smallest','dna',order),choice('second','Middle','depth',order),choice('third','Largest','cell',order),f('a','Ten times cell: coefficient','8','coefficient'),f('n','Ten times cell: exponent',-5,'exponent'),choice('decade','Magnitude change','one',[['one','One decade larger'],['ten','Ten decades larger'],['same','Same decade']])],'normal','magnitude');
add('C03a',2,'One cell, three units','Convert 8 µm to the requested units.',[f('m','Meters','8e-6'),f('mm','Millimeters','0.008'),f('nm','Nanometers','8000')],'normal','units');add('C03b',2,'Centimeters to meters','Convert 1.28 × 10⁹ cm to meters.',[f('m','Meters','1.28e7')],'normal','units');
for(const o of ops){let fs;if(['×','÷'].includes(o.op))fs=[f('c','Coefficient '+(o.op==='×'?'product':'quotient'),o.c),f('e','Exponent '+(o.op==='×'?'sum':'difference'),o.e,'exponent')];else fs=[f('common','Chosen common exponent',null,'exponent'),f('left','Rewritten first coefficient',null),f('right','Rewritten second coefficient',null)];fs.push(f('a','Final coefficient',o.a,'coefficient'),f('n',o.id==='C05a'?'Final exponent (0 or blank)':'Final exponent',o.n,'exponent'),choice('unit','Result unit',o.unit,[['m','m — length'],['s','s — time'],['widths','diameter-widths — no length unit'],['m/s','m/s — speed']]));add(o.id,3,o.title,o.prompt,fs,'operation',o.op==='×'?'multiply':o.op==='÷'?'divide':'add');gs.at(-1).operation=o}
for(const t of ['A','B']){add('C08'+t,4,t==='A'?'Enlarge a cell':'Reduce Earth and Moon',t==='A'?'Use 16 cm for the model and 8 × 10⁻⁶ m for the actual diameter.':'Use 20 mm for Earth and 1.28 × 10⁷ m for its actual diameter.',[f('model','Model Earth/cell diameter (m)',t==='A'?'0.16':'0.02'),f('k','Scale factor k (fraction allowed)',t==='A'?'20000':'1/640000000'),f('ratioM','Model side of ratio',t==='A'?'20000':'1'),f('ratioA','Actual side of ratio',t==='A'?'1':'640000000'),choice('direction','Scale direction',t==='A'?'enlarge':'reduce',[['enlarge','Enlargement'],['reduce','Reduction']]),...(t==='B'?[f('moon','Exact Moon diameter (mm)','5.46875'),f('rounded','Moon construction target, nearest 0.1 mm','5.5'),f('distance','Earth–Moon center distance (mm)','600')]:[])],'scale','scale');
let fs=[];for(const [id,label]of measurements[t])fs.push(f(id,label+' — measured',null),choice(id+'Unit',label+' — unit',null,Object.keys(unitFactors).filter(x=>!['μm','um'].includes(x)).map(x=>[x,x])),f(id+'Deviation',label+' — deviation in mm',null));fs.push(f('tool','Measuring tool',null,'text'),f('resolution','Tool resolution / estimate (mm)',null));add('C09'+t,6,'Measure your '+(t==='A'?'cell':'Earth–Moon model'),'Enter actual measurements. A correctly reported mismatch is a repair opportunity.',fs,'measurement','measure');
add('C10'+t,7,'Where this scale stops working','Select a comparison and calculate its model size. Then compare the museum’s available ratio with Earth/cell.',[choice('comparison','Comparison',null,t==='A'?[['person','Hypothetical 1.7 m person (answer in m)'],['dna','2 nm DNA width (answer in mm)']]:[['sun','Sun diameter (answer in m)'],['orbit','Earth–Sun distance (answer in m)']]),f('size','Predicted model size in the selected unit',null),f('available','3 m display ÷ 2 mm minimum: ratio','1500'),f('actual','Earth diameter ÷ cell diameter: ratio','1.6e12'),choice('conclusion','One shared linear scale is…','impractical',[['impractical','Possible mathematically, impractical here'],['impossible','Mathematically impossible'],['practical','Practical within these limits']])],'limitation','limit');
add('C11'+t,7,'Tell visitors what your model means','Use one numerical fact and a source. Examine the other track or teacher example.',[f('interpretation','My model preserves… / cannot show…',null,'text'),f('visitor','Other model observed: one preserved or omitted feature',null,'text'),choice('otherDirection','Other model’s direction',t==='A'?'reduce':'enlarge',[['enlarge','Enlargement'],['reduce','Reduction']])],'normal','science');}
add('C11match',7,'Read the science labels','Match each quantity with the measured property. Every picture in this app is an original explanatory diagram.',objects.map(o=>choice(o[0],o[1],o[2],[['width','Width'],['diameter','Diameter'],['distance','Distance'],['speed','Speed']])).concat(choice('image','These original drawings are…','diagram',[['diagram','Explanatory diagrams'],['observation','New measured observations']])),'normal','science');
for(const t of ['1','2'])add('C12'+t,7,'Independent response — learner '+t,t==='1'?'Five strips are each 6 × 10⁻⁶ m long. Find the total. Interpret model:actual = 5000:1.':'A probe travels at 2 × 10⁷ m/s for 30 s. Find the distance. Interpret model:actual = 1:5000.',[choice('mode','Response mode',null,[['digital','On this device'],['paper','Paper / oral submission']]),f('a','Normalized coefficient',t==='1'?'3':'6','coefficient'),f('n','Exponent',t==='1'?-5:8,'exponent'),f('decimal','Ordinary decimal (m)',t==='1'?'0.00003':'600000000','decimal'),choice('direction','Scale direction',t==='1'?'enlarge':'reduce',[['enlarge','Enlargement'],['reduce','Reduction']]),f('scale',t==='1'?'1 mm actual → how many model mm?':'1 mm model → how many actual mm?','5000'),f('submission','Teacher receipt / oral response record',null,'text')],'transfer','transfer');return gs}
const getGroup=(s,id)=>groups(s).find(g=>g.id===id),key=(g,f)=>g+'.'+f;
function raw(s,g){return Object.fromEntries(getGroup(s,g).fields.map(f=>[f.id,s.inputs[key(g,f.id)]||'']))}
function activeGroups(s,stage=null){return groups(s).filter(g=>(stage===null||g.stage===stage)&&(!/^C(?:08|09|10|11)[AB]$/.test(g.id)||g.id.endsWith(s.track)))}
function fingerprint(s,g){const r=raw(s,g),t=/[AB]$/.test(g)?g.slice(-1):null;const dependency=t&&/^C(?:09|10|11)/.test(g)?{plan:raw(s,'C08'+t),build:s.buildRevisions[t]}:null;return JSON.stringify([CONTENT,r,dependency])}
function evaluate(s,gid){const g=getGroup(s,gid),r=raw(s,gid),errors={};const attempt=(f,fn)=>{try{fn()}catch(e){errors[f]=e.message}};
for(const f of g.fields){if(g.type==='transfer'&&((r.mode==='paper'&&!['mode','submission'].includes(f.id))||(r.mode!=='paper'&&f.id==='submission')))continue;
attempt(f.id,()=>{const v=r[f.id];if(f.kind==='text'){if(!v.trim())throw Error('Enter a short response or a teacher-recorded oral response.');if(v.length>600)throw Error('Use at most 600 characters.');return}if(f.kind==='select'){if(!f.options.some(o=>o[0]===v))throw Error('Choose an option.');if(f.expected!==null&&v!==f.expected)throw Error('Choose the property or statement that matches.');return}if(g.id==='C05a'&&f.id==='n'&&v.trim()==='')return;
let x=f.kind==='exponent'?new Q(integer(v)):f.kind==='decimal'?dec(v):q(v);if(f.kind==='coefficient')sci(v,'0');if(f.expected!==null&&!['ratioM','ratioA'].includes(f.id)&&!x.eq(f.expected))throw Error('Recheck the calculation using the supplied values.');});}
if(g.type==='scale')attempt('ratioA',()=>{if(q(r.ratioM).cmp(0)<=0||q(r.ratioA).cmp(0)<=0||!q(r.ratioM).div(r.ratioA).eq(g.id.endsWith('A')?'20000':'1/640000000'))throw Error('Use a positive model:actual ratio in the stated direction.');});
if(g.type==='operation'&&!['×','÷'].includes(g.operation.op)){const o=g.operation;attempt('common',()=>integer(r.common));for(const [name,pair]of [['left',o.x],['right',o.y]])attempt(name,()=>{if(!q(r[name]).mul(ten(integer(r.common))).eq(q(pair[0]).mul(ten(pair[1]))))throw Error('Rewrite this quantity using your chosen common exponent.');});}
if(g.type==='measurement'){for(const [id,,target]of measurements[gid.slice(-1)])attempt(id+'Deviation',()=>{const x=mm(r[id],r[id+'Unit']);if(x.cmp(0)<=0||x.cmp(10000)>0)throw Error('Measured length must be positive and at most 10,000 mm.');if(!q(r[id+'Deviation']).eq(x.sub(target)))throw Error('Deviation is measured length minus the target, in mm.');});attempt('resolution',()=>{if(q(r.resolution).cmp(0)<=0||q(r.resolution).cmp(100)>0)throw Error('State a positive tool resolution, at most 100 mm.');});}
if(g.type==='limitation')attempt('size',()=>eq(r.size,({person:'34000',dna:'0.04',sun:'2.1875',orbit:'234.375'})[r.comparison]||'0'));
return errors}
function status(s,id){const cp=s.checkpoints[id];if(!cp)return 'not-started';if(cp.fingerprint!==fingerprint(s,id))return 'needs-recheck';if(cp.bypass&&s.teacherOverrides.some(o=>o.id===cp.overrideId))return 'bypassed';return Object.keys(evaluate(s,id)).length?'needs-correction':cp.passed?'checked':'needs-correction'}
const ok=(s,id)=>['checked','bypassed'].includes(status(s,id));
function check(s,id){if(s.attempts.length>=10000)throw Error('Attempt limit reached. Export this session and start a new one.');const errors=evaluate(s,id),fp=fingerprint(s,id);s.attempts.push({id:uid(),group:id,track:s.track,buildRevision:s.buildRevisions[s.track],response:raw(s,id),fingerprint:fp,passed:!Object.keys(errors).length,at:now()});s.checkpoints[id]={fingerprint:fp,passed:!Object.keys(errors).length,bypass:false,overrideId:null};return errors}
function setInput(s,k,v){const validKeys=new Set(groups(s).flatMap(g=>g.fields.map(f=>key(g.id,f.id))));if(!validKeys.has(k)&&!/^placard[AB]\.(title|property|source|scaleConfirmed)$/.test(k))throw Error('Unknown field.');if(typeof v!=='string'||v.length>600)throw Error('Invalid or overlong field.');s.inputs[k]=v;}
function fit(s,t=s.track){const r=raw(s,'C09'+t);try{return measurements[t].every(([id,,target,tol])=>mm(r[id],r[id+'Unit']).sub(target).abs().cmp(tol)<=0)}catch{return false}}
function reviewFingerprint(s,type,t=s.track){if(type==='inspection')return JSON.stringify([s.buildRevisions[t],raw(s,'C08'+t),raw(s,'C09'+t)]);if(type==='interpretation')return JSON.stringify([raw(s,'C08'+t),raw(s,'C10'+t),raw(s,'C11'+t),placardData(s,t)]);return fingerprint(s,type)}
function reviewState(s,type,t=s.track){return [...s.reviews].reverse().find(r=>r.type===type&&(type.startsWith('C12')||r.track===t)&&r.fingerprint===reviewFingerprint(s,type,t))?.status||'pending'}
function review(s,type,reviewer,role,state,note,t=s.track){if(!['inspection','interpretation','C121','C122'].includes(type)||!['accepted','pending','repair-needed'].includes(state)||!['teacher','peer'].includes(role)||!reviewer.trim()||reviewer.length>64||!note.trim()||note.length>400)throw Error('Enter reviewer alias, role, status and an inspection/review note.');if(type!=='inspection'&&role!=='teacher')throw Error('Interpretation and transfer reviews need a teacher record.');if(type==='inspection'&&!ok(s,'C09'+t))throw Error('Check the actual measurement record before recording inspection.');s.reviews.push({type,track:t,reviewer,role,status:state,note,fingerprint:reviewFingerprint(s,type,t),at:now()});}
function bypass(s,id,reviewer,reason){if(!getGroup(s,id)||!reviewer.trim()||reviewer.length>64||!reason.trim()||reason.length>400)throw Error('Choose a checkpoint and enter reviewer alias and reason.');const oid=uid();s.teacherOverrides.push({id:oid,group:id,reviewer,reason,at:now()});s.checkpoints[id]={fingerprint:fingerprint(s,id),passed:false,bypass:true,overrideId:oid};}
function placardData(s,t=s.track){return Object.fromEntries(['title','property','source','scaleConfirmed'].map(f=>[f,s.inputs['placard'+t+'.'+f]||'']))}
function labelsOK(s){const p=placardData(s);return !!p.title.trim()&&p.property===(s.track==='A'?'diameter':'diameter-distance')&&p.source===(s.track==='A'?'R2':'R3/R4')&&p.scaleConfirmed==='yes'}
function submissionOK(s,id){const r=raw(s,id);return r.mode==='paper'?!!r.submission.trim():ok(s,id)}
function outcome(s){const required=activeGroups(s).filter(g=>g.type!=='transfer');if(required.some(g=>!ok(s,g.id))||!s.built[s.track]||!['C121','C122'].every(g=>submissionOK(s,g)))return 'Draft — finish checks';if(activeGroups(s).some(g=>status(s,g.id)==='bypassed'))return 'Provisional — teacher review';if(!fit(s)||!labelsOK(s)||['inspection','interpretation','C121','C122'].some(k=>reviewState(s,k)==='repair-needed'))return 'Calibration required';if(['inspection','interpretation'].some(k=>reviewState(s,k)!=='accepted')||['C121','C122'].some(k=>raw(s,k).mode==='paper'&&reviewState(s,k)!=='accepted'))return 'Exhibit ready for review';return 'Featured exhibit'}
function missing(s,stage){const ids=[];if(stage>1&&(!s.teamAlias.trim()||s.students.some(x=>!x.trim())||s.students[0]===s.students[1]))ids.push('Team and two different learner aliases');for(let n=2;n<stage;n++){if(n===5){if(!s.built[s.track])ids.push('Build confirmation');continue}for(const g of activeGroups(s,n))if(g.type==='transfer'?!submissionOK(s,g.id):!ok(s,g.id))ids.push(g.id)}return ids}
function duplicate(s){const c=clone(s);c.duplicateOf=s.sessionId;c.sessionId=uid();c.localRevision=0;c.teamAlias=(s.teamAlias+' — copy').slice(0,64);return c}
function validateSession(raw,imported=true){const obj=v=>v&&typeof v==='object'&&!Array.isArray(v),err=m=>{throw Error(m)},keys=(o,ks)=>obj(o)&&Object.keys(o).every(k=>ks.includes(k)),str=(s,n)=>typeof s==='string'&&s.length<=n,stamp=s=>str(s,40)&&Number.isFinite(Date.parse(s));if(!keys(raw,Object.keys(newSession())))err('Unsupported session fields.');if(raw.schema!=='mcada-project-progress'||raw.projectId!=='powers-of-ten')err('This is not Powers of Ten progress.');if(raw.schemaVersion!=='1.0.0'||raw.contentVersion!==CONTENT||!/^0\.1\.\d+$/.test(raw.appVersion))err('Unsupported application/content/schema version.');
if(!str(raw.sessionId,100)||!/^[-\w]+$/.test(raw.sessionId)||raw.scenarioId!=='SN-BASE'||!str(raw.teamAlias,64)||!Array.isArray(raw.students)||raw.students.length!==2||raw.students.some(x=>!str(x,64))||![1,2,3,4,5,6,7,8].includes(raw.currentStage)||!['A','B'].includes(raw.track)||!Number.isSafeInteger(raw.localRevision)||raw.localRevision<0||!stamp(raw.updatedAt)||!(raw.completedAt===null||stamp(raw.completedAt))||typeof raw.imported!=='boolean'||!(raw.duplicateOf===null||str(raw.duplicateOf,100)))err('Invalid session identity or stage.');
if(!keys(raw.buildRevisions,['A','B'])||!keys(raw.built,['A','B'])||['A','B'].some(t=>!Number.isInteger(raw.buildRevisions[t])||raw.buildRevisions[t]<0||raw.buildRevisions[t]>100||typeof raw.built[t]!=='boolean')||!keys(raw.roles,['planner','builder'])||!['1','2'].includes(raw.roles.planner)||!['1','2'].includes(raw.roles.builder))err('Invalid build or role records.');
function walk(v,d=0){if(d>15)err('Save nesting too deep.');if(typeof v==='number'&&!Number.isFinite(v))err('Nonfinite saved number.');if(typeof v==='string'&&v.length>12000)err('Oversized saved string.');if(obj(v)||Array.isArray(v))for(const k of Object.keys(v)){if(['__proto__','constructor','prototype'].includes(k))err('Unsafe saved key.');walk(v[k],d+1)}}walk(raw);
for(const k of ['attempts','support','teacherOverrides','reviews'])if(!Array.isArray(raw[k])||raw[k].length>10000)err('Invalid or oversized '+k);const s=clone(raw),defs=groups(s),ids=defs.map(g=>g.id),fieldMap=new Map(defs.flatMap(g=>g.fields.map(f=>[key(g.id,f.id),f])));
if(!obj(s.inputs)||!obj(s.checkpoints))err('Missing input/check records.');for(const [k,v]of Object.entries(s.inputs)){const f=fieldMap.get(k);if(!f&&!/^placard[AB]\.(title|property|source|scaleConfirmed)$/.test(k))err('Unknown answer field.');if(!str(v,f?.kind==='text'?600:f?100:64))err('Overlong answer field.');}
for(const [id,c]of Object.entries(s.checkpoints)){if(!ids.includes(id)||!keys(c,['fingerprint','passed','bypass','overrideId'])||!str(c.fingerprint,12000)||typeof c.passed!=='boolean'||typeof c.bypass!=='boolean'||!(c.overrideId===null||str(c.overrideId,100)))err('Invalid checkpoint record.');if(c.bypass&&!s.teacherOverrides.some(o=>o.id===c.overrideId&&o.group===id))err('Missing bypass history.');}
for(const a of s.attempts){if(!keys(a,['id','group','track','buildRevision','response','fingerprint','passed','at'])||!ids.includes(a.group)||!str(a.id,100)||!['A','B'].includes(a.track)||!Number.isInteger(a.buildRevision)||a.buildRevision<0||a.buildRevision>100||!obj(a.response)||!str(a.fingerprint,12000)||typeof a.passed!=='boolean'||!stamp(a.at))err('Invalid attempt.');const g=getGroup(s,a.group);if(!keys(a.response,g.fields.map(f=>f.id))||Object.entries(a.response).some(([k,v])=>!str(v,g.fields.find(f=>f.id===k)?.kind==='text'?600:100)))err('Invalid attempt response.');}
for(const a of s.support)if(!keys(a,['group','at'])||!ids.includes(a.group)||!stamp(a.at))err('Invalid help history.');
for(const a of s.teacherOverrides)if(!keys(a,['id','group','reviewer','reason','at'])||!ids.includes(a.group)||!str(a.id,100)||!str(a.reviewer,64)||!a.reviewer.trim()||!str(a.reason,400)||!a.reason.trim()||!stamp(a.at))err('Invalid override history.');
for(const a of s.reviews)if(!keys(a,['type','track','reviewer','role','status','note','fingerprint','at'])||!['inspection','interpretation','C121','C122'].includes(a.type)||!['A','B'].includes(a.track)||!str(a.reviewer,64)||!a.reviewer.trim()||!['teacher','peer'].includes(a.role)||(a.type!=='inspection'&&a.role!=='teacher')||!['pending','accepted','repair-needed'].includes(a.status)||!str(a.note,400)||!a.note.trim()||!str(a.fingerprint,12000)||!stamp(a.at))err('Invalid review history.');
s.imported=imported||s.imported;for(const id of Object.keys(s.checkpoints))if(s.checkpoints[id].passed&&Object.keys(evaluate(s,id)).length)s.checkpoints[id].passed=false;return s}
function parseImport(text){const size=new TextEncoder().encode(text).length;if(size>25*1024*1024)throw Error('Backup files must be at most 25 MiB.');let p;try{p=JSON.parse(text)}catch{throw Error('Choose a valid JSON progress file.')}if(p?.schema==='mcada-project-progress-bundle'){if(p.schemaVersion!=='1.0.0'||p.projectId!=='powers-of-ten'||!Array.isArray(p.sessions)||p.sessions.length<1||p.sessions.length>25||Object.keys(p).some(k=>!['schema','schemaVersion','projectId','exportedAt','sessions'].includes(k)))throw Error('Invalid Powers of Ten backup.');if(new Set(p.sessions.map(s=>s.sessionId)).size!==p.sessions.length)throw Error('Duplicate session IDs in backup.');return p.sessions.map(s=>{if(new TextEncoder().encode(JSON.stringify(s)).length>5*1024*1024)throw Error('Each session must be at most 5 MiB.');return validateSession(s)})}if(size>5*1024*1024)throw Error('A session file must be at most 5 MiB.');return [validateSession(p)]}
function bundle(sessions){if(!sessions.length||sessions.length>25)throw Error('A backup supports 1–25 sessions; export individual sessions if more exist.');return {schema:'mcada-project-progress-bundle',schemaVersion:'1.0.0',projectId:'powers-of-ten',exportedAt:now(),sessions}}
class Store{constructor(storage){this.storage=storage;this.available=false;try{storage.setItem(PREFIX+'probe','1');this.available=storage.getItem(PREFIX+'probe')==='1';storage.removeItem(PREFIX+'probe')}catch{}}ids(){const a=[];if(!this.available)return a;for(let i=0;i<this.storage.length;i++){const k=this.storage.key(i);if(k?.startsWith(PREFIX+'session:'))a.push(k.slice((PREFIX+'session:').length))}return a}read(id){const x=this.storage.getItem(PREFIX+'session:'+id);return x===null?null:validateSession(JSON.parse(x),false)}list(){return this.ids().map(id=>{try{return{id,session:this.read(id)}}catch(e){return{id,error:e.message}}})}saveMany(sessions){if(!this.available)throw Error('Storage unavailable. Export progress before closing.');const ks=sessions.map(s=>PREFIX+'session:'+s.sessionId),ix=PREFIX+'index',old=new Map([...ks,ix].map(k=>[k,this.storage.getItem(k)]));try{sessions.forEach((s,i)=>this.storage.setItem(ks[i],JSON.stringify(s)));this.storage.setItem(ix,JSON.stringify(this.ids()))}catch{let restored=true;for(const [k,v]of old){try{v===null?this.storage.removeItem(k):this.storage.setItem(k,v)}catch{restored=false}}throw Error(restored?'Saving failed. Previous records retained; export current work.':'Saving and rollback failed. Keep this page open and export current work.')}}save(s){const prior=this.read(s.sessionId);if(prior&&prior.localRevision>s.localRevision)throw Error('CONFLICT');const rev=s.localRevision,date=s.updatedAt;s.localRevision++;s.updatedAt=now();try{this.saveMany([s])}catch(e){s.localRevision=rev;s.updatedAt=date;throw e}}remove(ids){let bad=[];for(const id of ids)try{this.storage.removeItem(PREFIX+'session:'+id);if(this.storage.getItem(PREFIX+'session:'+id)!==null)bad.push(id)}catch{bad.push(id)}try{this.storage.setItem(PREFIX+'index',JSON.stringify(this.ids()))}catch{bad.push('index')}if(bad.length)throw Error('Deletion incomplete. Remaining records: '+bad.join(', '))}}
function diagnostics(){return [['Tiny exact value',q('2e-4').eq(q('8e-6').mul(25))],['Zero rejected',!q(0).eq('8e-6')],['Cosmic scale',q('.02').div('1.28e7').eq('1/640000000')],['Moon exact diameter',q('3.5e6').div(640000000).mul(1000).eq('5.46875')],['Common scale',q('1.28e7').div('8e-6').eq('1.6e12')],['Signed exponent',sci('3.15','−5').eq('0.0000315')]].map(([name,passed])=>({name,passed}))}
root.SNLegacy={VERSION,CONTENT,PREFIX,Q,q,dec,integer,sci,ten,eq,mm,now,clone,uid,stages,objects,sources,ops,measurements,help,newSession,groups,getGroup,key,raw,activeGroups,fingerprint,evaluate,status,ok,check,setInput,fit,reviewFingerprint,reviewState,review,bypass,placardData,labelsOK,submissionOK,outcome,missing,duplicate,validateSession,parseImport,bundle,Store,diagnostics};if(typeof module!=='undefined')module.exports=root.SNLegacy;
})(globalThis);
