const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),{answers,shared}=require('./core.test.cjs');
const root=path.resolve(__dirname,'..'),out=process.env.QA_OUTPUT||path.join(root,'docs/verification');fs.mkdirSync(out,{recursive:true});const checks=[],ok=(v,label)=>{assert.ok(v,label);checks.push({label,passed:true})};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1365,height:980},acceptDownloads:true});await context.setOffline(true);const p=await context.newPage(),exceptions=[],network=[];p.on('pageerror',e=>exceptions.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url())});
const click=async a=>p.locator('[data-action="'+a+'"]').first().click(),stage=async n=>ok(await p.locator('.stages .active').getAttribute('data-stage')===String(n),'stage '+n+' errors '+await p.locator('#errors').allTextContents()),fill=async values=>{for(const[k,v]of Object.entries(values)){const el=p.locator('[data-field="'+k+'"]');if(await el.count()!==1||!await el.isVisible()||!await el.isEnabled())continue;const tag=await el.evaluate(e=>e.tagName);if(tag==='SELECT')await el.selectOption(v);else if(tag==='FIELDSET'){for(const cb of await el.locator('input').all())await cb.setChecked(v.split(',').includes(await cb.getAttribute('value')))}else await el.fill(v)}};
try{
await p.goto('file://'+root+'/index.html');await p.screenshot({path:path.join(out,'home.png'),fullPage:true});await click('new');await p.locator('#team-alias').fill('QA Festival');await p.locator('#truck-name').fill('The Golden Spoon');await p.locator('[data-meta="brief"]').check();await click('next');await stage(2);await fill(answers());await click('next');await stage(3);
await fill({...answers(),base_grain:'9'});await p.locator('[data-action="check"][data-group="C02"]').click();ok(await p.locator('#errors').count()===1,'wrong ingredient blocked');ok((await p.locator('#f-base_vegetables').locator('..').textContent()).includes('Checked'),'correct cost sibling retained');await p.locator('[data-action="help"][data-group="C02"]').click();ok((await p.locator('.dialog').textContent()).includes('$72'),'help different values');await p.keyboard.press('Escape');ok(await p.locator('[data-action="help"][data-group="C02"]').evaluate(e=>e===document.activeElement),'help focus returned');await fill({base_grain:'10'});await click('next');await stage(4);await fill(answers());await click('next');await stage(5);await fill(answers());await click('next');await stage(6);await fill(answers());await click('next');await stage(7);await fill(answers());await click('next');await stage(8);
ok((await p.locator('#main').textContent()).includes('Create Plan B'),'first launch ready for revision');const snapshotA=await p.evaluate(()=>JSON.parse(Object.values(localStorage).find(x=>x.includes('QA Festival')&&x.includes('mcada-project-progress'))).plans.A);ok(snapshotA.frozen,'Plan A frozen');
await click('createB');await stage(6);await p.locator('[data-plan="p"]').selectOption('15');await p.locator('[data-plan="q"]').selectOption('60');await p.locator('[data-stage="2"]').click();await fill(answers(15,60));await click('next');await stage(3);await fill(answers(15,60));await click('next');await stage(4);await fill(answers(15,60));await click('next');await stage(5);await fill(answers(15,60));await click('next');await stage(6);await fill(answers(15,60));await click('next');await stage(7);await fill(answers(15,60));await click('next');await stage(8);await fill(shared);await click('finish');ok(!(await p.locator('#errors').count()),'final submission no errors');ok((await p.locator('#main').textContent()).includes('Festival success'),'full journey top ending');
const downloadPromise=p.waitForEvent('download');await click('export');const download=await downloadPromise,text=fs.readFileSync(await download.path(),'utf8'),saved=JSON.parse(text);fs.writeFileSync(path.join(out,'completed-session.json'),text);ok(saved.plans.A.p===12&&saved.plans.A.q===100&&saved.plans.B.p===15&&saved.plans.B.q===60,'export retains both plan identities');ok(saved.attempts.filter(a=>a.key==='base_grain'&&a.plan==='A').map(a=>a.passed).join(',')==='false,true','first mistake/correction retained');ok(saved.lessonSwaps.join(',')==='1,2','role swaps recorded once');
await p.reload();await click('sessions');await click('resume');await stage(8);ok((await p.locator('#main').textContent()).includes('Festival success'),'resume retains outcome');await click('report');ok(await p.locator('#print-root .paper').count()===4,'four student sections');ok(!(await p.locator('#print-root').textContent()).includes('answer reference'),'no teacher key in student report');for(const format of ['A4','Letter'])await p.pdf({path:path.join(out,'student-'+format+'.pdf'),format,printBackground:true});await click('close');await click('menu');await p.pdf({path:path.join(out,'menu-A4.pdf'),format:'A4',printBackground:true});await click('close');await click('teacher');await click('teacherPrint');for(const format of ['A4','Letter'])await p.pdf({path:path.join(out,'teacher-'+format+'.pdf'),format,printBackground:true});await click('close');await click('teacher');await click('slips');ok(!(await p.locator('#print-root').textContent()).includes('9x−360'),'transfer slips omit key');await p.pdf({path:path.join(out,'transfer-slips.pdf'),format:'A4',printBackground:true});await click('close');
for(const [w,h]of [[768,1024],[1024,768],[390,844]]){await p.setViewportSize({width:w,height:h});ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow '+w);await p.screenshot({path:path.join(out,'layout-'+w+'.png'),fullPage:true});}await p.setViewportSize({width:1365,height:980});
await click('sessions');const chooser=p.waitForEvent('filechooser');await click('import');await(await chooser).setFiles(path.join(out,'completed-session.json'));await p.getByRole('heading',{name:'Review import',exact:true}).waitFor();ok((await p.locator('.dialog').textContent()).includes('1 session(s) validated'),'actual exported file validates');await click('importCopies');ok((await p.locator('#main').textContent()).includes('Festival success'),'imported complete copy works');await click('sessions');ok(await p.locator('[data-action="resume"]').count()===2,'import copy preserves original');await click('delete');await p.locator('[data-action="sessions"]').filter({hasText:'Cancel'}).click();ok(await p.locator('[data-action="resume"]').count()===2,'delete cancellation');const backupWait=p.waitForEvent('download');await click('backup');const backup=await backupWait;const backupPath=path.join(out,'backup.json');await backup.saveAs(backupPath);ok(JSON.parse(fs.readFileSync(backupPath)).sessions.length===2,'bundle includes both records');await p.evaluate(()=>localStorage.setItem('mcada:road-trip:session:sentinel','preserve'));await click('clearAll');await click('confirmDelete');ok(await p.locator('[data-action="resume"]').count()===0,'clear-all clears complete Food Truck sessions');ok(await p.evaluate(()=>localStorage.getItem('mcada:road-trip:session:sentinel'))==='preserve','other project retained');const restore=p.waitForEvent('filechooser');await click('import');await(await restore).setFiles(backupPath);await p.getByRole('heading',{name:'Review import',exact:true}).waitFor();await click('importCopies');await click('sessions');ok(await p.locator('[data-action="resume"]').count()===2,'backup restored after deletion');await click('close');
// All ten help groups through rendered controls, including original and revision screens.
for(const[n,groups]of [[2,['C01']],[3,['C02']],[4,['C03']],[5,['C04','C05','C06']],[6,['C07']],[7,['C08']],[8,['C09','C10']]]){await p.locator('[data-stage="'+n+'"]').click();for(const g of groups){await p.locator('[data-action="help"][data-group="'+g+'"]').click();ok(await p.locator('.dialog h3').count()===3,'help sections '+g);await p.keyboard.press('Escape');}}
await click('teacher');await click('diagnostics');ok(!(await p.locator('.dialog').textContent()).includes('Failed'),'diagnostic passes');await click('close');ok(exceptions.length===0,'zero uncaught exceptions: '+exceptions.join(';'));ok(network.length===0,'zero external runtime requests');fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({passed:checks.length,failed:0,checks,exceptions,network,browser:await browser.version(),node:process.version,environment:'Linux local file, offline Chromium'},null,2));console.log(checks.length+' browser assertions passed.');
}catch(e){await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.txt'),(await p.locator('body').innerText())+'\n'+e.stack);throw e;}finally{await browser.close()}
})();
