/* Application engine tests with independent literal fixtures from the specification. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../src/core.js'),F=require('./reference-cases-v0.1.0.json');let checks=[];const ok=(condition,label)=>{assert.ok(condition,label);checks.push({label,passed:true})},eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks.push({label,passed:true})},reject=(fn,label)=>{assert.throws(fn);checks.push({label,passed:true})};
function answers(p=12,q=100){const price=F.prices.find(r=>+r.price===p),recipe=F.recipes.find(r=>r.stock===q),launch=F.launches.find(r=>+r.price===p&&r.stock===q);const v={factor:String(recipe.factor),baseTotal:'90',preparedTotal:recipe.total,unitCost:'4.5',fixedTotal:'450',class_stall:'fixed',class_hire:'fixed',class_setup:'fixed',contribution:price.contribution,markup:price.markup,markupBase:'cost',contributionMeaning:'cover',revenueRule:p+'x',expenseRule:'450+4.5x',profitRule:price.contribution+'x-450',profitSlope:price.contribution,profitConstant:'-450',domain:'whole',assumption:'all',breakEquation:p+'x=450+4.5x',crossing:price.crossing,firstNonLoss:String(price.firstNonLoss),firstProfit:String(price.firstProfit),profitBefore:price.profitBefore,profitAt:price.profitAt,breakMeaning:'strict',xAxis:'portions',yAxis:'USD',xStep:'20',yStep:'200',crossX:price.crossing,crossY:price.crossingRevenue,lossAt30:price.profitAt30,lossMeaning:'expense',capacity:'96',forecastDemand:String(price.demand),sales:String(launch.sales),limits:launch.limits.join(','),actualRevenue:launch.revenue,actualExpense:launch.expense,actualProfit:launch.profit,waste:String(launch.waste),wastePercent:launch.wastePercent,sellThrough:launch.sellThrough,costBasis:'prepared',overstatement:String(launch.waste*4.5)};
F.base.ingredients.forEach((r,i)=>Object.assign(v,{['qty_'+r.id]:recipe.quantities[i],['base_'+r.id]:r.expectedLineCost,['prepared_'+r.id]:recipe.lineCosts[i],['class_'+r.id]:'variable'}));[0,60,100].forEach((x,i)=>{v['tableR'+x]=price.revenueTable[i];v['tableC'+x]=String([450,720,900][i]);for(const k of ['R','C']){v['point'+k+x+'X']=String(x);v['point'+k+x+'Y']=k==='R'?price.revenueTable[i]:String([450,720,900][i])}});return v;}
const shared={deltaProfit:'0',deltaWaste:'-10',chosenPlan:'B',evidenceMetric:'profit',evidenceValue:'180',reason:'Plan B earns the same profit and leaves no meals unsold.',transferModeA:'digital',transferModeB:'digital',transferARule:'9x-360',transferACross:'40',transferAFirst:'41',transferBRevenue:'560',transferBExpense:'480',transferBProfit:'80',transferBWaste:'14',transferBSell:'80',transferBBasis:'prepared'};
function fillPlan(s,pid,p=12,q=100){s.activePlan=pid;s.plans[pid].p=p;s.plans[pid].q=q;Object.assign(s.plans[pid].raw,answers(p,q));for(const g of ['C01','C02','C03','C04','C05','C06','C07','C08'])assert.deepEqual(C.check(s,g),[],'complete '+pid+' '+g);}
function completed(){const s=C.newSession('QA Festival');s.truckName='The Golden Spoon';s.brief=true;s.maxStage=8;s.currentStage='FT-S08';fillPlan(s,'A');C.freeze(s);C.createB(s);fillPlan(s,'B',15,60);Object.assign(s.raw,shared);C.check(s,'C09');C.check(s,'C10');s.currentStage='FT-S08';return s;}
class Memory{constructor(){this.map=new Map();this.failKey=null;this.failOnce=false}get length(){return this.map.size}key(i){return [...this.map.keys()][i]??null}getItem(k){return this.map.get(k)??null}setItem(k,v){if(k===this.failKey){if(this.failOnce)this.failKey=null;throw Error('quota')}this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}}
function run(){
for(const row of F.launches){const m=C.model(+row.price,row.stock);for(const k of ['s','revenue','expense','profit','waste','wastePercent','sellThrough']){const field={s:'sales'}[k]||k,actual=m[k]?.str?m[k].str():String(m[k]);eq(C.numeric(actual).str(),C.numeric(String(row[field])).str(),row.id+' '+k)}eq(m.limits,row.limits,row.id+' limits');eq(C.business(m).title,row.ending,row.id+' ending');const s=C.newSession();fillPlan(s,'A',+row.price,row.stock);ok(C.allPlanOK(s,'A'),row.id+' all actual evaluators');}
for(const p of F.prices){const m=C.model(+p.price);eq(m.crossing.str(),C.numeric(p.crossing).str(),'crossing '+p.price);eq(m.firstProfit,p.firstProfit,'strict profit '+p.price);eq(m.firstNonLoss,p.firstNonLoss,'nonloss '+p.price)}
for(const x of ['12x-(450+4.5x)','(15/2)x-450','7.50x−450'])ok(C.equivalent(x,'7.5',-450),'equivalent '+x);
ok(!C.equivalent('8x-480','7.5',-450),'same root wrong rule rejected');for(const x of ['x*x','x/2x','1/0','y+1','1e3','1,2','x**2','9'.repeat(13),'('.repeat(13)+'x'+')'.repeat(13)])reject(()=>C.linear(x),'bad expression '+x);
for(const x of ['12x=450+4.5x','7.5x-450=0','0=15x-900'])ok(C.equation(x,7.5,-450),'equivalent equality '+x);
ok(!C.equation('0=0',7.5,-450),'identity not break-even');eq(C.numeric('9/2 USD/portion','USD/portion').str(),'9/2','rate fraction');reject(()=>C.numeric('4.5 USD/portion','USD'),'rate cannot be total');reject(()=>C.numeric('4.5 USD','USD/portion'),'total cannot be rate');eq(C.numeric('$1,080.00','USD').str(),'1080','valid currency grouping');reject(()=>C.numeric('1,08','USD'),'bad thousands separator');eq(C.q('166.65').round(1).str(),'1667/10','half-up percent');
for(const r of F.boundaryThresholds){const m=C.model(+r.price,100,r.fixed,r.variable,90);eq(m.crossing?.str()??null,r.crossing,'boundary '+r.id);eq(m.firstProfit,r.firstProfit,'boundary first profit '+r.id)}
const zero=C.model(12,0);eq(zero.wastePercent,null,'zero stock percentage');eq(zero.profit.str(),'-450','zero stock cost');
for(const r of F.endingBoundaries){eq(C.business({profit:C.q(r.profit),waste:r.waste,q:r.stock}).title,r.ending,'exact ending cutoff '+JSON.stringify(r))}
let s=completed();eq(C.outcome(s).code,'success','complete top outcome');const before=JSON.stringify(s.plans.A),oldExpense=C.fieldState(s,'expenseRule');C.changePlan(s,'q',80);eq(JSON.stringify(s.plans.A),before,'Plan A immutable');eq(C.fieldState(s,'profitRule'),'verified','stock preserves sold-all model');eq(C.fieldState(s,'preparedTotal'),'needsRecheck','stock invalidates prepared expense');eq(C.outcome(s).code,'draft','edit creates draft');C.changePlan(s,'p',12);eq(C.fieldState(s,'expenseRule'),oldExpense,'price preserves expense model');eq(C.fieldState(s,'revenueRule'),'needsRecheck','price invalidates revenue model');s.activePlan='A';reject(()=>C.changePlan(s,'q',60),'frozen plan cannot change');
s=completed();s.raw.deltaProfit='99';ok(C.check(s,'C09').some(x=>x.key==='deltaProfit'),'wrong comparison rejected');eq(C.fieldState(s,'deltaWaste'),'verified','correct sibling retained');s.raw.deltaProfit='0';C.check(s,'C09');eq(s.attempts.filter(x=>x.key==='deltaProfit').map(x=>x.passed),[true,false,true],'historical corrected attempts preserved');
s=completed();s.raw.transferModeA='paper';C.check(s,'C10');eq(C.outcome(s).code,'draft','paper mode alone incomplete');C.review(s,'transferModeA','Teacher','Paper response received');eq(C.outcome(s).code,'success','recorded paper permits story with pending review');eq(C.reviewStatus(s,'transferModeA'),'pending','paper review remains pending');
s=completed();s.raw.transferBProfit='';C.bypass(s,'C10','Teacher','Input inaccessible');eq(C.outcome(s).code,'provisional','bypass is provisional');s.raw.transferBProfit='80';C.check(s,'C10');eq(C.outcome(s).code,'success','real recheck retires active bypass');ok(s.teacherOverrides.length===1,'bypass history retained');
s=C.newSession();s.maxStage=8;fillPlan(s,'A');s.plans.A.raw.factor='';C.bypass(s,'C01','Teacher','Access need');C.freeze(s);C.createB(s);eq(C.fieldState(C.parseImport(JSON.stringify(s))[0],'factor'),'overridden','carried teacher bypass survives import');
s=completed();const restored=C.parseImport(JSON.stringify(s))[0];eq(C.outcome(restored).code,'success','import revalidates complete session');ok(restored.imported,'import marked');const forged=C.clone(s);forged.plans.B.raw.actualProfit='999';eq(C.fieldState(C.validateSession(forged),'actualProfit'),'needsRecheck','forged verified rechecked');
for(const mutate of [x=>x.projectId='road-trip',x=>x.schemaVersion='2.0.0',x=>x.plans.B.q=0,x=>x.plans.B.p=14,x=>x.raw.extra='bad',x=>x.plans.B.history.push({p:1,q:2}),x=>x.attempts[0].key='unknown',x=>x.currentStage='FT-S99']){const a=C.clone(s);mutate(a);reject(()=>C.parseImport(JSON.stringify(a)),'invalid import rejected');}
reject(()=>C.parseImport('{broken'),'malformed JSON');reject(()=>C.parseImport('x'.repeat(5*1024*1024+1)),'oversized import');reject(()=>C.parseImport(JSON.stringify(C.bundle([s,s]))),'duplicate bundle identities');
const storage=new Memory(),store=new C.Store(storage);storage.setItem('mcada:road-trip:session:other','untouched');store.save(s);eq(C.outcome(store.read(s.sessionId)).code,'success','local resume');ok(!store.read(s.sessionId).imported,'local resume not imported');const copy=C.duplicate(s);store.save(copy);eq(store.ids().length,2,'independent duplicate');const old=storage.getItem(C.PREFIX+'session:'+s.sessionId),next=C.clone(s);next.teamAlias='Changed';storage.failKey=C.PREFIX+'index';storage.failOnce=true;reject(()=>store.saveMany([next]),'atomic failure reported');eq(storage.getItem(C.PREFIX+'session:'+s.sessionId),old,'atomic rollback restores');const stale=C.clone(s);store.save(s);reject(()=>store.save(stale),'newer revision conflict');store.remove([copy.sessionId]);eq(store.ids().length,1,'one-session deletion');store.remove(store.ids());eq(store.ids().length,0,'clear all');eq(storage.getItem('mcada:road-trip:session:other'),'untouched','other project retained');ok(!new C.Store(null).available,'denied storage detected');
const out=process.env.QA_OUTPUT||path.resolve(__dirname,'../docs/verification');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'core-results.json'),JSON.stringify({scope:'Actual Food Truck core, parser, state and storage',passed:checks.length,failed:0,checks},null,2));console.log(checks.length+' core assertions passed.');return checks.length;
}
module.exports={answers,shared,completed,Memory};if(require.main===module)run();
