const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),C=require('../src/core.js'),{completed,answers,shared}=require('./core.test.cjs');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/verification'),checks=[];
const ok=(v,label)=>{assert.ok(v,label);checks.push({label,passed:true})};
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']}),ctx=await browser.newContext({viewport:{width:768,height:1024},hasTouch:true,acceptDownloads:true}),p=await ctx.newPage();await ctx.setOffline(true);const errors=[];p.on('pageerror',e=>errors.push(e.message));const click=a=>p.locator('[data-action="'+a+'"]').first().click();
async function seed(s){await p.goto('file://'+root+'/index.html');await p.evaluate(({s,prefix})=>{localStorage.clear();localStorage.setItem(prefix+'session:'+s.sessionId,JSON.stringify(s));localStorage.setItem(prefix+'index',JSON.stringify([s.sessionId]))},{s,prefix:C.PREFIX});await p.reload();await click('sessions');await click('resume')}
try{
let s=completed();await seed(s);await click('glossary');ok((await p.locator('.dialog').textContent()).includes('Contribution'),'glossary available at tablet width');await p.keyboard.press('Escape');
await click('viewA');await p.locator('[data-stage="4"]').click();ok(await p.locator('[data-plan="p"]').isDisabled(),'preserved A price disabled');await p.locator('[data-stage="8"]').click();await click('freshCopy');ok((await p.locator('body').textContent()).includes('Plan A'),'fresh comparison created');
// Teacher bypass may advance a checkpoint without silently turning into a failed check.
s=C.newSession('Bypass QA');s.truckName='Test Truck';s.brief=true;s.currentStage='FT-S02';s.maxStage=2;await seed(s);await click('teacher');await p.locator('#reviewer').fill('Teacher');await p.locator('#bypass-group').selectOption('C01');await p.locator('#bypass-reason').fill('Accessibility review');await click('bypass');await click('next');ok(await p.locator('.stages .active').getAttribute('data-stage')==='3','bypass permits Next without regrading');
s=completed();s.raw.transferBProfit='';C.bypass(s,'C10','Teacher','Recorded assistance');await seed(s);await click('finish');ok((await p.locator('#main').textContent()).includes('Provisional — teacher review'),'finish preserves provisional bypass');
// Paper submission is recorded through the teacher UI.
s=completed();s.raw.transferModeA='paper';C.check(s,'C10');await seed(s);ok((await p.locator('#main').textContent()).includes('Draft — finish checks'),'paper selection alone draft');await click('teacher');await p.locator('#reviewer').fill('Teacher');await p.locator('#review-key').selectOption('transferModeA');await p.locator('#review-note').fill('Paper received and reviewed');await p.locator('#review-status').selectOption('verified');await click('review');await click('finish');ok((await p.locator('#main').textContent()).includes('Festival success'),'recorded paper completes story');
// Render valid loss and viable outcomes, with independently specified price/stock results.
for(const [price,stock,title,profit,waste]of [[9,100,'Business rethink',-36,4],[12,60,'Viable first launch',0,0]]){s=completed();s.plans.B.p=price;s.plans.B.q=stock;Object.assign(s.plans.B.raw,answers(price,stock));s.activePlan='B';for(const g of ['C01','C02','C03','C04','C05','C06','C07','C08'])C.check(s,g);Object.assign(s.raw,shared,{deltaProfit:String(profit-180),deltaWaste:String(waste-10),evidenceValue:String(profit)});C.check(s,'C09');C.check(s,'C10');await seed(s);await click('finish');ok((await p.locator('#main').textContent()).includes(title),'rendered ending '+title)}
// Local cross-tab revision conflict, reload and preserving edits as copy.
s=completed();await seed(s);async function newer(){await p.evaluate(prefix=>{const key=Object.keys(localStorage).find(k=>k.startsWith(prefix+'session:')),x=JSON.parse(localStorage.getItem(key));x.localRevision+=10;x.teamAlias='Other tab';localStorage.setItem(key,JSON.stringify(x))},C.PREFIX)}await newer();await click('save');ok((await p.locator('.dialog').textContent()).includes('Newer saved work'),'conflict disclosed');await click('conflictReload');ok((await p.locator('body').textContent()).includes('Loaded the newer saved revision'),'conflict reload');await newer();await click('save');await click('conflictCopy');await click('sessions');ok(await p.locator('[data-action="resume"]').count()===2,'conflict copy retains both');await click('duplicate');await click('sessions');ok(await p.locator('[data-action="resume"]').count()===3,'ordinary duplicate');await click('delete');const dl=p.waitForEvent('download');await click('deleteBackup');const backup=await dl;ok(JSON.parse(fs.readFileSync(await backup.path(),'utf8')).sessions.length===1,'pre-delete backup contains selected session');await click('confirmDelete');ok(await p.locator('[data-action="resume"]').count()===2,'single deletion retains others');await click('close');
// Print command dispatch and diagnostics export.
await click('teacher');const dg=p.waitForEvent('download');await click('diagnosticExport');ok(JSON.parse(fs.readFileSync(await(await dg).path(),'utf8')).appVersion==='0.1.0','diagnostic download version');await click('close');await click('report');await p.evaluate(()=>{window.print=()=>{document.body.dataset.printCalled='yes'}});await click('print');ok(await p.locator('body').getAttribute('data-print-called')==='yes','native print command dispatched');await click('close');
await p.evaluate(()=>document.documentElement.style.fontSize='32px');ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'200 percent root text no page overflow');await p.screenshot({path:path.join(out,'tablet-text-200.png'),fullPage:true});
// Imported strings stay inert, unsupported graph intervals are bounded, replacements are explicit.
s=completed();s.truckName='<img src=x onerror=alert(1)>';s.plans.B.raw.xStep='-1';s.plans.B.raw.yStep='0.00000001';s.raw.reason='A numerical recommendation. '.repeat(22).slice(0,600);s.plans.B.raw.profitRule='(21/2)x-450';C.check(s,'C04');await seed(s);await p.locator('[data-stage="5"]').click();ok(await p.locator('svg.graph').count()>0,'unsupported imported graph intervals bounded');ok(await p.locator('img').count()===0,'imported markup inert');await click('report');ok(!(await p.locator('#print-root .formula').last().innerHTML()).includes('fraction'),'fraction coefficient expression retains grouping');await p.pdf({path:path.join(out,'long-reason-Letter.pdf'),format:'Letter',printBackground:true});await click('close');
const importPath=path.join(out,'replacement-fixture.json');fs.writeFileSync(importPath,JSON.stringify(completed()));await seed(completed());async function chooseImport(){await click('sessions');const chooser=p.waitForEvent('filechooser');await click('import');await(await chooser).setFiles(importPath);await p.getByRole('heading',{name:'Review import',exact:true}).waitFor()}
await chooseImport();await click('confirmReplace');await p.locator('[data-action="sessions"]').filter({hasText:'Cancel'}).click();ok(await p.locator('[data-action="resume"]').count()===1,'replacement cancel retains local work');await click('close');await chooseImport();await click('confirmReplace');await click('importReplace');ok((await p.locator('#main').textContent()).includes('Festival success'),'explicit imported replacement loaded');
// Denied storage still allows starting work and exporting.
const denied=await ctx.newPage();await denied.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Denied','SecurityError')}}));await denied.goto('file://'+root+'/index.html');await denied.locator('[data-action="new"]').click();ok((await denied.locator('body').textContent()).includes('Device storage is unavailable'),'storage denied visible');const lost=denied.waitForEvent('download');await denied.locator('[data-action="export"]').click();ok(JSON.parse(fs.readFileSync(await(await lost).path(),'utf8')).projectId==='food-truck','export when storage denied');await denied.close();ok(errors.length===0,'no edge workflow exceptions');fs.writeFileSync(path.join(out,'edge-results.json'),JSON.stringify({passed:checks.length,failed:0,checks,errors},null,2));console.log(checks.length+' edge browser assertions passed');
}finally{await browser.close()}})();
